### ISSUE TITLE
How to specify version for IDE like CLion?

### ISSUE THREAD

**Issue by RobinQu** [loft-sh/devpod#1003]
When creating workspace using Clion, I noticed devpod is using  CLion-2023.2.2.tar.gz, which is old version.  So how to specify the version to use in devpod. Or is it managed by you, and cannot be modfiy easily?

**Comment by shanman190** [comment]
Hey @RobinQu, I just submitted a PR that was merged earlier to get this upgraded to 2024.1. I'm also planning to go ahead and submit another PR to actually swap over to the dynamic download links for the JetBrains products as well.

See https://github.com/loft-sh/devpod/pull/1002 for more details.

**Comment by RobinQu** [comment]
> Hey @RobinQu, I just submitted a PR that was merged earlier to get this upgraded to 2024.1. I'm also planning to go ahead and submit another PR to actually swap over to the dynamic download links for the JetBrains products as well.
> 
> See #1002 for more details.

What a coincidence!

**Comment by pascalbreuninger** [comment]
Just to add to this: @shanman190 create [this](https://github.com/loft-sh/devpod/pull/1006) PR to always fall back to the latest version.
Alternatively you can use `devpod ide set-options intellij -o VERSION=2024.1` to set it manually

**Comment by RobinQu** [comment]
> Just to add to this: @shanman190 create [this](https://github.com/loft-sh/devpod/pull/1006) PR to always fall back to the latest version. Alternatively you can use `devpod ide set-options intellij -o VERSION=2024.1` to set it manually

Following command is executed in my pod, and it still downloads 2023.2.

```
devpod ide set-options clion-o VERSION=2024.1 
```

**Comment by pascalbreuninger** [comment]
@RobinQu can you confirm it's updated with `devpod ide options clion`? 
I just tried this and the logs included `15:00:59 info Download CLion from https://download.jetbrains.com/cpp/CLion-2024.1-aarch64.tar.gz`. Maybe you'll have to recreate the workspace?

**Comment by pascalbreuninger** [comment]
and with a completely new workspace?

**Comment by RobinQu** [comment]
> and with a completely new workspace?


To reproduce:

1. Create a new workspace with no IDE selected in a K8S provider.

<img width="1198" alt="image" src="https://github.com/loft-sh/devpod/assets/342549/b85b4333-6b48-4ac2-9af4-ca49e51d9c2d">


2. Wait for POD ready.

[pod.txt](https://github.com/loft-sh/devpod/files/15026392/pod.txt)

3. Set IDE version in POD in interactive shell via k9s.

![image](https://github.com/loft-sh/devpod/assets/342549/e60b5b65-dd52-4348-851e-83143adf018d)

4. In devpod's dashboard, hower on the button with three dots of created workspace, and choose open with  Clion in the popup menu.


5. devpod is busy preparing IDE. And it shows it's still downloading old version of Clion.

<img width="1198" alt="image" src="https://github.com/loft-sh/devpod/assets/342549/0dfb7abf-cbc9-49b6-a545-980cdf8da72e">

**Comment by shanman190** [comment]
So you need to set the version on the local machine, not inside the k8s pod itself. 

So I'd tear down the workspace, set the version locally, then spin up your workspace and you should now have CLio. 2024.1.

**Comment by RobinQu** [comment]
> devpod ide set-options clion -o VERSION=2024.1

oh. silly of me... I never thought to give a try in the local temrinal.
