### ISSUE TITLE
DevPod image is outdated

### ISSUE THREAD

**Issue by shanman190** [loft-sh/devpod#1005]
**What happened?** 
Presently the devcontainer contained within this repository is directed to use go1.19, but the project requires go1.21 or better in order to utilize the toolchain feature. As a result of this, attempting to build the project using `./hack/rebuild.sh` errors out stating `toolchain` is unknown.

**What did you expect to happen instead?**  
A successful build.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Open the `loft-sh/devpod` project in DevPod and attempt to build it. 😉 

**Local Environment:**  
- DevPod Version: 0.5.5
- Operating System: windows
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Cloud Provider: aws
- Kubernetes Provider: N/A
- Local/remote provider: N/A
- Custom provider: N/A

**Anything else we need to know?**  
I think the above covers it.

**Comment by shanman190** [comment]
As a workaround, I've just installed go1.22 inside the container and that gets it going.

**Comment by pascalbreuninger** [comment]
Ha! Thanks for catching that, updated the Dockerfile :)
