### ISSUE TITLE
use docker not support

### ISSUE THREAD

**Issue by 0xA2618** [loft-sh/devpod#1007]
\[10:20:42\] info Workspace tusimaservermonitor already exists
\[10:20:42\] info Creating devcontainer...
\[10:20:42\] info devcontainer up: find dev container: docker ps: Cannot connect to the Docker daemon at tcp://10.1.1.116:855. Is the docker daemon running?
\[10:20:42\] info exit status 1
\[10:20:43\] error Try enabling Debug mode under Settings to see a more verbose output
\[10:20:43\] fatal run agent command: Process exited with status 1

* 10.1.1.116 is my dockerServer
  root@local116:\~# systemctl status docker
  ● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2024-03-21 15:50:45 CST; 3 weeks 4 days ago
  TriggeredBy: ● docker.socket
       Docs: [https://docs.docker.com](https://docs.docker.com)
   Main PID: 855 (dockerd)
      Tasks: 138
     Memory: 244.0M
        CPU: 33min 20.278s
     CGroup: /system.slice/docker.service

![image](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/03c4f30d-9965-4a2e-85da-333a550ffb1d/5cce124d-8f1f-4323-8e1f-b53a52b05613?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzBhYWIyNTZmLTYxYzQtNDRmNC05YWZmLTE1ZmUwOWMyMDI2Yi8wM2M0ZjMwZC05OTY1LTRhMmUtODVkYS0zMzNhNTUwZmZiMWQvNWNjZTEyNGQtOGYxZi00MzIzLThlMWYtYjUzYTUyYjA1NjEzIiwiaWF0IjoxNzEzMjcxNDgzLCJleHAiOjMzMjgzODMxNDgzfQ.V0lNyuU7Ok7ECpNandwJrGJEPq30e3uLYw_epqqsGwE)

**Comment by pascalbreuninger** [comment]
Hi @zhangyy8lab, thanks for opening the issue.
Can you confirm you're docker cli is able to connect to your host by running
`DOCKER_HOST=10.1.1.116:855 docker ps` please?
