### ISSUE TITLE
Proxy Environment Variables

### ISSUE THREAD

**Issue by Iyappanj** [loft-sh/devpod#1012]
**Is your feature request related to a problem?**  

I want to be able to provide the HTTP_PROXY variables with the "devpod up" command because my environment is behind a corporate proxy and fails with "Get "https://github.com/gitpod-io/openvscode-server/releases/download/openvscode-server-v1.84.2/openvscode-server-v1.84.2-linux-x64.tar.gz": dial tcp 140.82.121.3:443: i/o timeout" error while the provider is kubernetes.

I am also unable to use local docker images to bring up a environment with kubernetes as provider.

**Which solution do you suggest?**  

I should be able to provide the proxy variables in the cli

**Which alternative solutions exist?**  

**Additional context**

**Comment by 89luca89** [comment]
Hi @Iyappanj 
This is possible by using either `devpod up --workspace-env FOO=BAR --workspace-env BAZ=BIZ` and so on, or using an environment file and then `devpod up --workspace-env-file ./path/to/env-file`

**Comment by Iyappanj** [comment]
@89luca89 Thanks for the information.
