### ISSUE TITLE
Rebuild option should first update from repository

### ISSUE THREAD

**Issue by martinbiard** [loft-sh/devpod#1022]
It's been a few weeks since I tried Jetbrains' Gateway and if I recall correctly, whenever I had a bug in my devcontainer and pushed an update to my remote git repository, running rebuild in Gateway would first fetch the update before running the rebuild. I thought this was also convenient if my team ends up adopting this because whenever I would push an update to the devcontainer, I could just tell our devs to run "Rebuild". However, with devpod, running rebuild does not fetch updates, and I am left to delete the pod and re-add again to make sure I have the latest changes from remote.

In my case, I had an error during devcontainer boot, the onCreateCommand failed. I think in such case, fetching updates before rebuild is absolutely necessary since otherwise you cannot do anything more with that pod except delete it and start over. At the very least there should be an option to update from remote to bring back the pod into a useable state.

![Screenshot 2024-04-24 143328](https://github.com/loft-sh/devpod/assets/5204353/24c7c32f-c65d-4266-9cc5-62241c9babe4)

**Comment by martinbiard** [comment]
Actually, nevermind above, I just found out that Reset does exactly what I was looking for, I just had assumed it was like a reboot of the container and never actually tested it before.

**Comment by pascalbreuninger** [comment]
@martinbiard Was about to say that, will close this issue 👍 
Maybe we can add a little info button next to these actions and explain what they're doing
