### ISSUE TITLE
Docker Compose Prebuilds Support

### ISSUE THREAD

**Issue by edulix** [loft-sh/devpod#1025]
**Is your feature request related to a problem?**  
Docker Compose Prebuilds are not fully working, since it fails when pushing the images to the registry with an error like: `Error building image: cannot push to repository`

**Which solution do you suggest?**  
Docker Compose Prebuilds push to registry should work.

**Which alternative solutions exist?**  
Not using prebuilds.

**Additional context**  
None.

**Comment by pascalbreuninger** [comment]
@edulix thanks for opening the issue, we'll look into it 👍
