### ISSUE TITLE
DevPod is launching outdated IDE version

### ISSUE THREAD

**Issue by martinbiard** [loft-sh/devpod#1032]
I only tested this with IntelliJ IDEA, but devpod is launching version `2023.2.4` while the current version is `2024.1`.

My current workaround is adding a CLI option with the version, but it's not ideal because the CLI option is global while an IDE version is something you would want configured per IDE. For example if I don't remove the CLI option, I assume (not tested) it will cause an issue if I open a new workspace with VSCode instead of IntelliJ.

I think it might make sense to have all supported IDEs with a textbox, they could default to "latest" and we could put an exact version in there in case we want to pin it and control upgrades. It would also allow going for release candidate versions (devcontainers being so bleeding edge on the JetBrains side, going for release candidates often makes sense).

**Comment by shanman190** [comment]
So at least part of your issue is already solved by https://github.com/loft-sh/devpod/pull/1006.

VERSION can be set to get both older and prerelease versions as well to enable more specific control.

**Comment by pascalbreuninger** [comment]
@martinbiard I assume Shannons answer solves your problem and will close this issue - let me know if it doesn't
