### ISSUE TITLE
feature apt-get-packages fails with devpod

### ISSUE THREAD

**Issue by behrica** [loft-sh/devpod#1043]
**What happened?**  
Having this snipped in devcontainer.json

```
    "ghcr.io/devcontainers-contrib/features/apt-get-packages:1": {
      "ppas": ["ppa:ubuntuhandbook1/emacs"],
      "packages": "emacs,rlwrap,fonts-hack"
    }
```
fails with error:

19:09:08 info #11 134.8 add-apt-repository -y ppa:[ppa:ubuntuhandbook1/emacs]
19:09:08 info #11 134.8 Unable to handle repository shortcut 'ppa:[ppa:ubuntuhandbook1/emacs]'
while it does work in codespaces

**Local Environment:**  
- DevPod Version: 0.5.4
- Operating System: linux
- ARCH of the OS: i386 

- Local/remote provider: docker

**Comment by behrica** [comment]
It is reproducible from this repo:
https://github.com/scicloj/scicloj.ml.tribuo
`devpod up .`   on it fails as above,
while open in Codespace / VScode does work

**Comment by behrica** [comment]
I put it in its own repro:
https://github.com/behrica/emacs-clojure-devcontainer

**Comment by thecontinium** [comment]
I'm not sure of the correct syntax but If you change the definition to the below it works. I suspect the array is not being processed correctly. 

>     "ghcr.io/devcontainers-contrib/features/apt-get-packages:1": {
>       "ppas": "ppa:ubuntuhandbook1/emacs",
>       "packages": "emacs,rlwrap,fonts-hack"
>     }

This syntax also works with devcontainer cli.
