### ISSUE TITLE
Windows signing is broken

### ISSUE THREAD

**Issue by shanman190** [loft-sh/devpod#1051]
**What happened?**  
Windows Defender is by default warning about the unsigned MSI file. You can use the advanced menu, to force the installation.

**What did you expect to happen instead?**  
The MSI is signed and no longer needs forced trust to install.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Attempt a fresh install the latest 0.5.6 MSI on Windows.

**Local Environment:**  
- DevPod Version: 0.5.6
- Operating System: windows
- ARCH of the OS: AMD64

**Anything else we need to know?**  
N/A

**Comment by pascalbreuninger** [comment]
Thanks for reporting @shanman190, should be fixed again :)
