### ISSUE TITLE
Agent Url Override

### ISSUE THREAD

**Issue by MaGaudin** [loft-sh/devpod#1102]
**What happened?**  
We are trying to use DevPod with AWS as provider. Our VPC does not have internet connectivity (just for few addresses). So, we are trying to override Agent Url with something else. In particular, We download the agent from github and we experimented Bitbucket, AWS Codecommit and AWS S3 presigned URL.

Unfortunately, we always receive errors and we are not able to start dev pod correctly. For example, with AWS S3 presignedUrl We recieved an error saying that the url is too long and not found error trying to launch sh commands on that URL. Clearly, the system is not able to use the generated url correctly.

**What did you expect to happen instead?**  
to override the Agent Url and start a devpod agent on EC2

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Put the agent on an S3 bucket, create a presignedUrl and copy the url in Agent URL Override section.

**Local Environment:**  
- DevPod Version: 0.5.6
- Operating System: windows

**DevPod Provider:**  
- Cloud Provider: aws
- Local/remote provider: docker | ssh

**Comment by pascalbreuninger** [comment]
Hey @MaGaudin, thanks for opening the issue. 
You're right, overwriting the agent URL with presigned URLs won't work because DevPod tries to download the binary for the current VM architecture by appending `devpod-linux-$ARCH` to the `DEVPOD_AGENT_URL` environment variable. 

We could substitute `${BIN_NAME}` in the URL to make this work

**Comment by MaGaudin** [comment]
Hi @pascalbreuninger , 

thank you so much for your reply. Are you going to implement this modification? Or, is there something that we can do (using the console) to implement what you're saying?

**Comment by pascalbreuninger** [comment]
@MaGaudin I've linked a PR with an implementation, will kick off an alpha release for you to test the changes after tests pass. 
You'll need to pass in the agent url through the `DEVPOD_AGENT_URL` environment variable and can then add `${BIN_NAME}` as a placeholder. Make sure to escape the dollar sign if you're on the command line so prevent the shell variable expansion.

**Comment by MaGaudin** [comment]
Hi @pascalbreuninger,

you were really kind. I downloaded the alpha version of DevPod but, after overriding the Agent Url as below:
![image](https://github.com/loft-sh/devpod/assets/139143167/e8f99944-f77a-4f17-bc2f-231bb497d662)


I had the same error as before:
![image](https://github.com/loft-sh/devpod/assets/139143167/ab21e305-f093-41ab-8b32-56c1d3ea0ad5)

Am I doing something wrong?

Marco

**Comment by MaGaudin** [comment]
Is there any update? @pascalbreuninger

**Comment by pascalbreuninger** [comment]
Hey @MaGaudin, can you try again with the latest release please? :)

**Comment by MaGaudin** [comment]
Hey @pascalbreuninger, now i have a different error that is: Content Deadline exceeded exception. Any advise on how to solve this? :)

**Comment by bkneis** [comment]
@MaGaudin devpod now supports extending the agent download timeout, could you try setting `AGENT_INJECT_TIMEOUT` to something like 60 seconds and try again? i.e. `devpod context set-options -o AGENT_INJECT_TIMEOUT=60`
