### ISSUE TITLE
Desktop DevPod fails to locate CLI due to incorrect path

### ISSUE THREAD

**Issue by ndk** [loft-sh/devpod#1124]
**What happened?** 
Cannot configure any provider. I got an error "The system cannot find the file specified. (os error 2) "
<img width="902" alt="image" src="https://github.com/loft-sh/devpod/assets/591500/a732affc-f6dc-415e-8c3a-ad0c67024aee">

Due to the error message's lack of informativeness, I used Procmon from Sysinternals to see what was happening. It's trying to find the CLI in the wrong place.
![image](https://github.com/loft-sh/devpod/assets/591500/80d0f6e4-ac76-4336-98d2-0d285767dd58)

If you copy CLI to "c:\app\bin\devpod-cli.exe" it starts working. If you remove CLI from "c:\app\bin\devpod-cli.exe" it stops working again.

**What did you expect to happen instead?**  
I can configure a new provider without an error.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```
{
    "name": "...",
    ...
}
```

**Local Environment:**  
- DevPod Version: 0.5.14
- Operating System: windows
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Cloud Provider: n/a
- Kubernetes Provider: n/a
- Local/remote provider: n/a
- Custom provider: n/a

**Anything else we need to know?**

**Comment by francoisdtm** [comment]
<img width="1312" alt="image" src="https://github.com/loft-sh/devpod/assets/4825058/94a6a75b-599a-43b8-ac05-45b4bd2348bf">

**Local Environment:**
DevPod Version: 0.5.14 (20240613.064519)
Operating System: macOS 14.5 (23F79)
ARCH of the OS: Apple M1 Pro

**Comment by ndk** [comment]
Yep, it works

**Comment by ndk** [comment]
It seems it's fixed in v0.5.15
