### ISSUE TITLE
Add support for cursor.com IDE (vscode compatible fork)

### ISSUE THREAD

**Issue by jleni** [loft-sh/devpod#1127]
Cursor (cursor.com) is a vscode compatible fork.

https://docs.cursor.com/get-started/migrate-from-vscode

it would be good to have it listed in the IDEs and being able to open on that automatically too.

**Comment by pascalbreuninger** [comment]
Hi @jleni, thanks for opening the issue. Definitely sounds like an interesting addition, although an experimental one to begin with. Maybe it should even be disabled by default 🤔

**Comment by jleni** [comment]
experimental would be more than fine!
Would you be happy to accept a PR?
Could you point me to some similar code that I can bad that on?

**Comment by pascalbreuninger** [comment]
Hey @jleni, #1237 adds support for cursor and will be available with the next stable release :)
