### ISSUE TITLE
Spot/Preemptible cloud instance provisioning

### ISSUE THREAD

**Issue by ysaakpr** [loft-sh/devpod#1128]
**Is your feature request related to a problem?**  
I am very much using the dev pod to almost all backend dev activities. And i found its really worthy if we can use the spot/[Preemptible](https://cloud.google.com/compute/docs/instances/preemptible) instances with cloud that supports it.

**Which solution do you suggest?**  
a configurable choice to use spot instances when using supported cloud providers

**Which alternative solutions exist?**  
No alternatives as of now afaik.

**Additional context**

**Comment by algoORgoal** [comment]
@bbigras 
The feature is needed for us since it can save a lot of budget for us. Is this feasible?
