### ISSUE TITLE
Offer a way to supply GIT credentials

### ISSUE THREAD

**Issue by elronzo** [loft-sh/devpod#1133]
**Is your feature request related to a problem?**  
Cannot use a private GIT repo.

**Which solution do you suggest?**  
Add a way to provide credentials.

**Comment by gorillamoe** [comment]
IDK if this is feasible for you, but you could maybe use a Github PAT to clone a private repo :)

**Comment by pascalbreuninger** [comment]
Hi @elronzo, DevPod automatically forwards the git credentials of your local machine to the workspace. 
If you're able to clone a repository locally you should also be able to create a workspace. This requires you to either use a PAT and git credentials helper like @gorillamoe suggested, or setup an SSH Key for Github authentication
