### ISSUE TITLE
Unable to assign a label for pods

### ISSUE THREAD

**Issue by Iyappanj** [loft-sh/devpod#1134]
**Is your feature request related to a problem?**  
Yes, I am unable to get the exact pod name of the pod created using devpod. I want to create a automation for creation of pod, service and ingress. to do this I need someway to get the pod name or alteast assign a label at every devpod up command

**Which solution do you suggest?**  
Devpod up command should give an option to set the label on each devpod up command

**Which alternative solutions exist?**  
No Idea

**Additional context**

**Comment by pascalbreuninger** [comment]
Hey @Iyappanj, thanks for opening the issue. You can always add labels to a workspace with the kubernetes provider and the `LABELS` option.

**Comment by Iyappanj** [comment]
@pascalbreuninger Thanks for the hint. I already have seen this label in provider level like the below 

devpod provider set-options kubernetes --option etc....

But I am trying to set a dynamic label for each container in runtime, is there a way I can set the label in the devpod up command ? if so can you show some examples

Thanks in Advance

**Comment by pascalbreuninger** [comment]
> is there a way I can set the label in the devpod up command ?

Yes, by running `devpod up ... --provider-option=LABELS=YOUR_LABEL_HERE`. This will overwrite the provider option for this workspace.

 > Also is it possible to provide a unique name to the pod?
 
The pod names should be unique eventually, if you want to customize them you're responsible for their uniqueness. Something like combining a base string with 5-6 random characters should work

**Comment by Iyappanj** [comment]
Hi @pascalbreuninger Thanks for the hints again.  Actually I am trying to set the full name pod name by myself and I see that devpod is taking only 10 characters of what I provide

**Example**:
if I try to set "example-development" as the pod name, devpod is setting it something like "devpod-example-de-90950". here it has taken only "example-de" from the name I provided. In cases where I have another pod named "example-develop"  then it will again take only "example-de" from the name I provide. this will impact me while I try to create a service for the devpod pod because I will be able to search for the pods with name "example-de" to create a service for it and now it will list me two pods with this name.  but my intend would be to create service for "example-development " only.

If I set a label for the pod, then still the service creation expects pod name. 

Is there a way to set the full pod name by myself in the devpod up command ?

**Comment by pascalbreuninger** [comment]
@Iyappanj 
> If I set a label for the pod, then still the service creation expects pod name.

Why does the servide creation expect a pod name? 🤔 

> Is there a way to set the full pod name by myself in the devpod up command ?

Not directly, no. I've misread earlier and thought you were referring to the workspace name

**Comment by Iyappanj** [comment]
@pascalbreuninger Thanks for the info and my bad that I was trying to expose the pod and was thinking that I need the pods name. Now it worked out.

is it possible to start the openvscode server with "token" ? now I see it starts with "--without-connection-token" option.

I tried to get help from the --ide-options command with no luck

**Comment by pascalbreuninger** [comment]
@Iyappanj no worries, that's what we're here for ;) 

About the second issue: There's no built-in mechanism for this yet, but you could open a separate issue and we'll see if there's enough community interest to build it!
