### ISSUE TITLE
Logs go missing after successful build

### ISSUE THREAD

**Issue by isaacncz** [loft-sh/devpod#1135]
**What happened?**  
Upon successful build, when i want to visit back the logs, it goes missing. 
![image](https://github.com/loft-sh/devpod/assets/49158607/1a1a39c0-608f-4f61-9e23-1a4b50f78fc4)

**What did you expect to happen instead?**  
Show the history and append new logs below. 

**Local Environment:**  
- DevPod Version: v0.5.15
- Operating System: windows
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: docker | ssh

**Anything else we need to know?**

**Comment by pascalbreuninger** [comment]
Hi @isaacncz, thanks for reporting the issue. You can always check the logs for the latest action in the notifications menu in the top right corner. Clicking on "Start $YOUR_WORKSPACE` should get you there
