### ISSUE TITLE
Mac OS Sonoma 14.5, if no /usr/local/bin directory exists devpod gets created as bin

### ISSUE THREAD

**Issue by leematos** [loft-sh/devpod#1144]
**What happened?**  
sudo install -c -m 0755 devpod /usr/local/bin

bin did not exist yet (new mac install) and the devpod binary was installed as _bin_.

I ran /user/local/bin and got the devpod output.

**What did you expect to happen instead?**  
devpod to get created in /user/local/bin 

**How can we reproduce the bug?** (as minimally and precisely as possible)  

remove usr/local/bin directory if it exists, attempt to run:

curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-darwin-arm64" && sudo install -c -m 0755 devpod /usr/local/bin

run /usr/local/bin and get devpod output 😄 

**Local Environment:**  
- DevPod Version: [use `devpod version`]
- Operating System: mac
- ARCH of the OS: ARM64

**Anything else we need to know?**  

I got this from your homepage, I edited the command to remove the rm as I wasn't familar with the install flags and I didn't want to take the risk. 😅

**Comment by pascalbreuninger** [comment]
Hi @leematos, thanks for opening the issue. It's a funny interaction with the `install` command indeed, here's the relevant excerpt of the man page:
> The file(s) are copied to the target file or directory.  If the destination is a directory, then the file is copied into directory with its original filename.

 Installing binaries into /usr/local/bin is a relatively common operation in my opinion and something developers installing CLIs are familiar with. 
 I'll close this issue for now, if enough people encounter the same problem we can reopen it :)
