### ISSUE TITLE
Start Openvscode with token

### ISSUE THREAD

**Issue by Iyappanj** [loft-sh/devpod#1148]
**Is your feature request related to a problem?**  
Yes

**Which solution do you suggest?**  
is it possible to start the openvscode server with "token" ? now I see it starts with "--without-connection-token" option.

**Which alternative solutions exist?**  
Starting it with a Token

**Additional context**  
We are bringing up devpod on a common env where developers can use that to spin containers for their need. Now the concern is that we dont want to give the possibility for the developers to view other env from another developer. So we want to restrict it with some token for authentication.

**Comment by Iyappanj** [comment]
@pascalbreuninger any support from you ?

**Comment by pascalbreuninger** [comment]
@Iyappanj It's not the highest priority on the roadmap because it can be cirumvented by issueing one VM/pod per developer. 
In case you really need it fast, you could think about contributing it yourself :)
