### ISSUE TITLE
[feature] `devpod self update`

### ISSUE THREAD

**Issue by baggiponte** [loft-sh/devpod#1161]
I installed devpod with `brew` but I am unsure whether the cask is official. I'd love to just keep around the CLI but I am unsure about what to do when a new version comes out. I see that an interface like `<tool> self update` is quite common, at least in the Python ecosystem, and I'd say devpod might benefit from such a feature 😊 Another common pattern is to have a `<tool> upgrade` but it's sometimes confusing: some tools implement both an `update` and `upgrade` command and it's unclear what's doing what.

**Comment by pascalbreuninger** [comment]
Hi @baggiponte, thanks for opening the issue. We went with `devpod upgrade` in the end to keep it consistent with our other CLIs. Hope that's still alright with you ;)
#1163 

Will be available with the next release
