### ISSUE TITLE
Permission denied when building devcontainer

### ISSUE THREAD

**Issue by jzazo** [loft-sh/devpod#1169]
**What happened?**  
I configured an ssh provider with custom port. Then I try to create a workspace:
```
devpod up https://github.com/microsoft/cookie-doh
```
which has a permissions error:
```
14:33:54 info Workspace cookie-doh already exists
14:33:54 info Creating devcontainer...
14:34:01 info devcontainer up: parsing devcontainer.json: open /home/javierzazo/.devpod/agent/contexts/default/workspaces/cookie-doh/content/.devcontainer/devcontainer.json: permission denied
14:34:01 error Try using the --debug flag to see a more verbose output
14:34:01 fatal run agent command: Process exited with status 1
```

**Local Environment:**  
- DevPod Version: v0.5.16
- Operating System: **windows**
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Localprovider: ssh

**Comment by jzazo** [comment]
I managed to build cookie-doh-2, although it did not build the repo's devcontainer, and then it timed out trying to connect with vscode (but I think that's another issue).

**Comment by pascalbreuninger** [comment]
Based on the logs it seems like something is off with git. Can you confirm you can successfully clone the repo locally?

**Comment by jzazo** [comment]
I can clone it locally with no problem. I am not using the builtin ssh provider with devpod. Could that be an issue?

The repo is public, so cloning should be possible...

**Comment by pascalbreuninger** [comment]
Yep fair enough, I've also been able to open the repository and build the workspace with the GCP and azure providers. 
Stupid question, but is `git` installed and in your PATH on your machine?

**Comment by jzazo** [comment]
Yes, `git` is installed both in the remote machine and locally in Windows...

**Comment by pascalbreuninger** [comment]
Could you share more information about the SSH Server machine please? I wasn't able to reproduce the issue with a stock-standard debian VM with git and docker installed 🤔

**Comment by jzazo** [comment]
Yeah... it's a complicated setup. I connect to a remote machine via tunnel, so I start that tunnel to port 22. I then run a ssh port forwarding session from port 22 to 2222, and I then I try to connect with devpod to that port 2222.
This is my port forwarding command: `ssh -N -L 2222:127.0.0.1:22 -o StrictHostKeyChecking=no EUROPE.javierzazo@127.0.0.1`.

Surprisingly, I tried again with `--id cookie-doh-4` and it cloned the repo correctly this time, and was capable of building the devcontainer.

Do you know how can I properly clean the cache for all the previous build attempts and permission issues I am getting?

**Comment by jzazo** [comment]
It successfully built the devcontainer. It then failed because it timed out, as in this open [issue](https://github.com/loft-sh/devpod/issues/972).

I will close this issue now and continue monitoring the other one.

Let me know if there is an easy way to clean the cache to solve the permission issues.

**Comment by jzazo** [comment]
Thanks! What did the trick was remove the `$HOME/.devpod` in the remote node.

Note that `devpod up *** --reset` or `recreate` do not work because a permissions error is raised as well.
