### ISSUE TITLE
Cannot create devpod container from another container

### ISSUE THREAD

**Issue by Iyappanj** [loft-sh/devpod#1172]
**What happened?**  
I am trying to run devpod up .... command from a container which has access to my Kubernetes cluster and end up with the below error.

07:37:30 info devcontainer up: build image: get image build info: create authentication keychain: authenticate: serviceaccounts "default" is forbidden: User "system:serviceaccount:default:default" cannot get resource "serviceaccounts" in API group "" in the namespace "default"

but from the container I can access all resources of the Kubernetes cluster. Only with the Devpod I have this issue. Any hint ?

**What did you expect to happen instead?**  
Devpod should be able to create container and resources

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Run devpod up from a container to create devcontainer on a Kubernetes cluster

**Local Environment:**  
- DevPod Version: v0.5.15
- Operating System: Linux
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Kubernetes Provider: Server Version: v1.26.13+8f85140

**Anything else we need to know?**  
I tried devpod up against a on premise Kubernetes cluster as well as Openshift cluster and the result is same.

@pascalbreuninger Any support ?

**Comment by pascalbreuninger** [comment]
Hi @Iyappanj, when DevPod detects it's running on a kubernetes pod it uses the pods `serviceAccountToken` to authenticate itself agains the image registry. 

In your case it seems like the service account attached to your pod in the default namespace isn't allowed to list other serviceaccounts in the current namespace. 

You'll need to give it the [relevant permissions](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#service-account-permissions)

**Comment by Iyappanj** [comment]
@pascalbreuninger That Worked.!! Thank you.!
