### ISSUE TITLE
Support for Zed

### ISSUE THREAD

**Issue by brandondrew** [loft-sh/devpod#1185]
It would be very helpful if DevPod supported the Zed editor.

It's growing in popularity and now available for all 3 major platforms.

**Comment by pascalbreuninger** [comment]
Hi @brandondrew, thanks for opening the issue. 
Zed definitely looks like a welcome addition to the IDE ecosystem and I'm personally excited to see their development. It'd be fantastic if we could add them as an IDE to DevPod. We're currently lacking a way of programatically opening a remote environment though, I've created a [ticket](https://github.com/zed-industries/zed/issues/15070) over at Zeds repo for this purpose.

You can still use Zed with DevPod manually if you want to:
1. Create your workspace with DevPod
2. In Zed (Preview), start the `projects: open remote` action 
3. Click on `New Server`
4. Select `Connect via SSH (default)` and enter either `ssh $WORKSPACE_ID.devpod` or `devpod ssh $WORKSPACE_ID` as the host
5. Zed should install itself into the container and connect your local instance to it

**Comment by brandondrew** [comment]
@pascalbreuninger Thanks!

**Comment by simlal** [comment]
Hey man, I've been trying first with the example from the vscode repo for a quick check. I get this 
![image](https://github.com/user-attachments/assets/45818ce2-f9e7-4a0c-91e3-868a75d81345)

Even though I can ssh into it:
```bash
vscode-remote-try-python on  main via  v3.11.2 on   (ca-central-1)
❯ ssh vscode-remote-try-python.devpod
vscode ➜ /workspaces/vscode-remote-try-python (main) $ cd .local/
vscode ➜ /workspaces/vscode-remote-try-python/.local (main) $ ls -a
.  ..
vscode ➜ /workspaces/vscode-remote-try-python/.local (main) $ which gzip
/usr/bin/gzip

# Checking zed bin and glibc version
vscode ➜ ~/.local/bin $ ls
flask
vscode ➜ ~/.local/bin $ ldd --version
ldd (Debian GLIBC 2.36-9+deb12u8) 2.36
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

I am running 
❯ zed --version
Zed  preview 0.157.2

Feels like its not sending the headless zed binary through ssh or maybe I just don't get it. Anyways, I know this is like preview/alpha stuff but since I am trying to get into devcontainers and really don't want to ever go back to vscode, if you have any idea of what I am doing wrong.

**Comment by simlal** [comment]
DevPod worked though, meaning I can still edit the file in zed:
![image](https://github.com/user-attachments/assets/355b9c65-9ce5-42ca-bf4c-6767f8b754c7)

And changes are reflected inside the container
``` bash
vscode ➜ /workspaces/vscode-remote-try-python (main) $ python -m flask run --port 9000
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:9000
Press CTRL+C to quit
127.0.0.1 - - [10/Oct/2024 19:23:03] "GET / HTTP/1.1" 200 -
```
```
vscode ➜ /workspaces/vscode-remote-try-python (main) $ curl -X GET http://127.0.0.1:9000
<html>
    <head>
        <title>ZED</title>
    </head>
    <body>
        <h1>Changed?</h1>
        <p>Y</p>
    </body>
```

**Comment by pascalbreuninger** [comment]
We've just release [v0.6.0](https://github.com/loft-sh/devpod/releases/tag/v0.6.0) which includes support for Zed :)

**Comment by brandondrew** [comment]
@pascalbreuninger thank you so much!
