### ISSUE TITLE
.DS_Store appears as a workspace in `devpod up`

### ISSUE THREAD

**Issue by alipatti** [loft-sh/devpod#1189]
The hidden `.DS_Store` file appears as an option for workspaces when running devpod up on Mac. Somewhat related to #852 and #854.

**Reproducing:**
- Navigate to `~/.devpod/contexts/default/workspaces` in Finder and change something in the window (e.g., toggling a folder drop down, changing the sort order, etc.). This will create the .DS_Store file.
- Run `devpod up`. `.DS_Store` will be shown as a possible workspace (but it obviously won't launch if selected).

![Screenshot 2024-07-26 at 10 15 31 AM](https://github.com/user-attachments/assets/f6d5ea5d-6d16-4cf2-80c8-5ccdce7b888e)

**Local Environment:**  
- DevPod Version: 0.5.16
- Operating System: mac
- ARCH of the OS: x86

**DevPod Provider:**  local Docker

**Comment by bkneis** [comment]
Thanks for reporting this @alipatti! I think what would be best for this is to not show any hidden directories, there hidden after all :) I can't see many use cases where this is needed
