### ISSUE TITLE
Trying to open Fleet 1.38.89

### ISSUE THREAD

**Issue by midoriiro** [loft-sh/devpod#1196]
**What happened?**  
Cannot open fleet anymore, it was fine few minutes ago. Nothing had been updated on my side.

Log line: `[15:07:03] info Starting Fleet at https://fleet.jetbrains.com/?version=1.38.89&workspaceId=*** ...`

Versions available in toolbox:
![image](https://github.com/user-attachments/assets/eba48660-4d81-4bc9-bba4-d189e1c54b7b)

**What did you expect to happen instead?**  
Start last version installed

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Not really sure, depend how devpod resolve fleet version

**Local Environment:**  
- DevPod Version: 0.5.18
- Operating System: windows
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Localprovider: docker

**Comment by pascalbreuninger** [comment]
Hey @midoriiro, thanks for opening the issue. I'm unable to reproduce this on windows. Is it still failing and if so, could you provide additional information about your setup that might be relevant?

**Comment by midoriiro** [comment]
What kind of information do you have you in mind ?

The issue is resolved, later Jetbrains Toolbox proposed me to update Fleet. 

But Devpod should not rely on last IDE available version, as user I should be able to set which version I want to run. For example, if last version of Fleet has several issue and cannot be run on my PC I'll rollback to a prior one but I'll not be able to use Devpod. Is that correct ?

So there is two issues, the one described in OP and this one. What do you think about this @pascalbreuninger ?
