### ISSUE TITLE
SSH Provider Setup Fails Due to Agent Download Error (Could Not Resolve Host)

### ISSUE THREAD

**Issue by JochenMan** [loft-sh/devpod#1210]
**What happened?**

I tried setting up the SSH provider in DevPod, but encountered an issue during workspace creation using an example repo (e.g., Python). The log shows that DevPod is trying to download an agent from a URL that results in a `404` error. The error message indicates that it can't resolve the host `github.com`, leading to a failure in downloading the required agent from [this url](https://github.com/loft-sh/devpod/releases/download/v0.5.19).

This issue occurred when configuring the SSH provider via the DevPod CLI on Linux, as well as through the GUI on both Linux and Windows.

**What did you expect to happen instead?**

I expected the SSH provider to successfully set up the workspace by downloading the necessary agent from the correct URL.

**How can we reproduce the bug?**

1. Use either an Ubuntu 20.04 machine (Kernel 5.15.0-117) or a Windows 11 machine.
2. Set up the SSH provider in DevPod, ensuring passwordless login works via `ssh-copy-id`.
3. Create a workspace using an example repo (e.g., Python).
4. Observe the error during the agent download.

**Local Environment:**

- DevPod Version: 0.5.19
- OS: Ubuntu 20.04 (Kernel 5.15.0-117) / Windows 11
- ARCH: AMD64

**DevPod Provider:**

- Remote Machine: Ubuntu 22.04
- Provider: SSH

**Anything else we need to know?**

Only "user@FQDN" was set in the DevPod GUI. Passwordless login works fine.

**Comment by bkneis** [comment]
Hi @JochenMan could you re run the devpod up command with `--debug` and send the logs? I just tried to reproduce your error on Ubuntu 22 and everything worked fine. Also just want to check, is your remote SSH host DNS working fine? i.e. `nslookup github.com` returns a valid IP

**Comment by JochenMan** [comment]
Hi [@bkneis](#),

Thanks for your help. The problem was indeed related to the proxy configuration within my company's network and could be resolved by setting the corresponding variables in /etc/environment on the server-side.

What I don’t understand, though: I noticed that when I try to access the URL directly, I receive a 404 error, regardless of whether I'm on the company network or my home network.

Could you help me understand why this might be happening? How is the agent being downloaded if the corresponding URL returns a 404?

Best regards,  
Jochen

**Comment by bkneis** [comment]
No worries, glad to hear the problem is fixed 🙂 I think the logs that mentioned this URL are referring to it as a base URL. Then depending on your platform arch it downloads the correct binary. For example `[https://github.com/loft-sh/devpod/releases/download/v0.5.19/devpod-darwin-amd64](https://github.com/loft-sh/devpod/releases/download/v0.5.19/devpod-darwin-amd64)` works fine which downloads the am64 binary
