### ISSUE TITLE
Specify devcontainer definition location when not included in project

### ISSUE THREAD

**Issue by simonhauck** [loft-sh/devpod#1225]
**Is your feature request related to a problem?**  
When contributing to open source projects, they do not always have a devcontainer definition.
But it would still be great to use dev pod for these repositories as well.

**Which solution do you suggest?**  
When creating a new workspace, it could be possible to specify an optional property to overwrite the dev container location if needed. There is already a dev container path input., but it works only with relative paths. It would be great if it could either be an repository or a local file.

**Which alternative solutions exist?**  

Alternatively, it could be possible to check out the project after creating the workspace. But I am not sure how the "open in IDE" function would behave in this case.

**Additional context**

**Comment by pascalbreuninger** [comment]
Hey @simonhauck, thanks for opening this issue. 

Wouldn't it be feasible for open source repositories to fork them and create your own devcontainer.json, potentially contributing it back upstream?

I generally understand your need and we are actively working on something related, but geared towards platform teams, enabling them to roll out devcontainers in their organization incrementally. This will be available in [DevPod Pro](https://devpod.sh/pro/) in case you're curious

**Comment by simonhauck** [comment]
In some cases this might be an option, but not all open source projects might want to provide a devcontainer definition.
The main idea is that if a project does not provide a devcontainer you can still leverage the benefits of an isolated environment. 

Devpod is already using the ubuntu base image in that scenario. but if we could specify another (might even be local) devcontainer definition, this could be solved. 

I can understand if you say that this is out of scope - in that case feel free to close the issue :)
