### ISSUE TITLE
DevPod GUI AppImage segfaults when using amdgpu-dkms AMD drivers 

### ISSUE THREAD

**Issue by KhazAkar** [loft-sh/devpod#1261]
**What happened?**  
When using AMDGPU-DKMS driver from AMD (not built-in kernel one), DevPod GUI segfaults.

**What did you expect to happen instead?**  
Launch normally

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. Install amdgpu-dkms driver
2. Download DevPod Appimage to have GUI
3. Make it executable
4. Launch from CLI
5. Observe bug.

**Local Environment:**  
- DevPod Version: v0.5.20
- Operating System: linux
- ARCH of the OS: AMD64 

**Anything else we need to know?**  
```
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
Cannot find target for triple amdgcn-- Unable to find target for this triple (no targets are registered)
Segmentation fault (core dumped)
```

```
[29302.826644] dev-pod[97689]: segfault at 60 ip 00007126054bc0f6 sp 00007ffd2857a560 error 4 in libLLVM.so.18.1[712602400000+58c0000] likely on CPU 11 (core 6, socket 0)
[29302.826659] Code: 44 24 28 48 89 44 24 20 49 8b 04 24 48 89 44 24 08 49 8b 44 24 08 48 89 44 24 10 31 c0 48 85 db 74 08 48 89 df e8 2a 39 60 fd <4c> 8b 55 60 49 8b 4c 24 64 49 8b 54 24 6c 4d 85 d2 48 89 4c 24 30
```

**Comment by KhazAkar** [comment]
Nothing needs to be fixed. I've fixed it on my PC by installing amdgpu drivers to the fullest from AMD, instead of half-installed broken state. I'm surprised it survived that long.

**Comment by pascalbreuninger** [comment]
Thanks for the update!
