### ISSUE TITLE
I can't create a workspace with Docker

### ISSUE THREAD

**Issue by salaboy** [loft-sh/devpod#1263]
**What happened?**  

I tried to create a workspace but the button wasn't enabled. 
<img width="1396" alt="Screenshot 2024-09-16 at 10 00 54" src="https://github.com/user-attachments/assets/05b4503e-d41f-4724-9b4b-8dfb8b68e5ee">

**What did you expect to happen instead?**  

I wanted to create a workspace. 

**Local Environment:**  
- DevPod Version:  v0.5.20
- Operating System:  Mac 
- ARCH of the OS: ARM64 

**DevPod Provider:**  
- Local/remote provider: docker

**Anything else we need to know?**

**Comment by janekbaraniewski** [comment]
Hey @salaboy thanks for reporting this! 
I must say, this is a strange one. `Create Workspace` button should become enabled ones you input anything into workspace repo url bar or select any of quickstart examples. 
I can't reproduce this issue. Also running 0.5.20 on Mac with ARM cpu. 
What if you input repo url manually? Is it still the case then? Or is it only when you select quickstart example?

**Comment by salaboy** [comment]
yeah.. super strange.. after trying different things and going back to create from beginning it finally showed me the button enabled. So I am sure that I was hitting and edge case

**Comment by janekbaraniewski** [comment]
Glad to hear that it finally worked for you! 
Please reach out if you encounter any other issues!
