### ISSUE TITLE
Panic while trying to add the AWS provider

### ISSUE THREAD

**Issue by guthyerrz** [loft-sh/devpod#1267]
While using the Dev Pod Mac app version 0.5.20/aarch64 for the first time, I tried to add the AWS provider and I got this stack trace. The error happens every time I click on the AWS provider.

```
panic: runtime error: invalid memory address or nil pointer dereference goroutine 1 [running]:
runtime/debug.Stack()
/Users/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.5.darwin-arm64/src/runtime/debug/stack.go:24 +0x64
github.com/loft-sh/devpod/cmd.Execute.func1()
/Users/runner/work/devpod/devpod/cmd/root.go:80 +0x38
panic({0x10343ede0?, 0x1051f8570?})
/Users/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.5.darwin-arm64/src/runtime/panic.go:770 +0x124
github.com/loft-sh/devpod/cmd/provider.(*ListCmd).Run(0x140003206e0, {0x0?, 0x0?})
/Users/runner/work/devpod/devpod/cmd/provider/list.go:102 +0x2c0
github.com/loft-sh/devpod/cmd/provider.NewListCmd.func1(0x1400082f300?, {0x140005f2680?, 0x4?, 0x102c6c7df?})
/Users/runner/work/devpod/devpod/cmd/provider/list.go:37 +0x30
github.com/spf13/cobra.(*Command).execute(0x14000833208, {0x140005f2640, 0x2, 0x2})
/Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x140001f9b08)
/Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
/Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:1039
github.com/loft-sh/devpod/cmd.Execute()
/Users/runner/work/devpod/devpod/cmd/root.go:90 +0x48
main.main()
/Users/runner/work/devpod/devpod/main.go:6 +0x1c
```
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/f2105ffb-64a2-4fea-b3f6-61ce9e4e3168">

**Comment by janekbaraniewski** [comment]
Hey @guthyerrz! thanks for reporting this! 

I tried to recreate your issue but didn't manage to, tried on fresh install of DevPod 0.5.20 on Mac with arm chip: 

<img width="1312" alt="Screenshot 2024-09-18 at 15 21 32" src="https://github.com/user-attachments/assets/bd89b5da-3688-4db4-9eb5-d464ec89d526">

Can you provide some more details on how you installed DevPod? Where did you place application on your local machine? What are permissions set on it? Anything that could help in reproducing this issue is welcomed.

**Comment by guthyerrz** [comment]
<img width="1199" alt="image" src="https://github.com/user-attachments/assets/3750cac6-b32a-45c0-be13-885595c20c98">


Weird, it looks like it's working now so it might have been due to a network issue.
