### ISSUE TITLE
Wrong (default ?) user (UID / GID)

### ISSUE THREAD

**Issue by darkterra** [loft-sh/devpod#1295]
**What happened?**  
After cloning a repository and creating a .devcontainer folder itself containing a devcontainer.json file, a Dockerfile and a docker-compose.yml file, the devpod graphical client cannot launch VS Code _(this is not the command line case)_.
Knowing that on my workstation, the account with the UID and GID **1000** are associated with the "suportit" account which is an account installed by the team which manages the PC fleet. My ace account for UID and GID **1001**.

My guess is that devpod retrieves the correct "ssh client" when we see the debug line `/run/user/1001/keyring/ssh`, yet at the level of the **"Chown projects..."** info log it retrieves id **1000**. Which has the side effect of preventing me from modifying the code from my ide launched by the host, because the files belong to **1000** and more than **1001**.

![DevPod_Issue_#1289_0](https://github.com/user-attachments/assets/bda08bf1-5cc7-447a-a184-8cb97bdbf98e)

![DevPod_Issue_#1289_1](https://github.com/user-attachments/assets/d4689d7a-7c75-4786-90bd-be3ccd282ecc)

![DevPod_Issue_#1289_2](https://github.com/user-attachments/assets/a7ffbf96-9cc2-49a6-b0ac-63e952737161)

![DevPod_Issue_#1289_3](https://github.com/user-attachments/assets/9b2e4627-c9f7-4f24-8f2c-e659ff3c0a81)

![DevPod_Issue_#1289_4](https://github.com/user-attachments/assets/544a5de3-40cf-4965-b15c-035feb3bc8f8)

---

**What did you expect to happen instead?**  
Being able to use the graphical version of devops which opens the IDE without errors

**How can we reproduce the bug?** (as minimally and precisely as possible)
1. Create a docker provider with default values
2. Clone a repo _(with the 3 files inside of the .devcontainer folder, see image above)_
3. Create a workspace from a local folder _(clone on previous step)_

My *`devcontainer.json`*:
```
{
    "name": "new-sms-server",
    "dockerComposeFile": "docker-compose.yml",
    "service": "app",
    "workspaceMount": "source=${localWorkspaceFolder}, target=/workspace, type=bind",
    "workspaceFolder": "/workdpace"
}
```

**Local Environment:**  
- DevPod Version: [use `v0.5.22`]
- Operating System: `Linux` _(Ubuntu 24.04)_
- ARCH of the OS: `AMD64`

**DevPod Provider:**  
- Local/remote provider: docker | ssh

**Anything else we need to know?**

**Comment by bkneis** [comment]
@darkterra thanks for reporting your issue! Did you perform a `ls -la` on the directory to ensure it was owned by UID 1000 and not root? Looking at the code we chown the directory so the remote user on the devcontainer can modify the files. This should be set in the devcontainer.json or as a label on the pod `devpod.user`. Is this label set on your pod? You can use `docker inspect` to see this. Also can you try use the `remoteUser` attribute in [devcontainer.json](https://containers.dev/implementors/json_reference/) and set this to your user with UID 1001?

**Comment by eguiraud-pf** [comment]
Hi, is there any workaround for this? I also have an account with id 1001 and building the dev container changes ownership of all files to UID 1000, which does not correspond to any user.

This is a complete blocker to using devpod :/ vscode works fine.

**Comment by karypid** [comment]
I have the same issue.  My workspace uses uid 1000 and gid 1000 for a user/group unrelated to me (let's call these otheruser/othergroup).

The UID/GID for my own user account (let's say myuser:mygroup) are therefore not 1000.#

When I use devpod to create the container  in Linux, the workspace ownership is changed to 1000/1000 so it is suddenly owned by otheruser/othergroup instead of myuser/mygroup.

This problem is on Linux with Docker provider.

Simple container spec to test it (default "Basic Python" from VSCode):

```
{
  "name": "Basic Python",
  "build": { "dockerfile": "Dockerfile" },
  "remoteUser": "vscode",
  "customizations": {
    "vscode": {
      "extensions": ["ms-python.python"]
    }
  }
}
```

and:

```
FROM library/python:3.11-bookworm

ARG USER=vscode
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update \
    && apt install -y --no-install-recommends sudo \
    && apt autoremove -y \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -m -s /usr/bin/bash ${USER} \
    && echo "${USER} ALL=(ALL) NOPASSWD: ALL" >/etc/sudoers.d/${USER} \
    && chmod 0440 /etc/sudoers.d/${USER}
```

The above works fine when I create the container from within VSCode itself, but DevPod will mess up the permissions.

**Comment by bkneis** [comment]
@karypid thanks for reporting your issue and providing the example! I am running debian 12 and using your example devcontainer and Dockerfile, when I launch the devcontainer using vscode, the workspace is owned by root, not the remoteUser. Can you provide the output of `ls -la` in your workspace inside the container?

**Comment by bkneis** [comment]
@darkterra are you using a local directory to up the workspace? If so, then this is the intended behaviour. Since your remote user has UID 1000, in order for the workspace to be usuable devpod needs to chown the directory in the container for your user to have permissions. When using git this is not an issue, since there are no local files. But when using a local directory, the issue cannot be avoided since you are using the directory as a user in another user namespace

**Comment by eguiraud-pf** [comment]
at least in my case yes, this is with a local directory.

> the issue cannot be avoided

but vscode somehow avoids it :sweat_smile:

**Comment by bkneis** [comment]
@eguiraud-pf what platform are you on? I am on debian 12 and when I use vscode alone to open a devcontainer, all my files are owned by root when using @karypid config. Although this does not cause issues with my local file permissions, this is now not ideal for my development within the container. Docker also will do this if you try run the Dockerfile using --user.

![Screenshot from 2024-10-25 09-40-44](https://github.com/user-attachments/assets/24e801c2-ccc5-49fc-9424-3a1690eeaa22)
