### ISSUE TITLE
Setting to configure ssh configuration file to write connections

### ISSUE THREAD

**Issue by vfricou** [loft-sh/devpod#1312]
First of all, I apologize if this feature was already discussed, I haven’t found any of this in issues.

**Is your feature request related to a problem?**  

DevPod defaultly write configuration in `~/.ssh/config` without hability to specify other files (or I haven’t found option).

Typically, I split my configuration file in multiples files for complex environment and use `Include` directive to manage all theses configurations.

Other example, my vscode don’t write his configuration in `~/.ssh/config`, but in `~/.ssh/vscode-ssh-config` was included by my `~/.ssh/config` file for more readability.
This cause issue when I use VSCode with DevPod because is unable to retrieve correct `<workspace-name>.devpod` which not writen in his configuration file.

**Which solution do you suggest?**  

Hability to specify SSH configuration file where to write DevPod configurations directly in, and adding an `Include` directive only in `~/.ssh/config`.

For example, if we specify to DevPod to write ssh configuration in `~/.ssh/devpod-config` containing following example :

```
# DevPod Start alpine-latest.devpod
Host alpine-latest.devpod
  ForwardAgent yes
  LogLevel error
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  HostKeyAlgorithms rsa-sha2-256,rsa-sha2-512,ssh-rsa
  ProxyCommand "/Applications/DevPod.app/Contents/MacOS/devpod-cli" ssh --stdio --context default --user root alpine-latest
  User root
# DevPod End alpine-latest.devpod
```

And into `~/.ssh/config`, adding on top following directive : 

```
Include ~/.ssh/devpod-config
```

**Which alternative solutions exist?**  

N/A

**Additional context**  

N/A

**Comment by bkneis** [comment]
Hi @vfricou thanks for reporting this use case and giving an explanation! DevPod does already support this with the `up` command's argument `--ssh-config`. You can do exactly as you say, add `Include ~/.ssh/devpod-config` to your `~/.ssh/config` then when up'ing a workspace, you can run `devpod up --ssh-config ~/.ssh/devpod-config ...`
