### ISSUE TITLE
AWS Provider not working post Upgrade to 0.5.21

### ISSUE THREAD

**Issue by famagusta** [loft-sh/devpod#1315]
**What happened?**  
Getting the below screen on trying to add AWS provider
<img width="1200" alt="Screenshot 2024-10-15 at 11 26 51 AM" src="https://github.com/user-attachments/assets/b5f43131-20ff-4234-8c66-ae1fc4097ee6">

**What did you expect to happen instead?**  
Everything to work exactly the same

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Upgrade from 0.5.18 to 0.5.21 on a mac OS 15.0.1
Existing AWS provider will disappear and attempt to add a new AWS provider failed.

**Local Environment:**  
- DevPod Version: 0.5.21
- Operating System:  mac OS 15.0.1
- ARCH of the OS:  ARM64

**DevPod Provider:**  
- Cloud Provider: aws

**Anything else we need to know?**

**Comment by pascalbreuninger** [comment]
Hey @famagusta, do you still experience this issue with the latest version?

**Comment by famagusta** [comment]
I tried 0.5.22
Issue seems to be resolved in that version. Thanks for the update.

**Comment by pascalbreuninger** [comment]
Great, I'll close this issue then
