### ISSUE TITLE
"InvalidQuery: version"

### ISSUE THREAD

**Issue by ideaship** [loft-sh/devpod#1318]
**What happened?**  

When I start DevPod_linux_amd64.AppImage on Fedora 40, I get a message window titled "Failed to open workspace from URL" with the message `InvalidQuery: version`. The same error box appears every time I change to "Settings" or within "Settings" to the "General" tab.

Whenever the error box appears, the app logs
`[/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-plugin-deep-link-0.1.2/src/linux.rs:104:29] buffer = "version"`.

**What did you expect to happen instead?**  

No error.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

This bug may be related to https://github.com/loft-sh/devpod/issues/1195, but at least the conditions for triggering it appear to be different.

I tried to remove all local files that could affect the devpod behavior. But I don't remember seeing that error on the very first start of the application. Now it happens every single time. So there may be some lingering state somewhere.

`./DevPod_linux_amd64.AppImage version` does not give a version but the error described above:

```shell
$ ./DevPod_linux_amd64.AppImage --help
Gtk-Message: 12:21:51.473: Failed to load module "xapp-gtk3-module"

** (dev-pod:2042204): WARNING **: 12:21:51.842: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
Gtk-Message: 12:21:51.888: Failed to load module "xapp-gtk3-module"
[/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-plugin-deep-link-0.1.2/src/linux.rs:104:29] buffer = "version"
```

The running application reports on the dashboard "Version 0.5.21 | linux | x86_64".

**Comment by pascalbreuninger** [comment]
@ideaship thanks for reporting the error. We're currently upgrading the tauri dependencies including the deep link plugin. I'm somewhat hoping for this issue to be solved after the upgrade. 

In addition we're going to print a warning in the application logs instead of showing a modal if we can't parse a custom protocol URL since it seems to cause more issues than it's worth.
