### ISSUE TITLE
Setting alternative url for openvscode install

### ISSUE THREAD

**Issue by jamesfricker** [loft-sh/devpod#1328]
**Is your feature request related to a problem?**  

I am trying to use devpod on a remote host. This host has no internet access aside from our internal artifactory. 

When running 'devpod-cli up .', I get an error when the program tries to download the openvscode binary from GitHub.com. 

**Which solution do you suggest?**  

I suggest that an alternative option be made available, either by config or environment variable. This would allow me to use devpod to install openvscode from my internal artifactory. 

**Which alternative solutions exist?**  

None the I am aware of. 

**Additional context**  

Might be possible to also extend this idea to the other ide choices.

**Comment by bkneis** [comment]
@jamesfricker thanks for reporting your issue! This is supported via an ide option, you can

```
devpod ide set-options openvscode -o DOWNLOAD_AMD64={your artifactory}
```

or 

```
devpod ide set-options openvscode -o DOWNLOAD_ARM64={your artifactory}
```

depending on your arch. I hope that helps!

**Comment by jamesfricker** [comment]
oh this is awesome, didn't realise this was an option. Thanks heaps!
