### ISSUE TITLE
Appimage won't start fully: Ubuntu 22.04

### ISSUE THREAD

**Issue by life5ign** [loft-sh/devpod#1350]
**What happened?**  
Stalled here:
![image](https://github.com/user-attachments/assets/903b6677-f9fe-4c40-93b3-69b1a983bcab)

with these logs

```
❯ ~/appimage/DevPod_linux_amd64.AppImage

** (dev-pod:53504): WARNING **: 15:27:00.611: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.

(process:54013): GLib-CRITICAL **: 15:27:00.983: Failed to set scheduler settings: Operation not permitted

(WebKitWebProcess:54070): GLib-CRITICAL **: 15:27:01.525: Failed to set scheduler settings: Operation not permitted
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1200x800: Permission denied
```

**What did you expect to happen instead?**  
To run devpod without using sudo (which I haven't tried).

I tried adding my user to the `video` group, with no success

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Download appimage, make executable, start
My *`devcontainer.json`*:
didn't get there
```
{
    "name": "...",
    ...
}
```

**Local Environment:**  
- DevPod Version: [use `devpod version`]
- v0.5.21%                                                                                                                                                                     

- Operating System: windows | linux | mac
- linux
- 
- ARCH of the OS: AMD64 | ARM64 | i386 
- AMD64

**DevPod Provider:**  
Didn't get there
- Cloud Provider: google | aws | azure | digitalOcean
- Kubernetes Provider: [use `kubectl version`]
- Local/remote provider: docker | ssh
- Custom provider: provide imported `provider.yaml` config file

**Anything else we need to know?**  
```
❯ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Comment by life5ign** [comment]
Same result from the tarball:

```
❯ ./dev-pod 

** (dev-pod:130976): WARNING **: 17:07:13.711: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1200x800: Permission denied

```

**Comment by bkneis** [comment]
Thanks for reporting your issue @life5ign, can you try setting the env var `WEBKIT_DISABLE_DMABUF_RENDERER=1`, according to https://github.com/tauri-apps/tauri/issues/8462 this might be a known workaround

**Comment by life5ign** [comment]
> Thanks for reporting your issue @life5ign, can you try setting the env var `WEBKIT_DISABLE_DMABUF_RENDERER=1`, according to [tauri-apps/tauri#8462](https://github.com/tauri-apps/tauri/issues/8462) this might be a known workaround

Thank you, this worked. Much appreciated

**Comment by life5ign** [comment]
Since this issue has cropped up twice, might it make sense to put it in the documentation/troubleshooting?
