### ISSUE TITLE
problem with vsode and github repo

### ISSUE THREAD

**Issue by Sebiche09** [loft-sh/devpod#1358]
**What happened?**  
When i try to create a workspace with my github repo : https://github.com/Sebiche09/gestion-syndic and i select vscode,
when vscode start and try ssh remote, i have a error like this : 

/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/var/home/seb/.local/bin:/var/home/seb/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
:/usr/sbin
[10:10:16.805] Checking ssh with "ssh -V"
[10:10:16.812] Finding installed ssh failed: spawn ENAMETOOLONG
[10:10:16.813] Exec server for ssh-remote+gestion-syndic.devpod failed: Error: spawn ENAMETOOLONG
[10:10:16.813] Error opening exec server for ssh-remote+gestion-syndic.devpod: Error: spawn ENAMETOOLONG

**What did you expect to happen instead?**  
create a remote ssh connection with my workspace and vscode

**How can we reproduce the bug?** (as minimally and precisely as possible)  
you can try to clone the repo and test

My *`devcontainer.json`*:
```
{
    "name": "...",
    ...
}
```

**Local Environment:**  
- DevPod Version: 0.5.21
- Operating System: linux project bluefin
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: docker

**Anything else we need to know?**

**Comment by bkneis** [comment]
Hi @Sebiche09 thanks for reporting your issue! Can you please add `--debug` and paste the entire of the logs so I can debug?

**Comment by bkneis** [comment]
Hi @Sebiche09 thanks for reporting your issue! I tried to reproduce your issue using `devpod up https://github.com/Sebiche09/gestion-syndic` but this works for me. Can you append `--debug` to your `up` command and reply with your logs?

**Comment by bkneis** [comment]
@Sebiche09 can you try the workaround from https://github.com/loft-sh/devpod/issues/1045 and see if that fixes your issue? Seems that specifying the SSH path for vscode resolves the issue
