### ISSUE TITLE
OpenVSCode (port 10800) is not being forwarded

### ISSUE THREAD

**Issue by 4310V343k** [loft-sh/devpod#1387]
I want to launch a devpod on a remote server, then connect to it from my work computer. The remote server is ubuntu 20.04 with no graphical environment.

**What happened?**  

Looks like `devpod` started the forwarding, then closed it after encountering an error
```
11:06:29 debug Forward port localhost:10800:localhost:10800
11:06:29 debug Execute SSH server command: bash -c '/usr/local/bin/devpod' agent container credentials-server --user 'vscode' --configure-git-helper --configure-docker-helper --forward-ports --debug
...
11:06:29 debug New connection on localhost:10800 (Total: 1)
11:06:29 debug Accepted forward: localhost:10800
11:06:30 debug error copying to remote: writeto tcp 127.0.0.1:10800->127.0.0.1:51924: read tcp 127.0.0.1:10800->127.0.0.1:51924: read: connection reset by peer
11:06:30 debug Closed connection on localhost:10800 (Total: 0)
11:06:30 done Successfully opened http://localhost:10800/?folder=/workspaces/vscode-remote-try-python
```

I can't connect with `server-ip:10800` from my work computer and I can't `curl 127.0.0.1:10800` from the server itself

**What did you expect to happen instead?**  

The port forwarding stays working, so I can connect to the openvscode from outside the container

**How can we reproduce the bug?** (as minimally and precisely as possible)  

`devpod up https://github.com/microsoft/vscode-remote-try-python --ide openvscode --debug`

**Local Environment:**  
- DevPod Version: v0.5.22
- Operating System: linux
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: docker

**Anything else we need to know?**  

If I run `ssh -L 0.0.0.0:10800:127.0.0.1:10800 vscode-remote-try-python.devpod` on the server after starting the devpod, I'll be able to connect to openvscode from the remote server (curl) and from my work computer

**Comment by 4310V343k** [comment]
Turns out I was wrong and the above log has nothing to do with the actual forwarding. After fumbling around with creation of some more devcontainers it started forwarding like normal and I can't reproduce the bug anymore (I can connect from wherever)

**Comment by pascalbreuninger** [comment]
@4310V343k Thanks for the update 🙏 Let us know if you encounter the issue again please
