### ISSUE TITLE
`provider` value not passed correctly by `GlobalFlags`

### ISSUE THREAD

**Issue by abdulari** [loft-sh/devpod#1391]
**What happened?**  
- provider value not passed correctly by `GlobalFlags` for `provider set-options`
- provider value is passed correctly by `GlobalFlags` for `provider options`

**What did you expect to happen instead?**  
both `provider options` and `provider set-options` able to get provider value correctly from `GlobalFlags`

**How can we reproduce the bug?** (as minimally and precisely as possible)  

add `log.Debugf("GlobalFlags=%+v", cmd.GlobalFlags)` in *`set_options.go`* Run function 

```
vscode ➜ /workspaces/devpod (main) $ devpod provider set-options docker --provider docker2 --debug
09:55:23 debug GlobalFlags={Context: Provider: LogOutput:plain Debug:false Silent:false AgentDir: DevPodHome: UID:}
09:55:23 done Successfully set options for provider 'docker'
vscode ➜ /workspaces/devpod (main) $ 
```

```
vscode ➜ /workspaces/devpod (main) $ devpod provider options docker --provider docker2 --debug
09:56:52 debug GlobalFlags=&{Context: Provider:docker2 LogOutput:plain Debug:true Silent:false AgentDir: DevPodHome: UID:}
  
-- truncate --
```

**Local Environment:**  
- DevPod Version: `commit 37e66ce34ab125f8fb4952d6041a2ca159ca2603`
- Operating System:  `linux` and `windows`
- ARCH of the OS: `AMD64` 

**DevPod Provider:**  
- Local/remote provider: docker 

**Anything else we need to know?**

**Comment by bkneis** [comment]
Hi @abdulari thanks for reporting your issue! I believe you need to use the `--provider` flag like this

`devpod --provider docker2 provider set-options docker --debug`

Note the flag is added after `devpod` and not the sub command `provider`
