### ISSUE TITLE
DevPod not finding Zed

### ISSUE THREAD

**Issue by mathroc** [loft-sh/devpod#1444]
**What happened?**  

Trying to start a workspace works, but opening it in Zed doesn't

**What did you expect to happen instead?**  

Opening the workspace in Zed

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```
{"image":"mcr.microsoft.com/devcontainers/php:8.3"}
```

**Local Environment:**  
- DevPod Version: v0.6.3
- Operating System: linux
- ARCH of the OS: AMD64 

**DevPod Provider:**  
- Local provider: docker

**Anything else we need to know?**  

```
$ devpod up git@... --ide zed --debug
19:11:17 info Workspace ... already exists
19:11:17 info Creating devcontainer...
19:11:18 info Setup container...
19:11:18 info Run 'ssh ....devpod' to ssh into the devcontainer
19:11:18 info Opening Zed editor...
19:11:21 debug Starting Zed caused error: exit status 3
19:11:21 error Seems like you don't have Zed installed on your computer locally
```

(kept only the debug lines after "info Opening Zed editor...")

```
$ which zed
/home/mathieu/bin/zed
$ zed --version
Zed 0.163.3 – /home/mathieu/bin/dist/zed/zed.app/libexec/zed-editor
```

works if I try to open it with vscode

**Comment by pascalbreuninger** [comment]
Hey @mathroc, thanks for opening this issue. 
What happens when you run `xdg-open zed://ssh/$WORKSPACE_ID.devpod/`?

**Comment by mathroc** [comment]
It says

> /usr/bin/xdg-open: line 1091: x-www-browser: command not found
/usr/bin/xdg-open: line 1091: firefox: command not found
/usr/bin/xdg-open: line 1091: iceweasel: command not found
/usr/bin/xdg-open: line 1091: seamonkey: command not found
/usr/bin/xdg-open: line 1091: mozilla: command not found
/usr/bin/xdg-open: line 1091: epiphany: command not found
/usr/bin/xdg-open: line 1091: konqueror: command not found
/usr/bin/xdg-open: line 1091: chromium: command not found
/usr/bin/xdg-open: line 1091: chromium-browser: command not found
/usr/bin/xdg-open: line 1091: google-chrome: command not found
/usr/bin/xdg-open: line 1091: www-browser: command not found
/usr/bin/xdg-open: line 1091: links2: command not found
/usr/bin/xdg-open: line 1091: elinks: command not found
/usr/bin/xdg-open: line 1091: links: command not found
Alert!: Unsupported URL scheme!
lynx: Start file could not be found or is not text/html or text/plain
      Exiting...
/usr/bin/xdg-open: line 1091: w3m: command not found
xdg-open: no method available for opening 'zed://'

I'm going to look at why, this issue is very likely on my side. 

But I think this output should be printed in debug mode or at least be visible somehwere

**Comment by mathroc** [comment]
got it working by copying the zed.desktop file to ~/.local/share/applications/

Do you want me to create another ticket to remember to improve the logs in case xdg-open?

**Comment by pascalbreuninger** [comment]
Would be great to create a follow up issue so that it's in the public GitHub Issues instead of our internal issue tracking

**Comment by mathroc** [comment]
done, thank you a lot !

https://github.com/loft-sh/devpod/issues/1448

**Comment by elijahcuellar** [comment]
For anyone facing the same issue, when I installed zed, the handler for zed:// was not set properly. This command fixed that problem: `xdg-settings set default-url-scheme-handler zed dev.zed.Zed.desktop`.

If a different release channel was installed, then `zed` in the command above should be replaced with the correct url scheme (see https://github.com/zed-industries/zed/issues/6918#issuecomment-1913548723).
