### ISSUE TITLE
Pod Auto Timeout error state

### ISSUE THREAD

**Issue by buggtb** [loft-sh/devpod#1457]
**What happened?**  

I use the Kubernetes provider on AKS. When I set the timeout it does seem to time out but the pod ends in an error state.
Nothing in the logs, no pod event, but the devpod container is in an error state, and when I tested it it required a rebuild to come back to life

**What did you expect to happen instead?**  
Shutdown cleanly.

**Local Environment:**  
- DevPod Version: 0.6.4
- Operating System: mac
- ARCH of the OS: ARM64 

**DevPod Provider:**  
- Cloud Provider: azure
- Kubernetes Provider: Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.30.5
- Local/remote provider: kubernetes

**Comment by buggtb** [comment]
Hey @bkneis 

Yeah it does happen everytime. I should have said, its also with the IntelliJ gateway setup, which might be causing the wrinkle. 

I tried to dig into it a bit but failed to find anything of use in the pod. I'll try sticking on the debug setting and see if that makes a difference. 

Try flipping to intellij though and see if it does it, because it is 100% of the time.

**Comment by bkneis** [comment]
Hmm, I just tried again with intilliJ and no luck. If the issue is with the timeout though this will only take effect once the IDE is closed. I am also using AKS so not sure what the config difference is. Do you have any k8s configuration in your cluster than could impact the pod? Any finalizers etc?

**Comment by buggtb** [comment]
I dunno.... today I did the same as the other day and it exits cleanly. I give up! :)

I'll return if I can figure out how to reproduce it thanks for checking @bkneis
