### ISSUE TITLE
UID mapping logic breaks devpod on  MacOS Docker Desktop

### ISSUE THREAD

**Issue by gjhenrique** [loft-sh/devpod#1462]
**What happened?**  

In https://github.com/loft-sh/devpod/issues/1284 and https://github.com/loft-sh/devpod/pull/1287, you fixed the bug with UIDs not maching in the host and container. Good one :trophy:!

But this broke MacOS when using devpod in the recent versions. This is because the containers we're building expect the uid to be 1000, including some files from the prebuilt image. The mapping from user 501 breaks this expectation 

In #1287, @pascalbreuninger suggested to limit to Linux, which was a good idea, but the PR excluded windows. The check should be `runtime.GOOS == "linux"` instead of runtime.GOOS =! "windows"`

**What did you expect to happen instead?**  

MacOS Docker Desktop doesn't have any uid mapping, so the logic of rewriting the uid of the container is not necessary

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Use a container that sets a different `USER`, and doesn't rewrite the original UID   

**Local Environment:**  
- DevPod Version: versions at least 0.5.22
- Operating System: mac
- ARCH of the OS: user reported had a mac amd64, but I could reproduce with an ARM mac 
- 
**DevPod Provider:**  
- Local/remote provider: docker 

**Anything else we need to know?**  
Opened https://github.com/loft-sh/devpod/pull/1463 to fix that

**Comment by pascalbreuninger** [comment]
@gjhenrique Thanks a lot! I forgot to make sure we include this only on linux as per the devcontainer spec
