### ISSUE TITLE
Building Dockerfile with comment on base image build arg fails

### ISSUE THREAD

**Issue by agrinh** [loft-sh/devpod#1480]
**What happened?**  
Trying to build a Dockerfile with a base image that is specified with an argument which has a comment fails with `error Error building image: build image: get image build info: find base image dev`.

**What did you expect to happen instead?**  

This should just work.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Run `devpod build ... --skip-push --debug` with a `Dockerfile` like this:

```Dockerfile
# syntax=docker/dockerfile:1
ARG BASE_IMAGE="ubuntu:latest"  # comment

FROM ${BASE_IMAGE} AS dev
```

Using the following Dockerfile instead works fine:

```Dockerfile
# syntax=docker/dockerfile:1
ARG BASE_IMAGE="ubuntu:latest"

FROM ${BASE_IMAGE} AS dev
```

**Local Environment:**  
- DevPod Version: v0.6.5
- Operating System: mac
- ARCH of the OS: ARM64 

**DevPod Provider:**  
- Cloud Provider: N/A
- Kubernetes Provider: N/A
- Local/remote provider: docker

**Anything else we need to know?**

**Comment by bkneis** [comment]
Hey @agrinh thanks for reporting your issue! After looking into this I believe inline comments are actually not supported by docker https://docs.docker.com/reference/dockerfile/#format. Also see the conversation conclusion at https://github.com/moby/moby/issues/9533

In summary all comments need to be on a new line :)

**Comment by agrinh** [comment]
Thanks @bkneis appreciate the response, looks like you're right. I'm surprised buildkit never complained, perhaps it just gets ignored when searching for the image. It would've saved me some time with a slightly more detailed error message, but I'll close this now.
