### ISSUE TITLE
Build downgrades existing docker syntax specification

### ISSUE THREAD

**Issue by agrinh** [loft-sh/devpod#1481]
**What happened?**  
Trying to build a `Dockerfile` with an existing syntax specification fails if a recent syntax version is used since the syntax is replaced in the generated `Dockerfile-with-features` with `docker.io/docker/dockerfile:1.4`.

**What did you expect to happen instead?**  
devpod should never force an older syntax version, but could potentially bump the version to a minimum one if required.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Run `devpod build ... --skip-push --debug` with a `Dockerfile` like this:

```Dockerfile
# syntax=docker/dockerfile:1

FROM ubuntu:latest AS dev
ADD --checksum=sha256:b8713c36d3e6f6b2520830180cf6b5779e48410ad5d5e1b192635b0c7359fcc6 \
    https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb \
    /tmp/packages-microsoft-prod.deb
```

This will fail with `info ERROR: failed to solve: dockerfile parse error on line 2: unknown flag: checksum`. The logs reveal the reason, namely that the syntax is overridden with 1.4: `info #2 resolve image config for docker.io/docker/dockerfile:1.4`

This also happens if using a complete version e.g.  `# syntax=docker/dockerfile:1.12`.

**Local Environment:**  
- DevPod Version: v0.6.5
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Cloud Provider: N/A
- Kubernetes Provider: N/A
- Local/remote provider: docker
- Custom provider: N/A

**Anything else we need to know?**

**Comment by bkneis** [comment]
Hey @agrinh thanks for reporting your issue! I've reproduced this locally and working on and testing a fix now
