### ISSUE TITLE
Kubernetes proxy-url Not Being Used

### ISSUE THREAD

**Issue by damaestro** [loft-sh/devpod#1506]
**What happened?**  

When a Kubernetes context is configured with `proxy-url` you are unable to add a Kubernetes provider. When going to add a provider:

1. Click Kubernetes
2. See the "Loading Kubernetes ...."
3. Infinite spinner

`kubectl` commands work but the client for Devpod is not using this setting correctly.

**What did you expect to happen instead?**  

The Kubernetes provider is able to be configured.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

1. Setup a Kubernetes configuration. (In this case it was an `aws eks update-config` based configuration with the external credential provider command updated to give the full path to the `aws` command.)
2. Modify the configuration to use a proxy:
```
kubectl config set clusters.$context_name.proxy-url socks5://localhost:$port
```
3. Create the tunnel:
```
ssh -D $port user@bastion
```
4. See that `kubectl` is working as expected.
5. See that you can no longer add a Kubernetes provider in Devpod.

**Local Environment:**  
- DevPod Version: v0.6.6
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Cloud Provider: aws
- Kubernetes Provider: client 1.22, server 1.29+

**Anything else we need to know?**

**Comment by damaestro** [comment]
The infinite spinner is https://github.com/loft-sh/devpod/issues/1507

**Comment by damaestro** [comment]
It appears that the `proxy-url` setting does work.

**Comment by pascalbreuninger** [comment]
Thanks for the update. The other issue should be resolved with the latest DevPod versoins
