### ISSUE TITLE
Allow specifying DOCKER_HOST for docker provider

### ISSUE THREAD

**Issue by tylerauerbeck** [loft-sh/devpod#277]
**Is your feature request related to a problem?**
Docker is configured on my local machine to use a remote host running docker (i.e. `DOCKER_HOST=ssh://user@my-docker-host`). However when trying to use the Docker provider I see a message saying

```
Seems like docker is not reachable on your system.
Please make sure docker is installed and running.
You can verify if docker is running correctly via 'docker ps'
init: exit status 1
```

**Which solution do you suggest?**
Allow for specifying DOCKER_HOST in the `Advanced Options` section or have the provider check to see if that is configured at the system level instead of (my assumption) looking for a running docker process.

**Which alternative solutions exist?**

I'm sure I could get *something* similar to what I want running using the `ssh` provider? I just haven't made it that far yet 😄

**Additional context**

I have a handful of remote systems running docker that I use for dev machines and it would be great to be able to continue to use them in this manner with devpod.

**Comment by FabianKramm** [comment]
@tylerauerbeck thanks for creating this issue! Sounds like a good idea, we'll start working on it

**Comment by Azulinho** [comment]
How do you use this?

```
devpod provider add -o DOCKER_HOST=ssh://user@192.168.0.2 --name docker  docker

devpod up https://github.com/microsoft/vscode-remote-try-python.git
15:35:19 info Creating devcontainer...
15:35:22 info docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/azul/.devpod/agent/contexts/default/workspaces/vscode-remote-try-python/content.
15:35:22 info See 'docker run --help'.

```

it attempts to do a docker mount from my workspace to the remote docker daemon

**Comment by samhodgkinson** [comment]
@Azulinho - Did you get this working ? I'm hitting the same mounting problem and I couldn't see the solution.

**Comment by mattalxndr** [comment]
This issue is really old, closed and shouldn't be, with lots of people waiting, no one listening. Red flag.
