### ISSUE TITLE
Workspace cleanup does not happen after a failed clone

### ISSUE THREAD

**Issue by rio** [loft-sh/devpod#285]
**What happened?**

I tried running `devpod up $REPO` and it failed because of an auth issue. I tried running it again and because the workspace already existed but was empty devpod defaulted to just adding a basic devcontainer.json.

**What did you expect to happen instead?**

The clone should be attempted again.

**How can we reproduce the bug?** (as minimally and precisely as possible)

```
# clone and let it fail
❯ devpod up github.com/i/do-not-exist.git
09:35:42 info Creating devcontainer...
09:35:42 info Cloning into '/home/user/.devpod/agent/contexts/default/workspaces/do-not-exist/content'...
09:35:42 info fatal: could not read Username for 'https://github.com': terminal prompts disabled
09:35:42 fatal agent error: error cloning repository: exit status 128
: exit status 1

# retry and it passes
❯ devpod up github.com/i/do-not-exist.git
09:35:45 info Workspace do-not-exist already exists
09:35:45 info Creating devcontainer...
09:35:45 info Couldn't find a devcontainer.json
09:35:45 info Try detecting project programming language...
09:35:45 info Detected project language 'None'
09:35:45 info 41e79b26886cbb359faad34efa14fffc95bfa15b704eff782c3f369bcc75ae80
09:35:45 info Setup container...
09:35:45 info Chown workspace...
09:35:45 info Run 'ssh do-not-exist.devpod' to ssh into the devcontainer
09:35:45 info Starting VSCode...
```

**Local Environment:**

* DevPod Version: v0.1.2
* Operating System: Fedora Linux 38
* ARCH of the OS: AMD64

**Comment by FabianKramm** [comment]
@rio thanks for reporting this issue! Yes seems like we need to remove the folder after it fails, good catch!
