### ISSUE TITLE
devpod for hashicorp nomad

### ISSUE THREAD

**Issue by thatsk** [loft-sh/devpod#289]
it would be nice if we can provide support for provider nomad

let me know if I can help in integrating into it.

**Comment by alexandradragodan** [comment]
Hei, @thatsk! 👋 

That's a great idea! thanks for sharing. 
Unfortunatelly, I don't think it's gonna come in our roadmap soon enough, so if you want to help, you can already go ahead and start implementing the provider and we'd be happy to support you if you have further questions. 

Here's a guide we've put together on how to create DevPod providers: https://devpod.sh/docs/developing-providers/quickstart, hope it's helpful

**Comment by briancain** [comment]
Hey there @thatsk and @alexandradragodan: I just started using DevPod and love it! I found this issue, and figured it could be a fun hack-day project to get started on. I've got most of it implemented and working now, but there's a few bugs I need to sort out before it actually works (see the issues tab): https://github.com/briancain/devpod-provider-nomad
