### ISSUE TITLE
Allow selection of alternate devcontainer.json from UI

### ISSUE THREAD

**Issue by dmckernanacv** [loft-sh/devpod#294]
**Is your feature request related to a problem?**
Currently the only way to pick which devcontainer to use is via the CLI. This would allow the UI to detect all devcontainer configurations in a workspace and allow the user to choose which one to build.

**Which solution do you suggest?**
When devcontainer.json detection happens, look for all possible `devcontainer.json` files and if there is more than one, ask the user which one they would like to apply to the workspace (and possibly optionally set it as default for the future)

**Which alternative solutions exist?**
Currently this can be done manually via the CLI with the `--devcontainer-path` flag, however there is no way to supply this in the UI.

**Additional context**

**Comment by pascalbreuninger** [comment]
@dmckernanacv With the next release of devpod there will be 
1. A `devcontainer path` input field in the `create workspace` screen
2. An experimental `multi devcontainer` setting you can enable in settings. This will check workspaces for multiple devcontainer.json files **before** creating them. To do this, we need to traverse the source code which could take a couple of seconds depending on the repository size. Give it a shot and let us know what we can do better :)
