### ISSUE TITLE
forwardPorts not support "host:port" syntax

### ISSUE THREAD

**Issue by mrdev023** [loft-sh/devpod#305]
**What happened?**

When i try to use "\[service_name\]:\[port\]" with docker-compose config. I get `json: invalid number literal, trying to unmarshal "\"db:5432\"" into Number`

See [https://containers.dev/implementors/json_reference/#general-properties](https://containers.dev/implementors/json_reference/#general-properties)

**How can we reproduce the bug?** (as minimally and precisely as possible)

My `devcontainer.json`:

```
{
    ...
    "forwardPorts": [
        3000,
        "db:5432"
    ],
    ...
}
```

**Local Environment:**

* DevPod Version: v0.1.4
* Operating System: linux
* ARCH of the OS: AMD64

**DevPod Provider:**

* Local/remote provider: docker

**Comment by FabianKramm** [comment]
@mrdev023 thanks a lot for the issue! Oh true, seems like we missed that that is possible as well, should be an easy fix, we will fix that!
