### ISSUE TITLE
Hangs trying to configure any provider

### ISSUE THREAD

**Issue by arrowmaster** [loft-sh/devpod#306]
**What happened?**
Trying to add any provider hangs on "Loading <provider name>..."

**What did you expect to happen instead?**
Anything

**How can we reproduce the bug?** (as minimally and precisely as possible)
AppImage on Debian Bookworm

**Local Environment:**

* DevPod Version: 0.1.5
* Operating System: linux
* ARCH of the OS: AMD64

**Anything else we need to know?**
Bottom of DevPod window also has incorrect system information. "Version 0.1.5 | unknown platform | unknown arch"

**Comment by 89luca89** [comment]
Hi @arrowmaster 
Which version of bookworm? 

I've tried in a bookworm container, adding the minimal dependency to make appimages work:

`sudo apt install  fuse libharfbuzz-bin libopengl0 libfribidi0 libthai0`

And then simply starting the appimage `./dev-pod_0.1.5_amd64.AppImage` 

I got the correct infos at the bottom, and I was able to add a remote provider (gcloud in this case):

![image](https://github.com/loft-sh/devpod/assets/598882/4997719f-e434-4dee-be01-6a6a43f5dbd0)

**Comment by arrowmaster** [comment]
Installing libharfbuzz-bin had no effect and DevPod still shows unknown platform unknown arch. I'm not able to install the fuse package as it conflicts with fuse3 that is already installed.

**Comment by arrowmaster** [comment]
I tested version 0.1.10 AppImage on Debian and this has not been fixed. It still shows unknown for platform and arch too.
