### ISSUE TITLE
AWS Provider shouldn't use static IAM keys if possible

### ISSUE THREAD

**Issue by klauern** [loft-sh/devpod#309]
**Is your feature request related to a problem?**
I would love to make use of this tool, but we explicitly don't support or allow IAM users to be created, and thus, don't allow setting access keys directly.  The alternative is a time-limited STS token, but digging those out of the `~/.aws/credentials` file is tedious and repetitive.

**Which solution do you suggest?**
Using IAM Roles is the preferred option, and is often accomplished through the use of profiles:

[https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html)

**Which alternative solutions exist?**
I'm sure there are a lot of other tools, but as this comes from the vendor, I would hope that most tools would lean on the options offered OOTB from Amazon.

**Additional context**

**Comment by shanman190** [comment]
With the latest 0.0.2 aws provider, this still errors out when attempting to get the `AccessToken` call. A workaround that seems to get another step further is to drop an `|| true` after the command in the `provider.json`.

Here's the error message that I'm seeing personally:
```
22:20:46 fatal exit status 1
run command: AccessDenied: Cannot call GetSessionToken with session credentials
```

NOTE: In my case, I'm using an AWS SSO profile specifically.

**Comment by 89luca89** [comment]
Hi @shanman190 and @klauern 
I'm currently investigating on a way to implement this :+1: 

Thanks for the feedbacks!
