### ISSUE TITLE
Add VSCode Insiders to the list of Default IDE

### ISSUE THREAD

**Issue by stonesbg** [loft-sh/devpod#310]
**Is your feature request related to a problem?**
I currently just have VSCode Insiders edition installed and not VSCode so I can only use the ssh option.  I would like the ability to just work out of VSCode Insdiers

**Which solution do you suggest?**
Add VsCode Insiders as an option for Default IDE

**Which alternative solutions exist?**
Currently just connecting over ssh works

**Additional context**
None

**Comment by majidaldo** [comment]
same. browser works but couldn't get remote ssh to work. i can ssh from a terminal.

**Comment by 89luca89** [comment]
Hi @stonesbg I like the idea! I'll work on this :+1:

**Comment by shyim** [comment]
This seems to be blocked by https://github.com/microsoft/vscode/issues/168492 as you need VSCode CLI for Insiders.

**Comment by qyurila** [comment]
Also [VSCodium](https://vscodium.com/) please?

**Comment by pascalbreuninger** [comment]
VSCode Insiders is now an experimental IDE in DevPod! Let us know if you encounter any problems. We'll kick off a new release in about 1-2 days
