### ISSUE TITLE
I have updated the JetBrains gateway to the latest version, but every time a dialog box pops up asking me to download the latest JetBrains gateway

### ISSUE THREAD

**Issue by SeasonPilot** [loft-sh/devpod#324]
**What happened?**
I have updated the JetBrains gateway to the latest version, but every time a dialog box pops up asking me to download the latest JetBrains gateway

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/d4e37653-e69e-4043-ab83-d19a9bf5bbf4/c71c76b9-e6c9-4122-86e9-f9eecfbf5df1)

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/363dfbfd-a79d-4cd5-a4dc-672f4d23290d/2c172fae-7fad-4ce9-aa9f-be686bc54c5c)

**What did you expect to happen instead?**

**How can we reproduce the bug?** (as minimally and precisely as possible)

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/59539fb7-2c49-4161-9372-28d0b4a148cd/a1111bc1-389c-48a7-8a60-a06e58d65bab)

My `devcontainer.json`:

```
{
    "name": "...",
    ...
}
```

**Local Environment:**

* DevPod Version: \[use `devpod --version`\]

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/34992b93-eef8-469c-bb10-60354019a00b/a36aa3b5-d418-4d74-93a8-818a0bc1429b)

* Operating System: mac
* ARCH of the OS: AMD64 | ARM64 | i386

**DevPod Provider:**

* Cloud Provider: google | aws | azure | digitalOcean
* Kubernetes Provider: \[use `kubectl version`\]
* Local/remote provider: docker | ssh
* Custom provider: provide imported `provider.yaml` config file

**Anything else we need to know?**

**Comment by FabianKramm** [comment]
@SeasonPilot thanks for creating this issue! I think I had the same problem, you need to uninstall JetBrains Gateway EAP and reinstall the beta version (make sure the EAP version really goes away and it says beta instead when you start it again). It can happen that both versions of JetBrains Gateway are installed at the same time (Beta and EAP) and you need to get rid of EAP or otherwise you will always encounter this issue.

**Comment by alexandradragodan** [comment]
Hey, @SeasonPilot 
Did that approach Fabian suggested work? 
Wanted to close the issue if so, please open another one if you're facing issues.
