### ISSUE TITLE
Web Client

### ISSUE THREAD

**Issue by Jak2k** [loft-sh/devpod#328]
**Is your feature request related to a problem?**
Can't use in browser. That's the point of codespaces.

**Which solution do you suggest?**
A web client.

**Which alternative solutions exist?**
Using GitHub Codespaces

**Additional context**

**Comment by FabianKramm** [comment]
@Jak2k thanks for creating this issue! We support VSCode Browser, which is super similar to what Github Codespaces is doing, have you tried that?

**Comment by Jak2k** [comment]
Maybe you could add a link to your website for opening it with the necessary configuration.

**Comment by ThomasK33** [comment]
Hey @Jak2k, here's a [quick start guide](https://devpod.sh/docs/getting-started/quickstart-vscode-browser) for starting VS Code Browser.
