### ISSUE TITLE
rancher desktop / nerdctl/containerd

### ISSUE THREAD

**Issue by codeagencybe** [loft-sh/devpod#340]
**Is your feature request related to a problem?**
Use with Rancher Desktop and containerd+nerdctl

**Which solution do you suggest?**
How to use DevPod with nerdctl instead of Docker?

**Which alternative solutions exist?**
/

**Additional context**
I'm not using Docker but alternative Rancher Desktop on MacOS which comes with containerd and nerdctl default.
I already replaced all "Docker" commands to Nerdctl (eg Docker run .... -> Nerdctl run ... or Docker compose -> Nerdctl compose ...) via my zshrc shell as custom aliases but this also doesn't work for DevPod.

Any documentation how I can do this?

**Comment by ThomasK33** [comment]
Hey @codeagencybe 👋, thanks for opening this issue.

Currently, the shell commands invoked by devpod run in non-interactive shells; thus, any aliases configured will not be set.
Also, as devpod invokes either a `bash` or `sh`, depending on availability, you'd have to configure aliases in the respective `.bashrc` or `.profile` files.

I've opened a PR to start shells as interactive so that those aliases will be used in the future.
For now, you could symlink `docker` to `nerdctl` in a directory somewhere in your `$PATH`.

**Comment by ThomasK33** [comment]
And we had to revert this PR due to issues with interactive shells and suspensions.

We will have to find another way to source aliases.

**Comment by codingbutstillalive** [comment]
Does it work with Rancher Desktop at all? I think by default it is using the normal docker deamon, doesn't it?

**Comment by codeagencybe** [comment]
I gave up on Rancher Desktop with DevPod, just impossible to get it working. 
I reverted to Docker Desktop for the time being but now having other errors happening as mentioned in #355

**Comment by codingbutstillalive** [comment]
Thank you very much.

Fabio Tielen ***@***.***> schrieb am Di. 30. Mai 2023 um
08:45:

**Comment by joebowbeer** [comment]
Fixed?

**Comment by FabianKramm** [comment]
@chawyehsu yeah since we mostly reused existing devcontainers code for devpod, this causes issues, we could remove this within devpod, but not sure if that would have other sideeffects and fix the problem completely.

**Comment by joebowbeer** [comment]
@codingbutstillalive asks:
> Does it work with Rancher Desktop at all? I think by default it is using the normal docker deamon, doesn't it?

I assume Rancher Desktop w/dockerd does work because:

https://github.com/rancher-sandbox/rancher-desktop/issues/800

**Comment by pascalbreuninger** [comment]
DevPod should be compatible with nerdctl and containerd after we merge #1011. We consider this as an experimental feature, use at your own risk 😅
