### ISSUE TITLE
Build Repository registry credentials

### ISSUE THREAD

**Issue by donovanmuller** [loft-sh/devpod#343]
**What happened?**

I'm testing the Kubernetes provider on a local Rancher Desktop (K3s) cluster.  I couldn't find anything obvious about how you specify container registry credentials for the pushes to the `Build Repository`?

Error I'm getting using a Docker registry:

```
...
[13:15:52] info #5 pushing layers
[13:15:58] info #5 pushing layers 6.4s done
[13:15:58] info #5 ERROR: failed to push xxx:devpod-4c3cab74a0cec348ae8be1f977469860: push access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
...
```

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/4e3b8ee7-4915-48a5-b41c-7c60f06d5822/e07b1407-f5ad-496b-a0a0-582220d9c866)

**What did you expect to happen instead?**

Use my Docker credentials to be able to push to my private repository.

**How can we reproduce the bug?** (as minimally and precisely as possible)

NA

**Local Environment:**

* DevPod Version: `v0.1.5`
* Operating System: mac
* ARCH of the OS: ARM64

**DevPod Provider:**

* Cloud Provider: NA
* Kubernetes Provider:

```
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6+k3s1", GitCommit:"9176e03c5788e467420376d10a1da2b6de6ff31f", GitTreeState:"clean", BuildDate:"2023-01-26T00:30:33Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/arm64"}
```

* Local/remote provider:
* Custom provider: NA

**Anything else we need to know?**

**Comment by ThomasK33** [comment]
Hey @donovanmuller 👋  Thanks for opening this issue.

The docker credentials are sourced from your Docker config file.
Have you tried performing a [`docker login`](https://docs.docker.com/engine/reference/commandline/login/) prior to running DevPod?

As we're utilizing [github.com/google/go-containerregistry](https://github.com/google/go-containerregistry) for interacting with OCI registries, these mechanics apply to DevPod:
> The DefaultKeychain will use credentials as described in your Docker config file -- usually ~/.docker/config.json, or %USERPROFILE%\.docker\config.json on Windows -- or the location described by the DOCKER_CONFIG environment variable, if set.
> If those are not found, DefaultKeychain will look for credentials configured using [Podman's expectation](https://docs.podman.io/en/latest/markdown/podman-login.1.html) that these are found in ${XDG_RUNTIME_DIR}/containers/auth.json.
- <https://github.com/google/go-containerregistry/blob/main/pkg/authn/README.md#tldr-for-consumers-of-this-package>

**Comment by donovanmuller** [comment]
Hi, yes I have valid Docker credentials via `docker login` before starting DevPod.

Thanks for the link, the part I’m missing is how my local Docker credentials are projected into the Kubernetes cluster, so that the buildkit image can leverage my credentials?
