### ISSUE TITLE
SSH remote doesn't surface errors

### ISSUE THREAD

**Issue by dgl** [loft-sh/devpod#350]
**What happened?**

Tried to use a project with SSH remote. Appeared to hang on agent init.

**What did you expect to happen instead?**

Work, or at least get an error, without having to turn on debug mode.

Turning on debug I saw: `debug zsh:87: command not found: sudo -E sh -c`

and then when I changed shell to bash:

```
Inject Error: sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
```

**How can we reproduce the bug?** (as minimally and precisely as possible)

```
ssh remote
apt install -y zsh
chsh -s /bin/zsh
# and/or
sudo visudo  # and drop any "NOPASSWD" bits
```

My `devcontainer.json`: n/a; I think this applies to anything.

**Local Environment:**

* DevPod Version: v0.1.5
* Operating System: mac
* ARCH of the OS: arm64

**DevPod Provider:**

* Cloud Provider: own hardware
* Local/remote provider: ssh to Ubuntu 22.04 machine

**Anything else we need to know?**

**Comment by 89luca89** [comment]
Hi @dgl thanks for reporting!
This might be related to #346

**Comment by dgl** [comment]
The sudo part is, yes; I'm a bit more confused by the Zsh behaviour though. But also I think errors can happen and it would make sense for them to be treated higher than debug level.
