### ISSUE TITLE
AppImage UI: kubernetes provider permission denied

### ISSUE THREAD

**Issue by timdahlmanns** [loft-sh/devpod#352]
### What happened?

When creating a workspace with the kubernetes provider, the pod spins up and VSCode is able to connect to it, but the workspace is empty.
The status in the UI says "Error" and shows the following logs (btw. how can I check the logs from devpod CLI?):

```
[12:21:59] fatal error retrieving container status: bash: Unable to set terminal process group (1382).: Inappropriate IOCTL (I/O control) for the device
bash: No job control in this shell.
bash: Cannot set the terminal's process group (1382).: Inappropriate IOCTL (I/O control) for the device.
bash: No job control in this shell.
find dev container: find pvc: cannot open path of the current working directory: Permission denied
exit status 1
```

I guess devpod tries to copy or mount the workspace into the PV of the Pod and this command fails?

### What did you expect to happen instead?

Devpod copies or mounts the workspace content into the Pod

### How can we reproduce the bug? (as minimally and precisely as possible)

I have a feeling it might be a problem with my local environment, so i don't know if it is reproducible.

```
devpod up --provider kubernetes --debug --id test --ide vscode .
```

### My `devcontainer.json`:

```
{
    "name": "Kubernetes Test",
    "image": "mcr.microsoft.com/devcontainers/java:0-17",
    "features": {
        "ghcr.io/devcontainers/features/docker-in-docker:2": {}
    },
    "workspaceMount": "source=${localWorkspaceFolder},target=/workspace,type=bind,consistency=cached",
    "workspaceFolder": "/workspace",
    "postCreateCommand": "bash /workspace/.devcontainer/create-workspace.sh"
}
```

### Local Environment:

* DevPod Version: v0.1.5
* Operating System: linux
* ARCH of the OS: AMD64

### DevPod Provider:

* Kubernetes Provider:

  ```
  Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-18T02:15:29Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+k0s", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-17T13:46:59Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
  ```

**Anything else we need to know?**

**Comment by timdahlmanns** [comment]
Works with CLI. Seems to be a permission issue with the AppImage.

**Comment by 89luca89** [comment]
@timdahlmanns thanks for reporting, I'm investigating the problem :+1: 

If this works from CLI, but not from the appimage, can you verify if it works from the rpm/deb package?
Thanks!

**Comment by 89luca89** [comment]
Ok then it seems a problem with the appimage packaging, seems strange as it shouldn't do any sandboxing :thinking: I'll investigate further, thanks!

**Comment by 89luca89** [comment]
Testing again in various combinations of distros (Fedora, Suse, Arch) I'm not able to replicate with the appimage of 0.1.9
Can you try again with these updated versions?

Thanks!

**Comment by timdahlmanns** [comment]
Still having the issue with v0.1.9

![grafik](https://github.com/loft-sh/devpod/assets/131154267/76626b03-e408-49e0-b387-d5f37a5a7eb2)

**Comment by 89luca89** [comment]
Thanks I'll investigate further :+1:

**Comment by gbonnefille** [comment]
Same here with version 0.1.11-20

**Comment by 89luca89** [comment]
Hi I cannot reproduce this on 0.3.4 
Can anyone of you reproduce?

**Comment by timdahlmanns** [comment]
Hi, I can't reproduce it anymore either :+1:
