### ISSUE TITLE
Allow Specifying Storage Class in provider.yaml

### ISSUE THREAD

**Issue by prasadkris** [loft-sh/devpod#361]
It would be beneficial to have the ability to specify the name of the storage class used for creating PVCs in the  Kubernetes `provider.yaml` file. Currently, it defaults to the default kubernetes storage class, which may not always be the most appropriate choice for development environments.

In our case, we have a default storage class based on SSDs, primarily intended for production operations. Meanwhile, we utilize a Ceph/Rook storage class for our development environments. Therefore, being able to specify the storage class within the `provider.yaml` file would provide better flexibility and optimization in managing resources, Thanks! 🙏

**Comment by pascalbreuninger** [comment]
@prasadkris just merged the feature request in pr #364 , will be available with the next release, probably tomorrow

**Comment by prasadkris** [comment]
Excellent, thank you so much @pascalbreuninger . I will try it out as soon as it's released. 🙏
