### ISSUE TITLE
hostRequirements, pod nodeselectors in kubernetes provider

### ISSUE THREAD

**Issue by anguslees** [loft-sh/devpod#362]
**Is your feature request related to a problem?**

Nope.  Loving devpod so far!

**Which solution do you suggest?**

Please add support to kubernetes provider for devcontainer "hostRequirements" (I see some support exists in a few other providers).

Related for my needs (but unrelated in implementation), kubernetes provider options to pass through pod node selectors would be super useful too.

**Which alternative solutions exist?**

**Additional context**

In our k8s cluster, we dynamically provision nodes using [karpenter](https://karpenter.sh/).  This needs some information to know how 'big' the pod needs to be, which I think means devcontainer `hostRequirements`.  Karpenter can also use [node selectors](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector) for additional hints like EC2 instance-type/spot/etc.

Also on k8s, it's important to tie the pod to the correct OS/architecture, since there may be mixed nodes in the same cluster.  I think devpod knows this information and can set these os/arch node selectors correctly automatically.

**Comment by alexandradragodan** [comment]
hey, @anguslees 

Glad to hear you find DevPod helpful. Thanks a bunch for reaching out with the suggestion!
We already have plans to rework&enhance a bit the kubernetes provider, so keeping this issue in mind as well!
