### ISSUE TITLE
HTTP proxy

### ISSUE THREAD

**Issue by gbonnefille** [loft-sh/devpod#365]
**Is your feature request related to a problem?**

Yes: I'm unable to use DevPod in corporate environment.

**Which solution do you suggest?**

Add support for HTTP proxy, via settings or (in Linux) by supporting standard variables like http_proxy, no_proxy and/or upcase versions.

**Which alternative solutions exist?**

**Additional context**

The error occured when trying to download [https://github.com/gitpod-io/openvscode-server/releases/download/openvscode-server-v1.76.2/openvscode-server-v1.76.2-linux-x64.tar.gz](https://github.com/gitpod-io/openvscode-server/releases/download/openvscode-server-v1.76.2/openvscode-server-v1.76.2-linux-x64.tar.gz)

**Comment by gbonnefille** [comment]
Hi,
I'm running Linux.
I targeted a Kubernetes provider.
I tried to start one of the devcontainer example (C++ I think).

**Comment by gdaemon** [comment]
Yes, http[s]_proxy/no_proxy support is must have for corporate environments.

Will test this feature with great pleasure

**Comment by gbonnefille** [comment]
@89luca89 I don't know if you started working on this. I created a PR based on my understanding of the bug.

I'm still unable to validate on my side.

@89luca89 feel free to review and merge if it is OK on your side.
