### ISSUE TITLE
Q: Is it possible to support Visual Studio?

### ISSUE THREAD

**Issue by samopolacek** [loft-sh/devpod#366]
**Is your feature request related to a problem?**
No

**Which solution do you suggest?**
N/A

**Which alternative solutions exist?**
N/A

**Additional context**
I would like to move a lot of my peers into our K8S. A lot of people are used to Visual Studio. Is it possible to support Visual Studio?

**Comment by ThomasK33** [comment]
Hey @samopolacek 👋 

Unfortunately, Visual Studio does not support running the entire IDE remotely over SSH.

While Microsoft added support for dev containers in Visual Studio 2022, it only supports connecting to remote targets via SSH. (comparable to connecting to WSL 2 locally; see: https://devblogs.microsoft.com/cppblog/dev-containers-for-c-in-visual-studio/)

---

So one way of using Visual Studio with DevPod would be running the up command and passing an ide=none

```bash
devpod up --ide none [URL to the project]
```

And then connect to the DevPod via SSH in Visual Studio. (see: https://learn.microsoft.com/en-us/cpp/linux/connect-to-your-remote-linux-computer?view=msvc-170)

Yet this would not configure the IDE and potential extensions/plugins and configs, and one would still rely on local installations.
