### ISSUE TITLE
Clone/Duplicate existing Provider

### ISSUE THREAD

**Issue by BretFisher** [loft-sh/devpod#367]
**Is your feature request related to a problem?**
I want to make two AWS Providers with slightly different settings, but I have to re-enter all the info manually.

**Which solution do you suggest?**
Provide a clone/copy/duplicate option in an existing Provider so I can reuse the values.

**Which alternative solutions exist?**
None that I know of. I can't easily copy text from one Provider to another (AMIs, Keys, etc.) because I can't have two Windows or two Providers open at once.

**Additional context**

**Comment by pascalbreuninger** [comment]
Merged the PR, will release with next version

You can clone providers using the CLI `devpod provider add --from-existing kubernetes --name other-k8s` or from the UI by clicking the `duplicate provider` button in the `provider` screen.

One restriction: This only works for providers that have been created with the new version, so you'd have to re-enter all of the options one last time 😿
