### ISSUE TITLE
Include Visual Studio Code Insiders

### ISSUE THREAD

**Issue by codingbutstillalive** [loft-sh/devpod#372]
Github Copilot currently only works under Visual Studio Code Insiders. Would be nice to see this an an IDE option.

**Comment by pascalbreuninger** [comment]
Hi @codingbutstillalive, we do have vscode insiders on our list. In the meantime, you can start the workspace using the `none` (ssh) option and then connect from within vscode insiders using the `Remote-SSH: Connect to Host` command. Your workspace should show up in the dropdown list. 
As I said, it's only a workaround for the time being

**Comment by codingbutstillalive** [comment]
> Hi @codingbutstillalive, we do have vscode insiders on our list. In the meantime, you can start the workspace using the `none` (ssh) option and then connect from within vscode insiders using the `Remote-SSH: Connect to Host` command. Your workspace should show up in the dropdown list. 
> 
> As I said, it's only a workaround for the time being

Very cool! Thanks!

**Comment by majidaldo** [comment]
https://github.com/loft-sh/devpod/issues/310

**Comment by pascalbreuninger** [comment]
@wixregiga it's available now, will release a new version soon
