### ISSUE TITLE
Running VSCode with a devcontainer on MacOS results in "docker version 17.12 required"

### ISSUE THREAD

**Issue by codingbutstillalive** [loft-sh/devpod#376]
**What happened?**
The above described problem.

**What did you expect to happen instead?**
Visual Studio Code should start the devcontainer without such a problem.

**How can we reproduce the bug?** (as minimally and precisely as possible)
Latest version of MacOS (Intel CPU) plus latest version of Docker Desktop.

My `devcontainer.json`:
I was testing with the following repo

**DevPod Provider:**

* Docker Desktop

**Anything else we need to know?**
A similar problem was documented here, but not sure if it is related.

[https://github.com/microsoft/vscode-remote-release/issues/8573#issuecomment-1578684633](https://github.com/microsoft/vscode-remote-release/issues/8573#issuecomment-1578684633)

**Comment by codingbutstillalive** [comment]
Yes, exactly this is what I was doing. There was a popup within VS Code asking for opening a container and I clicked on it. So I will just need to ignore it then?

**Comment by alexandradragodan** [comment]
Exactly. Either closing or ignoring the VSCode pop-up notification works. 

Will close this issue for now. 
If you encounter any other problems or have more feedback, feel free to open up another one and we'd be happy to help! 

Have a great day ahead! 🌞
