### ISSUE TITLE
Add a method to update the app from the app

### ISSUE THREAD

**Issue by contentfree** [loft-sh/devpod#377]
**Is your feature request related to a problem?**  
Keeping current

**Which solution do you suggest?**  
Adding a "Check for Updates" feature like many other apps

**Which alternative solutions exist?**  
Downloading the latest version manually

**Comment by pascalbreuninger** [comment]
Hey @contentfree, the desktop app currently supports auto-updates which will be installed in the background. We're thinking about making this more transparent. For now, be assured your app will stay up to date. You can always check the version in the bottom left corner
