### ISSUE TITLE
Kubernetes provider not working with insecure registries

### ISSUE THREAD

**Issue by lizardruss** [loft-sh/devpod#384]
**What happened?**
Currently receiving the following error when DevPod attempts to push an image to an insecure registry:

```
debug DeadlineExceeded: failed to push dockerregistry.some.hostname.com/my-project:devpod-6194100ffa818a3e0caa3175bae66de9: failed to do request: Head "https://dockerregistry.some.hostname.com/v2/my-project/blobs/sha256:f4a222a09f4768c29df49b900126c48e4f506238a7a569a6645d0756e18a2173": dial tcp 10.125.4.34:443: i/o timeout
```

The registry has been configured as insecure in `~/.docker/config.json`, and the `BUILD_REPOSITORY` is configured as `dockerregistry.some.hostname.com/my-project`.

In addition, building and pushing to the registry works as expected when using the Docker CLI

**What did you expect to happen instead?**
The image should build and push successfully and the DevPod should start.

**How can we reproduce the bug?** (as minimally and precisely as possible)
Configure a local, insecure image registry, and use the `kubernetes` provider to create a DevPod.

**Local Environment:**

* DevPod Version: latest

**DevPod Provider:**

* Kubernetes Provider

**Anything else we need to know?**
The issue is with a 3rd party library that always assumes a secure registry is used when parsing the registry reference, for example, the lines below would output `https` instead of `http`:

```
ref, _ := name.ParseReference("http://dockerregistry.some.hostname.com/my-project")
fmt.Println(ref.Context().Registry.Scheme())
```

[Slack thread where this issue was reported.](https://loft-sh.slack.com/archives/C056ZDZPJ4W/p1686579458184289)

**Comment by leunamnauj** [comment]
Any workaround for this?
Would be great to be able to use an "insecure" local registry

**Comment by pbialon** [comment]
Update: I had some problems with setup the env for testing it. I'll need some more time to investigate the issue, but hope to return to you with an answer this week!

**Comment by pascalbreuninger** [comment]
As we're now building images in kubernetes in-container there's no strong need to push to an insecure local registry anymore imo. If you have a good use case we can reopen this issue

**Comment by nicholas-presien** [comment]
Hi, 

I am using devpod on a locally hosted k3s cluster with a mixture or ARM and AMD agents. The k3s are running with docker runtime as well.

The images are all built locally on a separate server; however, I am facing issues specifying devpod to run on a specific node via nodeName or nodeSelector with hardware label, and it complains about using a docker image from an insecure registry, however on the agent itself, I've updated the docker daemon.json file to register the insecure registry, and was able to manaully run a docker pull to validate it.

Any idea how I can ensure that devpod tries to run the build on that specific node?
