### ISSUE TITLE
workspace creation failed with ssh provider

### ISSUE THREAD

**Issue by amal-chandran** [loft-sh/devpod#385]
**What happened?**

* Created a ubuntu vm in proxmox
* Using ssh provider tried to create a workspace
* Workspace creation status stayed in loading with logs `Waiting for devpod agent to come up...`
* After long sometime process exited `[01:11:02] fatal error retrieving container status: bash: line 1: /tmp/devpod/agent: No such file or directory exit status 127`
* Things are working fine for local docker provider

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/208dbec0-e709-4c9f-a82b-02be0368b206/369e5436-112f-4060-8223-56efd8268e2a)

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/7b27db24-59d5-4202-bbe3-3b95963310d9/da7da185-35af-4685-b2e3-e68de2bd0d43)

**What did you expect to happen instead?**

* The node js test repo based workspace should be created
* The vs code editor should be opened up

**How can we reproduce the bug?** (as minimally and precisely as possible)

* Spin up the linux desktop app  (kde neon)
* Create an ubuntu 22 server vm in proxmox
* Configure ssh with password & try to connect
* Use default ssh provider config
* Use node js test template for workspace creation
* Create the workspace & check logs

**Local Environment:**

* DevPod Version: 0.1.9
* Operating System: linux (KDE neon 5.27)
* ARCH of the OS: AMD64

**DevPod Provider:**

* Local/remote provider: ssh

**Comment by 89luca89** [comment]
Hi @amal-chandran 

I've just tried and I couldn't reproduce the bug, can you try removing/readding the ssh provider?

I did try both using a root account and a rootless account
It should be noted that we need passwordless ssh access for the provider to work

**Comment by janhurst** [comment]
I have a similar experience when trying to create a devpod to an azure ml compute instance (managed ubuntu 20.04 vm) over ssh when running devpod on a windows host...

for me it hangs after 
```
code --folder-uri vscode-remote://ssh-remote+psa-ds15-try-python.devpod//workspaces/psa-ds15-try-python --disable-extension ms-vscode-remote.remote-containers --new-window
```

vscode never launches...
