### ISSUE TITLE
IDE IntelliJ cannot start because of missing 'remote-dev-server.sh'

### ISSUE THREAD

**Issue by njam** [loft-sh/devpod#386]
Summary: Cannot start Intellij IDE, because the script `remote-dev-server.sh` is only included in the "Ultimate" version in new Intellij versions?

**What happened?**

I'm trying to start a basic DevPod with IntelliJ as the IDE.

The "Jetbtrain Gateway" cannot connect to the backend because it cannot run `remote-dev-server.sh`. It shows this in the error log:

```
2023-06-13 21:34:01,916	WARN	exit code: 1	/bin/bash -lc echo\ REMOTE_EXEC_OUTPUT_MARKER_\ \&\&\ /home/vscode/.cache/JetBrains/RemoteDev/remote-dev-worker/remote-dev-worker_0ec7a5894d84ecbca903e581fdf42c2238085d427a818fead0f4a71e131cc951\ host-status\ --ide-path=/home/vscode/.cache/JetBrains/RemoteDev/dist/intellij\ --project-path=/workspaces/foo
	stdout:
	REMOTE_EXEC_OUTPUT_MARKER_
	Stdout: 
	Stderr: 
	{"type":"error","errorCode":"CommandError","data":"fork/exec /home/vscode/.cache/JetBrains/RemoteDev/dist/intellij/bin/remote-dev-server.sh: no such file or directory"}

	[command is repeated 54 more times]
```

The path where the script is expected in exists (`/home/vscode/.cache/JetBrains/RemoteDev/dist/intellij/bin/`), but doesn't contain the file.

This happens with IntelliJ version 2023.1.1.

If I downgrade to IntelliJ 2022.3 it works fine:

```
devpod-cli ide set-options -o VERSION=2022.3 intellij
```

Is it possible that this script was removed in newer IntelliJ versions, and is now only available in IntelliJ Ultime builds? (see [https://youtrack.jetbrains.com/issue/GTW-4384/remote-dev-server.sh-No-such-file-or-directory](https://youtrack.jetbrains.com/issue/GTW-4384/remote-dev-server.sh-No-such-file-or-directory))
Then probably the Ultimate tarball should be downloaded instead?

**What did you expect to happen instead?**
The "Jetbtrains Gateway" should be able to connect to the DevPod

**How can we reproduce the bug?** (as minimally and precisely as possible)

My `devcontainer.json`:

```
{"image":"mcr.microsoft.com/devcontainers/rust:0.203.9-bullseye"}
```

**Local Environment:**

* DevPod Version: v0.1.9%
* Operating System: linux
* ARCH of the OS: AMD64\\

**DevPod Provider:**

* Local/remote provider: docker (but using "podman" binary)

**Anything else we need to know?**

**Comment by pascalbreuninger** [comment]
Hi @njam, are you using the IntelliJ Community edition?
According to Jetbrains, remote development is [only available for Ultimate](https://www.jetbrains.com/help/idea/faq-about-remote-development.html#community)

**Comment by njam** [comment]
@pascalbreuninger I can't reproduce the problem anymore, so it's good that you closed it.

I'm usually using the "ultimate" edition. But maybe for some reason, in some context, the "community" edition was used. Not sure exactly, where this folder is taken from.

I checked, and the file `remote-dev-server.sh` _is_ present in the tarballs that [devpod downloads](https://github.com/loft-sh/devpod/blob/143b2be72f312a5d96869eaff70238e8b0bf7c93/pkg/ide/jetbrains/intellij.go#L9), in all recent versions:
```
find . -name 'remote-dev-server.sh'
./idea-IU-2023.1.2---231.9011.34/bin/remote-dev-server.sh
./idea-IU-2022.3---223.7571.182/bin/remote-dev-server.sh
./idea-IU-2023.1.1---231.8770.65/bin/remote-dev-server.sh
```

**Comment by pascalbreuninger** [comment]
glad it worked out for you, thanks for reporting 🙇

**Comment by igomon-bloomberg** [comment]
I have this problem again when I try to open an existing project which I could open just yesterday. Here is from the err.log:

```
...
Stdout: '{"type":"error","errorCode":"CommandError","data":"Command /home/igomon/.cache/JetBrains/RemoteDev/dist/b1e8660b1c947_pycharm-2025.1.1/bin/remote-dev-server.sh failed.\nStdout: \nStderr: \n\nCaused by: fork/exec /home/igomon/.cache/JetBrains/RemoteDev/dist/b1e8660b1c947_pycharm-2025.1.1/bin/remote-dev-server.sh: no such file or directory"}'
2025-05-23 15:04:26,697 [  21671]   WARN - #c.j.g.s.GoHighLevelHostAccessor - The status command provided error result.
...
```

PyCharm version:
PyCharm 2025.1.1.1
Build #PY-251.25410.159, built on May 14, 2025
Source revision: 31f194c2a1782
Licensed to ** / **
You have a perpetual fallback license for this version.
Subscription is active until December 31, 2026.
Runtime version: 21.0.6+9-b895.109 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.4.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true


ALl of a sudden I can no longer open any of my projects. Not sure what happened.
