### ISSUE TITLE
Ports support for kubernetes driver

### ISSUE THREAD

**Issue by snapiz** [loft-sh/devpod#390]
**Is your feature request related to a problem?**
I'm trying to make workspaces communicate using traefik but can't find a way to expose pod port

**Which solution do you suggest?**
allow to configure pod ports maybe through `portsAttributes` of devcontainers.json ?

**Which alternative solutions exist?**
not able to find a solution

**Additional context**

**Comment by pascalbreuninger** [comment]
Hi @snapiz, thank you for submitting a feature request, we'll look into it 👍
