### ISSUE TITLE
Using a custom SSH config for VS Code causes issues

### ISSUE THREAD

**Issue by proever** [loft-sh/devpod#397]
**What happened/how to reproduce?**

* use a custom config file for VS Code (`"remote.SSH.configFile"`)
* add a new workspace and try to launch it with VS Code
* the "default" config file is modified (`~/.ssh/config`) rather than the custom one specified

**Local Environment:**

* DevPod Version: v0.1.9
* Operating System: macOS Sonoma dev beta 1
* ARCH of the OS: Apple Silicon

**DevPod Provider:**

* Cloud Provider: digitalOcean

Solution (?): read config file from VS Code JSON settings and write to that one?
`/Users/<USER>/Library/Application Support/Code/User/settings.json`

**Comment by FabianKramm** [comment]
I'm closing this for now, feel free to reopen if still a problem
