### ISSUE TITLE
image timeout

### ISSUE THREAD

**Issue by ilovejs** [loft-sh/devpod#398]
**What happened?**

ran rust with vscode, rust with vscode web all failed.

\[10:47:26\] info Get "[https://github.com/gitpod-io/openvscode-server/releases/download/openvscode-server-v1.78.2/openvscode-server-v1.78.2-linux-x64.tar.gz](https://github.com/gitpod-io/openvscode-server/releases/download/openvscode-server-v1.78.2/openvscode-server-v1.78.2-linux-x64.tar.gz)": dial tcp: lookup [github.com](http://github.com) on 192.168.1.1:53: read udp 172.17.0.2:52108->192.168.1.1:53: i/o timeout

**What did you expect to happen instead?**
no timeout or faster / slimer docker image

**How can we reproduce the bug?** (as minimally and precisely as possible)

normal devcontainer.json, idk where to find due to workspace itself has error to spin up.

My `devcontainer.json`:

```
{
    "name": "...",
    ...
}
```

**Local Environment:**

* DevPod Version: i use AppImage, version is latest by this time.
* Operating System: linux
* ARCH of the OS: AMD64

**DevPod Provider:**

* Local/remote provider: docker

**Anything else we need to know?**

**Comment by 89luca89** [comment]
Hi @ilovejs 

What is failing is the download of the web IDE (openvscode), that one is needed to function in the first place via web
It isn't the rust image

**Comment by ilovejs** [comment]
probably, it huge.
