### ISSUE TITLE
SoftLink for devpod-cli created by the Appimage version of devpod will invalid after a restart of devpod

### ISSUE THREAD

**Issue by ihipop** [loft-sh/devpod#400]
**What happened?**
when I click "Add CLI to PATH" in the settings of devpod, it creates a softlink to a temporary mount point of Appimage instead of a permanent link to Appimage of devpod
after a restart  or quit of devpod  , this path will be invalid, and devpod-cli  will be unavailable

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/912d9e70-4001-445f-ab39-9cf756813de1/8bd7b1e5-7422-40e9-9ff4-be8b41456c2e)

**What did you expect to happen instead?**
a soft link of devpod-cli  should be created to the path of the  Appimage of devpod
**and the Appimage should judge if we want to start devpod-cli or devpod,which is a lacked feature of v0.1.9  for now at least**

\~**How can we reproduce the bug?** (as minimally and precisely as possible)\~

**Local Environment:**

* DevPod Version: ` v0.1.9`
* Operating System: linux
* ARCH of the OS: AMD64

\~**DevPod Provider:**\~

\~**Anything else we need to know?**\~

**Comment by 89luca89** [comment]
Hi @ihipop Will take a look at this thanks for reporting! :+1:

**Comment by ihipop** [comment]
@FabianKramm @89luca89 
if I wasn't wrong，this patch only copy a cli binary to path when I click install button？
if I updated the version of app image ，I won't got the cli binary to be updated until I click the install button again？

why just symlink to the app image itself ，and，judge the basename in the entrypoint to known if we want to lauch the UI or cli
