### ISSUE TITLE
Create workspace button grayed out with Python example

### ISSUE THREAD

**Issue by vermaat** [loft-sh/devpod#406]
**What happened?**

I tried creating a sample Python project, but the "Create workspace" button stayed grayed out after adding all the required input. Only after clicking the JS example button, and subsequently the Python button again the workspace button turned purple.

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/8d49240b-e3bd-41bd-aa91-640daadf7850/f3cb2c57-a1c6-4bac-acdc-2ba342df049a)

**What did you expect to happen instead?**

A working Create workspace button After clicking Python example project once

**How can we reproduce the bug?** (as minimally and precisely as possible)

My `devcontainer.json`:

```
{
    "name": "...",
    ...
}
```

**Local Environment:**

* DevPod Version: Version 0.1.9 (20230605.081937)
* Operating System: mac
* ARCH of the OS: ARM64

**DevPod Provider:**

* Local/remote provider: docker
* Custom provider: provide imported `provider.yaml` config file

**Anything else we need to know?**

**Comment by pascalbreuninger** [comment]
HI @vermaat, thanks for reporting the isse. I assume you typed the name after clicking on the python quickstart? That's how I can repro the bug at least, will fix

**Comment by vermaat** [comment]
Correct! I typed the name after clicking the Python quickstart button. From: Pascal Breuninger ***@***.***>Date: Wednesday, 21 June 2023 at 10:21To: loft-sh/devpod ***@***.***>Cc: Vermaat ***@***.***>, Mention ***@***.***>Subject: Re: [loft-sh/devpod] Create workspace button grayed out with Python example (Issue #406)HI @vermaat, thanks for reporting the isse. I assume you typed the name after clicking on the python quickstart? That's how I can repro the bug at least, will fix—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by pascalbreuninger** [comment]
Seems like validation for this input is broken, you should have gotten a message stating "only lowercase characters and numbers are allowed" for the name.. that's the reason the `create workspace` button is disabled (working on a fix)
