### ISSUE TITLE
Research containers (or: custom web-based editors)

### ISSUE THREAD

**Issue by fliepeltje** [loft-sh/devpod#408]
**Is your feature request related to a problem?**
A significant use of devcontainers is to provide 0-installation data analysis environments for researchers around a specific topic.

**Which solution do you suggest?**
It would be great to have documentation on how to run arbitrary web-based setups (specifically Jupyter notebooks or R studio)

**Which alternative solutions exist?**
Through github, you can setup a jupyter notebook environment. [Example](https://github.com/github/codespaces-jupyter)
When specified in your personal settings, you can open up a browser tab with jupyter notebook from the example repo.

**Additional context**
Some use cases:

* A biology research group wants to have a standardised set of data pipelines for certain experiments. To that end, they develop a package that processes standardised inputs to standardised plots/statistics. To create reproducible and publishable pipelines, they create a devcontainer that has this software and all its dependencies builtin so that other people do not have to install a bunch of stuff just to get the pipeline running
* A humanities research group is working with large datasets that are stored in a secure data repository. They use advanced tools to interpret the data. To facilitate researchers, they create devcontianers with a pre-configured integration to the data repository so that researchers do not have to set this up locally or learn how to ssh into remote servers

Currently we are using github codespaces, but we also have a k8s cluster and it seems like this might be a wonderful fit to remove our dependency to github for research containers.

**Comment by pascalbreuninger** [comment]
Hi @fliepeltje , sounds like an interesting addition, we'll look into it 👍

**Comment by fliepeltje** [comment]
> add jupyter notebooks and r studio as separate IDEs next to VSCode and Jetbrains IDEs. Wyt?

For my use cases it would be perfect :)

**Comment by limx0** [comment]
Chiming in for a +1 on Jupyter notebooks - this would be an awesome addition.
