### ISSUE TITLE
app in DevPod_macos_x64.dmg quits after starting with no error message

### ISSUE THREAD

**Issue by Darkness-Bright** [loft-sh/devpod#412]
Monterey 12.6.3

app in `DevPod_macos_x64.dmg` quits after starting with no error message.
cannot start app :(

**Comment by Darkness-Bright** [comment]
oh sorry
i forgot to mention that my mac is x64.

**Comment by yCrab** [comment]
@Darkness-Bright is there something useful in the log file by chance? It’s usually in `~/Library/Logs/sh.loft.devpod`

**Comment by Darkness-Bright** [comment]
okay. i regret the fact that i didn't include the devpod version number in my first comment.
for the latest release, it works. yay!
so this means that this issue can be closed.
