### ISSUE TITLE
kubernetes: Local dependencies

### ISSUE THREAD

**Issue by max06** [loft-sh/devpod#427]
**Is your feature request related to a problem?**

I wanted to use devpod to deploy existing devcontainers (using Dockerfiles) into a k8s cluster. It turned out there are some dependencies to satisfy:

* A local docker daemon needs to be up and running to build the image

A container registry needs to be available to push the image so it can be used in k8s (authentication)

**Which solution do you suggest?**

By deploying your own container registry into the k8s cluster into the namespace you already create, you have full control on the credentials used and can spare some complexity.

By using a docker-in-docker-container for the initial build, you can eliminate the need for the local docker daemon for the build process. It would be similar to what microsoft did (or still does) in their implementation, when you clone a repository in a docker volume. They start a bootstrap container with all required tools to get the devcontainer built and running.

**Which alternative solutions exist?**

Extending the documentation would be a starting point. It was quite a ride until I started to see what's going wrong.

**Additional context**

**Comment by FabianKramm** [comment]
@max06 thanks for creating this issue! Sorry for letting this hang so long, for k8s builds we actually already start a buildkit container so a local docker daemon shouldn't be required, although you are correct that a container registry is currently expected. The local registry approach would work (we use that approach for DevSpace), however it needs a nodeport service to work as the containerd is not able to pull the image within the cluster otherwise, which is usually not allowed in a rather locked down cluster. We can add an option for this, but I wouldn't change the default behaviour.

**Comment by pbialon** [comment]
Hi @max06! 

I wanted to ask if you were trying to deploy private or public container image on Kubernetes cluster? With private one it is indeed pretty complicated, and we will work to make it easier.

However for public one it is pretty straightforward, but we will provide some instruction nevertheless. 

Thanks for raising this issue once again!

**Comment by max06** [comment]
Hi @pbialon!

I'm trying to deploy vscode devcontainers - they usually use publicly available base images, but are built "locally" using the devcontainers-cli. Pushed prebuilt images are possible but rarely used - only in bigger teams/companies.

**Comment by pbialon** [comment]
> I wonder if you can use the local secret to create and push a suitable secret into k8s on your own...

If I understand you correctly that's what I meant by using `imagePullSecrets`. You can create a Secret in a Kubernetes cluster containing credentials to the container registry and then you can use them to pull images. If you're talking about another approach then please help me understand it :) 

> Is there really no way to run a local registry in k8s?
I didn't explore that path, but I think that you can run the registry in the k8s cluster, specify it as a prebuild image target, and then use it within kubernetes to spin up devcontainer. I don't know how complicated it will be to deploy such registry, but I guess there is a helm chart for it.

But as for now devpod can't do it without your help. You'll need to deploy the registry and pass the url path to the `devpod build` as well as `devpod up`.

**Comment by paulcwarren** [comment]
@pbialon did this blog post get written?  I am looking for some better docs as I am facing a similar issue except in my case my devcontainer uses all publicly available images so building it is not an issue - that works - instead I want to push the devcontainer image to a private repo.  But I am getting a `405 Method Not Allowed` at the end of the build-pod logs.

To my cluster I added a dockerjson secret with the creds to my repo (gcr.io in my case) and added that secret as a secret and an imagePullSecret to the default SA in the devpod ns and created a role/rolebinding to the give the SA permissions to get/list secrets.

I even spun up a docker-shell-pod to check that the SA could read the secret and then used it to docker login which worked.  So, I am bit stuck on where to go now.  I'll go look at the code to try and figure out how the build-pod is authenticating but just figured you might already have the instructions published

**Comment by pbialon** [comment]
Hi @paulcwarren and @max06!

Sorry for a late response, but in the last two weeks I've been working specifically on this issue - it will be included in the new release of devpod-kubernetes-provider!

To be able to pull private image in the kubernetes cluster, all you'd need to do is to `docker login` to that registry. Then the credentials from your `.docker/config.json` file will be transmitted to a pull secret in k8s cluster, and the devpod will use them to pull the image.

I'll let you know when the release will be available (I guess it's a matter of hours) and you'll be able to test it by yourself.

If you have any other questions or issues please let me know! 
Once again, thanks @max06 for raising this issue!

**Comment by paulcwarren** [comment]
Thanks for the update @pbialon .  Will check it out once released.  Much appreciated

**Comment by pbialon** [comment]
Hi @paulcwarren!

We released new version of kubernetes provider (https://github.com/loft-sh/devpod-provider-kubernetes/releases/tag/v0.1.1).

Please take a look how it works with newest devpod (0.3.7) version. If you need anything just let me know (especially if you need guidance or you think we lack documentation)

**Comment by jpapejr** [comment]
So how does one update a provider.. I've tried many ways: 

```
devpod provider update kubernetes https://github.com/loft-sh/devpod-provider-kubernetes/releases/download/v0.1.1/provider.yaml

 devpod provider update kubernetes loft-sh/devpod-provider-kubernetes

devpod provider update  kubernetes /Users/jtp/Downloads/devpod-provider-kubernetes-darwin-arm64

```

None of them nets me a successful update.

**Comment by paulcwarren** [comment]
Thanks @pbialon.  I am hitting the same issue as @jpapejr.  Devpod cli is reporting:

```
$ devpod provider add https://github.com/loft-sh/devpod-provider-kubernetes/releases/download/v0.1.1/provider.yaml
12:19:47 info Download provider https://github.com/loft-sh/devpod-provider-kubernetes/releases/download/v0.1.1/provider.yaml...
12:19:47 error Try using the --debug flag to see a more verbose output
12:19:47 fatal validate: agent.driver can only be docker or kubernetes
```

**Comment by pascalbreuninger** [comment]
Hey @jpapejr @paulcwarren, `v0.3.7` was the latest stable release but I think these updates only made it into the new alpha versions. Could you try again with these pls? 
https://github.com/loft-sh/devpod/releases/tag/v0.4.0-alpha.4

**Comment by jpapejr** [comment]
@pascalbreuninger To be clear, you're saying I'd need to update my devpod client to 0.4.0-alpha.4 to be able to update the kubernetes provider in-place like we tried above?

**Comment by pascalbreuninger** [comment]
@jpapejr to test it, yes. You can also wait one or two more weeks until we release a new stable release

**Comment by pbialon** [comment]
@jpapejr did you manage to test it? Now you can use official release (v0.4.1) instead of alpha. Let us know if everything works for you now.

**Comment by jpapejr** [comment]
I had to switch off the Kubernetes provider for now but yes I did get things working on 0.4.1. Thanks!
