### ISSUE TITLE
AWS ECS Fargate driver

### ISSUE THREAD

**Issue by bruecktech** [loft-sh/devpod#428]
**Is your feature request related to a problem?**
No

**Which solution do you suggest?**
Support AWS ECS Fargate as driver as alternative to Docker and Kubernetes

**Which alternative solutions exist?**
Only Docker and Kubernetes so far, but for companies that don't run Kubernetes in AWS ECS Fargate is a good option.

**Additional context**

**Comment by piotr-yuxuan** [comment]
Also, for small individual contributors, ECS/Fargate may provide a more cost-competitive solution that on-demand EC2 instances. Another solution would be to use EC2 spot instances, but that might interrupt human work from time to time.

**Comment by ThomasK33** [comment]
Hey @bruecktech & @piotr-yuxuan 👋 

We've just released an [ECS provider for DevPod](https://github.com/loft-sh/devpod-provider-ecs).
