### ISSUE TITLE
Downloading Devpod_windows_x64_en_US triggers Windows Defender on Windows 11

### ISSUE THREAD

**Issue by 1technophile** [loft-sh/devpod#429]
**What happened?**

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/cdfe639e-65d6-481e-a671-6ab37f040c45/b7505e6d-eff2-41bb-9eae-aba8d4b127f1)

```
containerfile: C:\Users\florian\Downloads\DevPod_windows_x64_en-US.msi
file: C:\Users\florian\Downloads\DevPod_windows_x64_en-US.msi->app.cab->Bin_devpod_cli.exe
```

**What did you expect to happen instead?**
No virus threat detected

**How can we reproduce the bug?** (as minimally and precisely as possible)
Download Devpod  for Windows from this page:
[https://devpod.sh/](https://devpod.sh/)

**Local Environment:**

* Operating System: windows 11 V2H2
* ARCH of the OS: i386
* Windows Defender Security Intelligence version: 1.391.2201.0

**Comment by pascalbreuninger** [comment]
oh wow, thank you for reporting this issue! We'll investigate

**Comment by pascalbreuninger** [comment]
we weren't able to reproduce this issue unfortunately. Let us know if there's something specific we need to enable on windows
