### ISSUE TITLE
Adding new SSH provider hangs

### ISSUE THREAD

**Issue by MicroPJ** [loft-sh/devpod#430]
**What happened?**
Adding new provider, type SSH, using root@IPADDRESS. Enter details, click Add Provider and the button continually spins. Provider isnt added as expected.

**What did you expect to happen instead?**
Provider added and ready to use for workspace

**How can we reproduce the bug?** (as minimally and precisely as possible)

Click Add Provider
Select SSH
Enter root@IPADDRESS
Click Add Provider button

**Local Environment:**

* DevPod Version: v0.1.10
* Operating System: windows 11
* ARCH of the OS: AMD64

**DevPod Provider:**

* Cloud Provider: PulseHeberg VPS
* Kubernetes Provider: n/a
* Local/remote provider: ssh1
* Custom provider: n/a

Attempted on different Windows machines, 10 and 11, same results - just hangs

**Comment by navaneeth-dev** [comment]
Same issue windows 11

**Comment by segfly** [comment]
Also ran into this issue on every version of DevPod I've tried up to v0.2.1. Overall the UI seems very buggy and resource hungry, so I decided to run `provider create ssh` from the CLI and it worked just fine.

**Comment by JonasVlaeyen** [comment]
For me, having a ssh-agent running before creating the provider fixes this issue. 

This is why I think this fixes the issue:
When creating the provider, the ssh program on your system waits for the user to input the password (for the private key if you are using one). When creating the provider with the CLI, you can just enter the password, with the UI you cannot. I don't know if this is the intended behavior, but if it is, it would be useful to have this explained somewhere in the documentation or UI.

**Comment by segfly** [comment]
Interesting theory @JonasVlaeyen, but it doesn't explain the situation I encountered above: My environment has a working ssh-agent with a key already loaded, and the UI still hangs for me but the CLI does not.

It's starting to seem that is more than one issue that is causing the same symptom we are collectively seeing.

**Comment by pascalbreuninger** [comment]
@MicroPJ Do you still experience this issue with newer versions of DevPod?
