### ISSUE TITLE
DevPod should not close the window of an IDE workspace when we open another IDE on the same IDE.

### ISSUE THREAD

**Issue by bruno-lopes** [loft-sh/devpod#431]
**Is your feature request related to a problem?**
Yes. Currently, when I open one workspace in VSCode, it closes the window of another workspace that was opened in VSCode.

**Which solution do you suggest?**
DevPod should open another window of the IDE with the other workspace without closing the previous workspace window.

**Which alternative solutions exist?**
Considering VSCode, it is possible to open one workspace on VSCode and the other on VSCode Browser, but I don't think it is a good alternative, since I like to have my browser "free".
Also, it is possible to go on File menu, select Open Recent, hold CTRL key and select the previous application (workspace) on remote. But it a little bit disappointing.

**Additional context**

**Comment by FabianKramm** [comment]
@bruno-lopes thanks for creating this issue! Yeah we also thought about that, since we use the vscode deeplink to open the workspace, I'm not sure if this was possible there with an additional parameter, but we could also fallback to the code cli if its there as it works with that.

**Comment by FabianKramm** [comment]
@bruno-lopes we found a solution, and from now on devpod will default to not opening the same window which can be toggled via:
```
devpod up ... --ide vscode --ide-option OPEN_SAME_WINDOW=true
```

**Comment by bruno-lopes** [comment]
@FabianKramm very thanks!
