### ISSUE TITLE
Add a web interface

### ISSUE THREAD

**Issue by hex-developer** [loft-sh/devpod#434]
**Is your feature request related to a problem?**

A feature Github Codespaces many users like is being able to use it from the web. The user logs in, goes to [https://github.com/codespaces](https://github.com/codespaces) and starts a codespace. They are then taken to the Visual Studio Code web editor where the repository they selected is open. For DevPod, the user is required to download a client. This impacts the project significantly because it becomes less portable.

**Which solution do you suggest?**

I understand that the way DevPod works is not really meant to be used from a browser, but I think it is probably the only feature missing that will drive people away from this project.

My suggestion is to host a server that will be available for use from a web page, with authentication of course.

Otherwise, you could make a server that users can host on their own infrastructure/cloud services so that they can connect to it from a web interface.

**Comment by pascalbreuninger** [comment]
Hey @hex-developer , thank you for opening this feature request.
We've received this kind of feedback quite often ever since we've launched DevPod and are currently investigating options of server-side DevPod that's going to be accessible from a web interface

**Comment by pascalbreuninger** [comment]
FYI: I closed this as it's on our roadmap but we don't have an ETA yet

**Comment by hex-developer** [comment]
@pascalbreuninger is there any update on this feature?

**Comment by pascalbreuninger** [comment]
We're currently running a private beta for [DevPod.Pro](https://devpod.sh/pro/)
