### ISSUE TITLE
Devpod desktop for arm64.

### ISSUE THREAD

**Issue by steveiliop56** [loft-sh/devpod#435]
**Is your feature request related to a problem?**

Yes, currently there is a devpod cli executable for arm64 (raspberry pi for example) but not a desktop one.

**Which solution do you suggest?**

Providing an arm64 devpod executable too.

**Which alternative solutions exist?**

Currently, there aren't any alternative solutions rather than just building it ourselves.

**Comment by pascalbreuninger** [comment]
Hi @steveiliop56, @89luca89 and I actually just had a conversation touching on that this morning. It's not our highest priority to be frank, but we're looking into it

**Comment by steveiliop56** [comment]
So will we see an arm64 version soon?

**Comment by pascalbreuninger** [comment]
depends on your definition of soon I guess. We're thinking about was to achieve it but there are also more pressing issues. 
If you want to speed it up, you can try to get the project to run on your arm linux machine and update the release pipeline (or tell us about the necessary steps and we'll update the pipeline)

**Comment by steveiliop56** [comment]
Ok thank you very much, I will try to build it and run it on my raspberry pi 4 4gb ram and report any issues here...

**Comment by pascalbreuninger** [comment]
Great, looking foward to it!

**Comment by jayna37** [comment]
I'm trying to build desktop on some aarch64 Linux systems, but haven't been able to so far. Has anyone succeeded? Would be happy about any pointers. I got Ampere, Raspberry Pi and Apple M2 (Asahi) here to test.
