### ISSUE TITLE
Centos 7 install issue

### ISSUE THREAD

**Issue by kaylab87** [loft-sh/devpod#436]
**What happened?**
Can't install on CentOS 7 GUI

**What did you expect to happen instead?**
Install gui version.

**How can we reproduce the bug?** (as minimally and precisely as possible)
Try to install rpm package.
*sudo yum localinstall DevPod_linux_x86_64.rpm*
Loaded plugins: fastestmirror, langpacks
Examining DevPod_linux_x86_64.rpm: dev-pod-0.1.10-1.x86_64
Marking DevPod_linux_x86_64.rpm to be installed
Resolving Dependencies
\--> Running transaction check
\---> Package dev-pod.x86_64 0:0.1.10-1 will be installed
\--> Processing Dependency: gtk3-immodules for package: dev-pod-0.1.10-1.x86_64
Loading mirror speeds from cached hostfile
\--> Processing Dependency: libappindicator-gtk3 for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libbsd for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.18)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.25)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.27)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.28)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.29)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.32)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.33)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.34)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libcrypto.so.3(OPENSSL_3.0.0)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libdeflate for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libssl.so.3(OPENSSL_3.0.0)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libwmf for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libcrypto.so.3()(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libssl.so.3()(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Running transaction check
\---> Package dev-pod.x86_64 0:0.1.10-1 will be installed
\--> Processing Dependency: libbsd for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.18)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.25)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.27)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.28)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.29)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.32)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.33)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.34)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libcrypto.so.3(OPENSSL_3.0.0)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libdeflate for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libssl.so.3(OPENSSL_3.0.0)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libcrypto.so.3()(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libssl.so.3()(64bit) for package: dev-pod-0.1.10-1.x86_64
\---> Package gtk3-immodules.x86_64 0:3.22.30-8.el7_9 will be installed
\--> Processing Dependency: gtk2-immodules(x86-64) for package: gtk3-immodules-3.22.30-8.el7_9.x86_64
\---> Package libappindicator-gtk3.x86_64 0:12.10.0-13.el7 will be installed
\--> Processing Dependency: libindicator3.so.7()(64bit) for package: libappindicator-gtk3-12.10.0-13.el7.x86_64
\--> Processing Dependency: libdbusmenu-gtk3.so.4()(64bit) for package: libappindicator-gtk3-12.10.0-13.el7.x86_64
\--> Processing Dependency: libdbusmenu-glib.so.4()(64bit) for package: libappindicator-gtk3-12.10.0-13.el7.x86_64
\---> Package libwmf.x86_64 0:0.2.8.4-44.el7 will be installed
\--> Processing Dependency: libwmf-lite = 0.2.8.4-44.el7 for package: libwmf-0.2.8.4-44.el7.x86_64
\--> Processing Dependency: libwmflite-0.2.so.7()(64bit) for package: libwmf-0.2.8.4-44.el7.x86_64
\--> Running transaction check
\---> Package dev-pod.x86_64 0:0.1.10-1 will be installed
\--> Processing Dependency: libbsd for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.18)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.25)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.27)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.28)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.29)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.32)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.33)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libc.so.6(GLIBC_2.34)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libcrypto.so.3(OPENSSL_3.0.0)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libdeflate for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libssl.so.3(OPENSSL_3.0.0)(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libcrypto.so.3()(64bit) for package: dev-pod-0.1.10-1.x86_64
\--> Processing Dependency: libssl.so.3()(64bit) for package: dev-pod-0.1.10-1.x86_64
\---> Package gtk2-immodules.x86_64 0:2.24.31-1.el7 will be installed
\---> Package libdbusmenu.x86_64 0:16.04.0-4.el7 will be installed
\---> Package libdbusmenu-gtk3.x86_64 0:16.04.0-4.el7 will be installed
\---> Package libindicator-gtk3.x86_64 0:12.10.1-6.el7 will be installed
\---> Package libwmf-lite.x86_64 0:0.2.8.4-44.el7 will be installed
\--> Finished Dependency Resolution
Error: Package: dev-pod-0.1.10-1.x86_64 (/DevPod_linux_x86_64)
Requires: libssl.so.3()(64bit)
Error: Package: dev-pod-0.1.10-1.x86_64 (/DevPod_linux_x86_64)
Requires: libc.so.6(GLIBC_2.28)(64bit)
Error: Package: dev-pod-0.1.10-1.x86_64 (/DevPod_linux_x86_64)
Requires: libc.so.6(GLIBC_2.18)(64bit)
Error: Package: dev-pod-0.1.10-1.x86_64 (/DevPod_linux_x86_64)
Requires: libbsd
Error: Package: dev-pod-0.1.10-1.x86_64 (/DevPod_linux_x86_64)
Requires: libssl.so.3(OPENSSL_3.0.0)(64bit)
Error: Package: dev-pod-0.1.10-1.x86_64 (/DevPod_linux_x86_64)
Requires: libcrypto.so.3(OPENSSL_3.0.0)(64bit)
Error: Package: dev-pod-0.1.10-1.x86_64 (/DevPod_linux_x86_64)
Requires: libcrypto.so.3()(64bit)
Error: Package: dev-pod-0.1.10-1.x86_64 (/DevPod_linux_x86_64)
Requires: libc.so.6(GLIBC_2.29)(64bit)
Error: Package: dev-pod-0.1.10-1.x86_64 (/DevPod_linux_x86_64)
Requires: libc.so.6(GLIBC_2.34)(64bit)
Error: Package: dev-pod-0.1.10-1.x86_64 (/DevPod_linux_x86_64)
Requires: libc.so.6(GLIBC_2.33)(64bit)
Error: Package: dev-pod-0.1.10-1.x86_64 (/DevPod_linux_x86_64)
Requires: libc.so.6(GLIBC_2.25)(64bit)
Error: Package: dev-pod-0.1.10-1.x86_64 (/DevPod_linux_x86_64)
Requires: libc.so.6(GLIBC_2.32)(64bit)
Error: Package: dev-pod-0.1.10-1.x86_64 (/DevPod_linux_x86_64)
Requires: libdeflate
Error: Package: dev-pod-0.1.10-1.x86_64 (/DevPod_linux_x86_64)
Requires: libc.so.6(GLIBC_2.27)(64bit)

**Local Environment:**

* DevPod Version: v0.1.10
* Operating System: CentOS Linux release 7.9.2009 (Core)
* ARCH of the OS: AMD64

**DevPod Provider:**

* Cloud Provider: google | aws | azure | digitalOcean
* Kubernetes Provider: \[use `kubectl version`\]
* Local/remote provider: docker | ssh
* Custom provider: provide imported `provider.yaml` config file

**Anything else we need to know?**

**Comment by yCrab** [comment]
Hi @kaylab87, thanks for opening the issue. I’m not really familiar with CentOS but the error messages say you’re missing libc and a few other system dependencies that are usually available. Could you try to install them and check again?
