### ISSUE TITLE
Started a go http server, but cannot access it through the browser

### ISSUE THREAD

**Issue by upupnoah** [loft-sh/devpod#438]
**What happened?**  
When I use Docker as the provider and create a Go workspace, using the default https://github.com/microsoft/vscode-remote-try-go, after opening it with VSCode and running the code, when trying to access http://127.0.0.1:9000 through a browser, access is denied.

**What did you expect to happen instead?**  
Output Hello, Alex.Name on the browser.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Using Docker as the provider, click on the Go logo on the interface to create a default workspace. Then use VSCode to open and run the code. Afterwards, enter 127.0.0.1:9000 in your browser.
My *`devcontainer.json`*:
```json
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/go
{
	"name": "Go",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/go:0-1.19-bullseye",

	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},

	// Configure tool-specific properties.
	"customizations": {
		// Configure properties specific to VS Code.
		"vscode": {
			"settings": {},
			"extensions": [
				"streetsidesoftware.code-spell-checker"
			]
		}
	},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [9000],

	// Use 'portsAttributes' to set default properties for specific forwarded ports. 
	// More info: https://containers.dev/implementors/json_reference/#port-attributes
	"portsAttributes": {
		"9000": {
			"label": "Hello Remote World",
			"onAutoForward": "notify"
		}
	}

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "go version",

	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}

```

**Local Environment:**  
- DevPod Version: [use `0.1.10 (20230621.164324)`]
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Local/remote provider: docker

**Anything else we need to know?**  
The same operation, creating a default Python container is no problem, and the result was successfully returned at 127.0.0.1:9000.

**Comment by yCrab** [comment]
@upupnoah thanks for opening the issue. Would you mind checking if the port is opened in the go workspace using vscodes ports view (run `Ports: Focus on Ports View` in vscode)?

**Comment by upupnoah** [comment]
> @upupnoah thanks for opening the issue. Would you mind checking if the port is opened in the go workspace using vscodes ports view (run `Ports: Focus on Ports View` in vscode)?
I just need to add port 9000 in Ports View. Thank you!

**Comment by upupnoah** [comment]
> @upupnoah thanks for opening the issue. Would you mind checking if the port is opened in the go workspace using vscodes ports view (run `Ports: Focus on Ports View` in vscode)?

I have added port 9000 in Ports View, it's working now. Thank you!

**Comment by upupnoah** [comment]
Already solved.
