### ISSUE TITLE
devpod up seems to resolve symlinks

### ISSUE THREAD

**Issue by ibuildthecloud** [loft-sh/devpod#439]
**What happened?**

My devpod would never start and looking at it further I noticed that the context folder on the remote machine was huge and still syncing.  This was because my local directory had a symlink to /nix/store which is massive. It seems like devpod should copy symlinks as is and not de-reference them.  Also this seems like a potential security issue.

**Local Environment:**

* DevPod Version: v0.1.1
* Operating System: linux
* ARCH of the OS: AMD64
* **DevPod Provider:**
* Cloud Provider: digitalOcean

**Comment by FabianKramm** [comment]
@ibuildthecloud thanks for creating this issue! Yes you are right, we should change that
