### ISSUE TITLE
Documentation - Instruction for building from source

### ISSUE THREAD

**Issue by mavencode01** [loft-sh/devpod#443]
**Is your feature request related to a problem?**

No
**Which solution do you suggest?**
Instruction for building from source

**Which alternative solutions exist?**
N/A

**Additional context**
N/A

**Comment by pascalbreuninger** [comment]
Have a look at https://github.com/loft-sh/devpod/blob/main/CONTRIBUTING.md 
If you encounter any problems while building from source, please don't hesitate and open a PR to update the file
