### ISSUE TITLE
Add Dark mode options with OS matching by default

### ISSUE THREAD

**Issue by ThomasRedstone** [loft-sh/devpod#445]
**Is your feature request related to a problem?**

No

**Which solution do you suggest?**

Add Dark mode options with OS matching by default.

**Which alternative solutions exist?**

**Additional context**

Modern Operating Systems support dark mode; many applications detect that and adopt that setting.

It's also helpful to have the option to override the OS-level settings manually.

**Comment by ThomasRedstone** [comment]
That's great to hear @pascalbreuninger, thanks for you confirming it's on the roadmap!

**Comment by pascalbreuninger** [comment]
@ThomasRedstone aaaand it's back 👍 Will need a bit to update all providers that need different icon in dark mode but should generally work with the next release coming around thursday next week

**Comment by pascalbreuninger** [comment]
we had to disable it for the time being, was't quite there yet - will bring it back soon-ish
