### ISSUE TITLE
[Question] does devpod support rootless docker?

### ISSUE THREAD

**Issue by haiwu** [loft-sh/devpod#448]
It seems devpod supports rootless podman. Does it support rootless docker?

**Comment by 89luca89** [comment]
Hi @haiwu 

Technically it shouldn't be a problem either rootless docker or rootless containerd+nerdctl, but I haven't tested

I'll  do and let you know :+1:

**Comment by haiwu** [comment]
Thanks @89luca89 ! 

I just tried this with ssh provider on a host with rootless docker only (there's no docker installed for root user). And I got this error message: 

[11:13:40] info Creating devcontainer...
[11:13:41] info Cloning into '/root/.devpod/agent/contexts/default/workspaces/vscode-remote-try-python/content'...
[11:13:42] fatal agent error: devcontainer up: find dev container: find container: : exec: "docker": executable file not found in $PATH
error parsing workspace info: rerun as root: exit status 1
: exit status 1


It seems it by default would become root user, which is not what I want .. Maybe I am missing some additional configuration for ssh provider?

**Comment by mway** [comment]
Another datapoint - from the UI, attempting to use local docker (macos, apple silicon):

```Seems like docker is not reachable on your system.
Please make sure docker is installed and running.
You can verify if docker is running correctly via 'docker ps'
init: exit status 1```

While I can confirm that it is running:

```
docker ps -q
15043754d4e3
fe48d8c6ea4f
c14603168007
```

**Comment by haiwu** [comment]
@89luca89 : I just tried latest beta version 0.2.0-20, still not working. I turned on debug, and here are the last few lines:

[23:01:31] debug Acquire workspace lock...
[23:01:31] debug Acquired workspace lock...
[23:01:31] info Creating devcontainer...
[23:01:31] debug Inject and run command: '/tmp/devpod/agent' agent workspace up --workspace-info ...' --debug
[23:01:31] debug execute inject script
[23:01:31] debug Run command provider command: ssh -oStrictHostKeyChecking=no \
    -p ${PORT} \
    ${EXTRA_FLAGS} \
    "${HOST}" \
    "${COMMAND}"
[23:01:32] debug Received line after pong: done
[23:01:32] debug done inject
[23:01:32] debug done injecting
[23:01:32] debug Done executing up command
[23:01:32] debug Done InjectAgentAndExecute
[23:01:32] debug Done creating devcontainer
[23:01:32] debug done exec
[23:01:32] fatal didn't receive a result back from agent

It seems it could see the rootless docker, but the IDE did not receive result back from agent. 

Is there anything else I could try?

**Comment by mway** [comment]
Quick update, but at least as of v0.2.1, I tried specifying the local docker socket address for `DOCKER_HOST` and it worked. I got the path by running:

```
# docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                              KUBERNETES ENDPOINT   ORCHESTRATOR
default *           moby                Current DOCKER_HOST based configuration   unix:///foo/run/docker.sock
desktop-linux       moby                Docker Desktop                            unix:///foo/run/docker.sock
```

Then in the UI, I just used that path (`unix:///foo/run/docker.sock`) as the docker host, and it worked as expected.

**Comment by haiwu** [comment]
That's not rootless docker. The above assumes you are root user with docker, which is working for me. But we really want to have rootless docker or rootless podman to work, for security reason. 

@89luca89: Any update?

**Comment by mway** [comment]
> That's not rootless docker. The above assumes you are root user with docker, which is working for me. But we really want to have rootless docker or rootless podman to work, for security reason. 
> 
> 
> 
> @89luca89: Any update? 

Not running as root, but ok.

**Comment by 89luca89** [comment]
Hi @haiwu 
Rootless podman already works as of now

I'll try `rootless-docker` itself this week, in the meantime you can try rootless podman which is already supported

**Comment by 89luca89** [comment]
From my tests, `rootless-docker` works correctly:

![image](https://github.com/loft-sh/devpod/assets/598882/ff8fe520-c46b-47d6-bb94-fa11cefd405f)

Both that and rootless podman

**Comment by 89luca89** [comment]
And it also worked with `containerd+nerdctl` with that setup :+1:

**Comment by haiwu** [comment]
@89luca89 Thanks! This still does not work for me. What I tested before on this is: 
I created an SSH provider, this would login remotely to my own host, the provider's "Docker Path" is set to 'docker', "Agent Path" is set to '/tmp/devpod/agent', all defaults. Then I tried to create a workspace from this provider. I could run rootlessdocker manually after logging into this host via ssh as my own username without issue. 

The error I got is: 
`[10:32:52] info find dev container: docker ps: exec: "docker": executable file not found in $PATH`. But it is in my own $PATH if I manually remotely ssh into this host. This rootless binary is stored as in /home/myhome/bin/docker on my remote ssh host. 

I guess the code for SSH provider might have some assumption on how to initialize user ssh session remotely and grab $PATH, but that assumption does not seem to work for my case. 

I am not sure if you tested using a localhost or a remote ssh via SSH provider..

**Comment by haiwu** [comment]
Another issue I see using this with rootlessdocker is: 

I see this in the log: 
`[10:32:50] info Use /root/.devpod/agent/contexts/default/workspaces/vscode-remote-try-python as workspace dir`

Also I see you have `wheel` as your user's group. 

This means user would have to be able to do 'sudo root'. The idea of using rootlessdocker or rootlesspodman is so that we don't give user sudo root permission for security reasons. 

Is it possible for devpod users to customize `/root/.devpod/agent` folder so that it could be something else that non-root user would have access to later? 

Otherwise the other workaround I could think of would be to create `/root/.devpod` folder ahead of time, and assign that to some group `devpod_users_group`, and then we assign all such users to this group later. Would this work? Not sure if it would be ok if this parent folder already exists ahead of time.

**Comment by 89luca89** [comment]
mmh ok I tested the docker provider itself
I'll check for the ssh provider, it may be that we also need to add DOCKER_HOST to it

> I see this in the log:
[10:32:50] info Use /root/.devpod/agent/contexts/default/workspaces/vscode-remote-try-python as workspace dir
> Also I see you have wheel as your user's group.

This is related to the ssh provider, the devpod agent is running as root, thus using root's home directory

**Comment by haiwu** [comment]
ah ok. We would prefer to be able to customize to run devpod agent in user case of rootless(docker|podman) as user self, rather than as root user..

**Comment by 89luca89** [comment]
That would be possible just using ssh as the user 
Setting up the HOST for the ssh-provider to be user@ip instead of just ip

**Comment by haiwu** [comment]
Ok I just tried that, it seems it first tried to run as my userid via ssh, but it failed with error 
`[13:55:08] info Error trying to reach docker daemon: docker command 'docker' not found`. 

Then it retried with `Rerun as root`, failed again after that. 

I am not sure what's the default logic used to try to reach docker daemon for ssh provider. If I manually ssh logging into the host, `docker` is in my $PATH.

**Comment by haiwu** [comment]
@89luca89: Have you been able to test this use case?

**Comment by 89luca89** [comment]
Hello @haiwu 

yes and it's working, these are the steps I've followed:

- I've set up a linux node (fedora in this case) with a non-root user
- installed rootless docker in it
- in ~/.bashrc I've added `export DOCKER_HOST=unix:///run/user/1000/docker.sock`
- addedd the `devpod-provider-ssh` specifying in the HOST `luca-linux@IP`

Rootless docker was used and no problems detected :+1: 

![image](https://github.com/loft-sh/devpod/assets/598882/cf12b196-41f3-4a55-bdfa-79fa78f9f256)

**Comment by haiwu** [comment]
@89luca89 : Thank you! I have almost the same setting, and I just tried the latest devpod 0.3.4, and it still not working for me. It kept complaining for the same reason: 
```
[18:26:13] debug execute inject script
[18:26:13] debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.3.4
[18:26:13] debug Run command provider command: ssh -oStrictHostKeyChecking=no \
    -p ${PORT} \
    ${EXTRA_FLAGS} \
    "${HOST}" \
    "${COMMAND}"
[18:26:14] debug Received line after pong: done
[18:26:14] info Error trying to reach docker daemon: docker command 'docker' not found
```

I added '-v' flag as extra flag, and I could see it got into the remote host via ssh, but it just can't find docker command. But if I manually login to the host, docker command is available. 

Is there anything else I could try?

**Comment by haiwu** [comment]
Seems this was caused by something in .bashrc. After getting a very basic .bashrc in place, things are now working.

**Comment by haiwu** [comment]
@89luca89 : 

Just found another issue. It turns out that for both rootlessdocker and rootlesspodman, the vscode does not have permission to make any modifications. It always comes back with error "Permission Denied". If I ssh into the remote host, and do "docker exec -it ... bash", and cd into /workspace/..., then I have the permission to make modifications. And I do "chmod a+rwx README.md", then after that, I could make modifications to this file within vscode. 

Have you tested this from your end?

**Comment by haiwu** [comment]
after uncommenting this line '"remoteUser": "root"' in devcontainer.json, it is now working for rootlessdocker, but it still kept failing with same error for rootlesspodman.

**Comment by haiwu** [comment]
@89luca89 : Found another issue even with rootlessdocker, which is almost working for all test cases: After setting 'Inactivity Timeout' to '1m' for ssh provider, and recreated the rootlessdocker workspace (after manually deleting the file '/tmp/devpod/agent'), the spinned up docker container would keep running forever, I don't see agent would terminate the running container after 1 minute idle time. 

Does this work the same for your rootlessdocker?

**Comment by ChristopherRabotin** [comment]
@89luca89 are you running devpod instead of a distrobox container or on the host? I'm trying to run it on the host (using the AppImage) and after telling DevPod that `docker` is located at `/usr/bin/podman` (I'm running OpenSuse Aeon/MicroOS).

**Comment by haiwu** [comment]
@89luca89 : I have already figured out how to get this to work for both rootless docker and rootless podman. It turns out we need to look at devcontainer document on this topic in order to figure out the settings needed in devcontainer.json. yes we need different extra config entry/entries for rootless docker and rootless podman. This is pretty painful to figure out, but that's what is needed to get this to work. 

Also I have not figured out how to get this to work for DevPod and Jupyter, with rootless docker and rootless podman. For example, with rootless podman with `userns=keep-id` setting, by default, Jupyter with DevPod would end up with notebook files being owned by my own userid inside the container. But I have not figured out how to set this in 'devcontainer.json' file:
remoteUser=my_own_user_id

If setting the above to remoteUser=vscode, or remoteUser=codespace, then this user does NOT have permission to download stuff into where the notebook python codes are stored inside the container. The same if using remoteUser=root. 

@89luca89 : Could you please figure this out from your end, on what extra entries are needed for rootless podman for Jupyter integration with DevPod in file `devcontainer.json`? 

I used this `https://github.com/github/codespaces-jupyter` to test, in particular, this notebook for testing, and I could not get this to work due to permission issue with rootless podman using 'userns=keep_id': `https://github.com/github/codespaces-jupyter/blob/main/notebooks/image-classifier.ipynb`.
