### ISSUE TITLE
Add ability to install dotfiles from a repository

### ISSUE THREAD

**Issue by gbraad** [loft-sh/devpod#455]
**Is your feature request related to a problem?**
Inconsistency with Codespaces? The devcontainer will start, but is not customized as expected.

**Which solution do you suggest?**
As part of the start command, a repository for dotfiles needs to be pulled and installation started:

[https://docs.github.com/en/codespaces/customizing-your-codespace/personalizing-github-codespaces-for-your-account#dotfiles](https://docs.github.com/en/codespaces/customizing-your-codespace/personalizing-github-codespaces-for-your-account#dotfiles)

**Which alternative solutions exist?**
Prebuild container images.

**Additional context**

**Comment by pascalbreuninger** [comment]
Hey @gbraad, thanks for opening the issue. Dotfile sync is actually on our roadmap for the upcoming releases, I'll let you know when it's ready

**Comment by 89luca89** [comment]
Hi @gbraad this is now implemented :)
