### ISSUE TITLE
Can't connect to devpod using VS Code

### ISSUE THREAD

**Issue by duttaoindril** [loft-sh/devpod#460]
**What happened?**

devpod can't connect to vs code

**What did you expect to happen instead?**

use vscode with devpod

**How can we reproduce the bug?** (as minimally and precisely as possible)

I just created the python container and got the error after it launched VS Code

**Local Environment:**

* DevPod Version: v0.1.10
* Operating System: mac
* ARCH of the OS: ARM64

**DevPod Provider:**

* Local/remote provider: docker

**Anything else we need to know?**
<img width="1027" alt="image" src="[https://github.com/loft-sh/devpod/assets/4969854/049a8478-b396-428a-95fd-34325b253b6b](https://github.com/loft-sh/devpod/assets/4969854/049a8478-b396-428a-95fd-34325b253b6b)">

**Comment by pascalbreuninger** [comment]
Hi @duttaoindril, thank you for opening the issue. 
Can you connect to the container when you run the workspace plain SSH instead of VSCode?
`devpod up $YOUR_WORKSPACE --ide none`

**Comment by cakriwut** [comment]
Hi,

I have the same problem , and through `--debug` options it shows the command args to launch remote vscode `--disable-extension ms-vscode-remote.remote-containers`. Removing this args, will launch vscode perfectly.
Source code open.go, line 79.
https://github.com/loft-sh/devpod/blob/e0b2eb06cefae38f415671daf0757de7103ffa56/pkg/ide/vscode/open.go#L79

**Comment by pascalbreuninger** [comment]
Hey @cakriwut, that's quite curious because devpod connects to vscode using the `remote-ssh` extension. We disable `remote-containers` because it displays a popup prompting you to restart the workspace in another devcontainer because it can't detect it's already in one started by devpod. 

Would you mind pasting the full debug log of the failed attempt here?

**Comment by FabianKramm** [comment]
Maybe we can check if remote-containers is actually installed and then disable it only if found

**Comment by b-robey** [comment]
I'm also encountering this. I noticed that if I run the command spat out by using `--debug` then it launches. For example, the debug logs say:

`Run vscode command code --folder-uri vscode-remote://ssh-remote+vscode-remote-try-rust.devpod//workspaces/vscode-remote-try-rust --disable-extension ms-vscode-remote.remote-containers --new-window`

That never finishes, but if I run:
`code --disable-extension ms-vscode-remote.remote-containers --new-window  --folder-uri vscode-remote://ssh-remote+vscode-remote-try-rust.devpod//workspaces/vscode-remote-try-rust`

then a new VS Code window opens.

**Comment by neogopher** [comment]
Hi @b-robey ,
We already have a [fix](https://github.com/loft-sh/devpod/issues/681) for this and it would be available in the next release which is coming very soon. 
BTW, just for reference may I know what OS you are using.

**Comment by b-robey** [comment]
@neogopher, sure, I'm on Windows 10.

**Comment by pascalbreuninger** [comment]
Should be fixed together with #681
