### ISSUE TITLE
Can't open on desktop mode

### ISSUE THREAD

**Issue by ggsuha** [loft-sh/devpod#461]
I installed the DevPod through CLI (AMD), but when I click the icon in the app menu, it won't start.

I tried to run it with terminal, there are `devpod` and `dev-pod`.
`devpod` get ouput like below

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/a6598876-ae5a-412e-8560-a557b56b1bae/c1cc52f5-212d-4fda-b6e1-f139420943be)

While `dev-pod` returns `dev-pod: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory`.

Is DevPod requires OpenSSL 3?

**Comment by 89luca89** [comment]
Hi @ggsuha 

can you give me some more informations?
- how did you install devpod 
- which OS you're on

Thanks!

**Comment by ggsuha** [comment]
@89luca89 Hai, I installed using CLI 
```
curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64" && sudo install -c -m 0755 devpod /usr/local/bin && rm -f devpod
```

Here is my OS
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

**Comment by akafazov** [comment]
I have the same issue on Debian 11

**Comment by cristhyanearaldi** [comment]
Hi! I have the same issue here on Ubuntu 20.04.6 LTS. Any update with this question?

**Comment by 89luca89** [comment]
Hi @haiwu @ggsuha I've tested building on ubuntu-20 instead of ubuntu-latest

Can you test this deb on you systems?

[dev-pod_0.0.0_amd64.deb.zip](https://github.com/loft-sh/devpod/files/12513252/dev-pod_0.0.0_amd64.deb.zip)

It seems from my containerized testing it works, let me know

**Comment by akafazov** [comment]
> Hi @haiwu @ggsuha I've tested building on ubuntu-20 instead of ubuntu-latest
> 
> Can you test this deb on you systems?
> 
> [dev-pod_0.0.0_amd64.deb.zip](https://github.com/loft-sh/devpod/files/12513252/dev-pod_0.0.0_amd64.deb.zip)
> 
> It seems from my containerized testing it works, let me know

works for me

**Comment by carstencodes** [comment]
I have the issue exactly the other way around. As I am using LinuxMint 21.3 - based on Ubuntu 22.04, I have OpenSSL 3 on it.

I had to download and install libopenssl1.1.1w (by install I mean also compiling it and adding ld-conf entries for it).

I think there need to be two binaries or libssl1.1 should be mentioned on https://devpod.sh/docs/getting-started/install
