### ISSUE TITLE
ssh error

### ISSUE THREAD

**Issue by shenmingming** [loft-sh/devpod#465]
Run init provider command: ssh -
oStrictHostKeyChecking=no
\-p ${PORT}
${EXTRA_FLAGS}
"${HOST}"
sh -c ""if \[ $(id -ru) -eq 0 \];   then
exit 0;   fi;
if (!   mkdir -p $(dirname ${AGENT_PATH})
|| \[ !   -w $(dirname ${AGENT_PATH}) \]) &&
!   sudo -nl >/dev/null;   then
echo $AGENT_PATH is not writable,
passwordless sudo or root user required;
exit 1;
fi;
if !   command -v ${DOCKER_PATH} >/dev/null
&& !   sudo -nl >/dev/null;   then
echo $DOCKER_PATH not found, passwordless
sudo or root user required;   exit 1;
fi ""
if \[ $?   != 0 \];   then

> &2 echo "Unexpected non-zero ssh exit
> &2 echo "Please make sure you have
> configured the correct SSH host"
> &2 echo "and the following command can be
> executed on your system:"
> &2 echo ssh -oStrictHostKeyChecking=no -p
> "${PORT}" "${HOST}"
> exit 1
> fi
> "ssh": executable file not found in $PATH
> Unexpected non-zero ssh exit code
> Please make sure you have configured the
> correct SSH host
> and the following command can be executed
> on your system:
> ssh -oStrictHostKeyChecking=no -p 22
> root@ip
> exit status 1
> init
> [github.com/loft](http://github.com/loft)sh/devpod/cmd/provider.initProvider

**Comment by shenmingming** [comment]
![image](https://github.com/loft-sh/devpod/assets/20808075/07bd6dde-0da7-403b-add2-b4c230d7cfea)

**Comment by shenmingming** [comment]
Hello, the local computer (windows 10) installed Devpod client, want to connect through SSH, the local and the current SSH host have installed OpenSSH, mutual access is through, the following exceptions are reported:
Extra Flags
Extra flags to pass to the SSH command.
Enter Extra Flags
Agent options
Add Provider Set as default
"ssh": executable file not found in $PATH
Unexpected non-zero ssh exit code
Please make sure you have configured the
correct SSH host
and the following command can be executed on
your system:
ssh -oStrictHostKeyChecking=no -p 22
root@IP
init: exit status
I hope you can help me. Thank you

**Comment by pascalbreuninger** [comment]
are you sure `ssh` is accessible from your `$PATH`? 
What happens if you type `ssh` in the regular command line?

**Comment by shenmingming** [comment]
![image](https://github.com/loft-sh/devpod/assets/20808075/5568c7d8-f448-45f3-977e-72d79764cda2)
![image](https://github.com/loft-sh/devpod/assets/20808075/f62586f1-55f4-4687-a7aa-c34dda8e4a28)

**Comment by pascalbreuninger** [comment]
Alright, thank you. I will need to investigate a bit more then, might be related to other windows ssh problems

**Comment by shenmingming** [comment]
Thank you. You can try using the Devpod Windows client to SSH connect on your own. We look forward to your reply.

**Comment by shenmingming** [comment]
Do you need to install a development environment for Go?

**Comment by pascalbreuninger** [comment]
Not if you downloaded the CLI/Desktop app

**Comment by pascalbreuninger** [comment]
@shenmingming are you still experiencing this problem with newer versions of DevPod?
