### ISSUE TITLE
Provider logo Civo, instead of Azure

### ISSUE THREAD

**Issue by audacioustux** [loft-sh/devpod#480]
**What happened?**
<img width="157" alt="Screenshot 2023-07-05 at 7 06 47 PM" src="[https://github.com/loft-sh/devpod/assets/7238675/17d4ae92-d8d6-46a9-97e8-ce4c75ad6900](https://github.com/loft-sh/devpod/assets/7238675/17d4ae92-d8d6-46a9-97e8-ce4c75ad6900)">

**What did you expect to happen instead?**
expected to see Azure logo

**How can we reproduce the bug?** (as minimally and precisely as possible)
by adding Azure provider in Devpod Desktop (Version 0.1.10 (20230621.164320))

**Local Environment:**

* DevPod Version: v0.1.10
* Operating System: mac
* ARCH of the OS: AMD64

**Comment by FabianKramm** [comment]
@audacioustux thanks a lot for creating this issue! You are correct, thats definitely a mistake, we will fix that!
