### ISSUE TITLE
Question: how to handle setup with projects that depend on other projects

### ISSUE THREAD

**Issue by aareman** [loft-sh/devpod#482]
For example, if you have a micro service setup that spans multiple repos but require all of them to be running for any app to work (more realistic example sso, auth server and downstream need to be running)

We have a local dev setup with a reverse proxy for all the web service frontends. How do you suggest working that out with devpods?

\_Everything is local development using docker, docker compose, and vscode devcontainers. \_

Any direction would be helpful

Thank you, this tool looks wonderful 👍

**Comment by lizardruss** [comment]
Hello! I think you might start with the built-in docker provider for DevPod:
```shell
docker use provider docker
```

Much of the VSCode devcontainer functionality should map over from there. There's also support for using docker compose, but I'd need more details to give a more specific answer. Some questions to get the ball rolling:
- Do you use docker-compose to start all services, or is there a docker-compose for each service?
- Does each service get a vscode devcontainer, or only one?
- What are you using the reverse proxy to do?

**Comment by FabianKramm** [comment]
Closing this for now, please feel free to reopen if still relevant
