### ISSUE TITLE
SSH Connection fails after June 2023 VSCode update

### ISSUE THREAD

**Issue by jasminmoneymaker** [loft-sh/devpod#486]
**What happened?**
I had a simple workspace working properly. My VSCode auto-updated from version 1.79 to version 1.80, and DevPod App started failing to connect to the IDE with the following error: "Failed to connect to the remote extension host server (Error: Not an authority that can be resolved!)"

I was, however, able to establish a connection TO the DevPod workspace FROM VSCode using the Remote SSH extension.

After reverting to the May 2023 (version 1.79) VSCode, the problem disappeared.

**What did you expect to happen instead?**
I expected to be able to successfully open/start my workspace with VSCode from the DevPod app.

**How can we reproduce the bug?** (as minimally and precisely as possible)
Use VSCode June 2023 (version 1.80)
Create a simple workspace with a Docker provider
From the DevPod app, open/start the workspace with VSCode

My `devcontainer.json`:

```
{"image":"mcr.microsoft.com/devcontainers/python:3","build":{}}
```

**Local Environment:**

* DevPod Version: v0.2.0
* Operating System: mac
* ARCH of the OS: ARM64

**DevPod Provider:**

* Local/remote provider: docker

**Anything else we need to know?**
No.

**Comment by jfroco** [comment]
Same problem here: Windows + VSCode 1.80 + DevPod 0.2.0

![image](https://github.com/loft-sh/devpod/assets/2047144/b5e03b95-f24d-493c-8cec-3975c8aa753d)

**Comment by FabianKramm** [comment]
@jasminmoneymaker thanks a lot for the issue! Seems to be an upstream vscode issue https://github.com/microsoft/vscode/issues/187202 with the path not being correct, maybe we can build a workaround until this problem is fixed.

**Comment by FabianKramm** [comment]
@jasminmoneymaker found a solution, should be fixed in the next DevPod release

**Comment by jasminmoneymaker** [comment]
Thanks @FabianKramm!

**Comment by jfroco** [comment]
Thank you! @FabianKramm It works!!!
