### ISSUE TITLE
Allow setting of envvars/sensitive data to workspaces

### ISSUE THREAD

**Issue by mrsimonemms** [loft-sh/devpod#492]
**Is your feature request related to a problem?**
In Gitpod, there is the ability to set environment variables to the control plane. These are then loaded when your workspace starts up, which are very useful for storing credentials and sharing them securely.

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/70bcb44b-30fc-4b95-9960-ffcd0b4a5e37/c565bc4d-8232-46f7-bc75-8a0d18c2100e)

**Which solution do you suggest?**
Something similar to Gitpod. A "user settings" page with the ability to add arbitrary envvars limited by scope (`<owner>/<repo>` with support for `*` wildcards in both parts).

For bonus points, it would be useful allowing both envvars and files to be set similar to how GitLab does for CI/CD settings variables. That way, if we wanted to store a `kubeconfig` file or a GCP service account JSON file, we wouldn't need to [convert the envvar into a file via Dotfiles](https://github.com/mrsimonemms/gitpod-dotfiles/blob/main/setup.sh#L66,L80)

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/58b7b2d6-f9fb-488b-b277-6cbcd5b2e87d/047a3bc4-cdb0-4234-9ad1-3cff082aae3c)

**Which alternative solutions exist?**
Gitpod supports this

**Additional context**
[Slack thread](https://loft-sh.slack.com/archives/C056ZDZPJ4W/p1688742390308089)

**Comment by FabianKramm** [comment]
@mrsimonemms thanks a lot for creating this issue! Yes that is a very good idea, I think this was part of our roadmap item to implement dotfiles as well.

**Comment by pascalbreuninger** [comment]
We've never linked back the PRs but DevPod supports the `--workspace-env` and `--workspace-env-file` flags
