### ISSUE TITLE
Sigstore container signing

### ISSUE THREAD

**Issue by d3287t328** [loft-sh/devpod#493]
**Is your feature request related to a problem?**
Improve supply chain security by using Rekor for metadata and immutable log generation for the DevPod binary and or for managed containers created by DevPod.

**Which solution do you suggest?**
Rekor via [https://github.com/sigstore/rekor/tree/main](https://github.com/sigstore/rekor/tree/main)
It is not clear to me just yet if the best feature implementation would look something like `devpod sign container name` or if the rekor-cli would be better for this task and I so I thought I would share this as an idea because even if that turns out to not be the right solution you could still release your binaries with Rekor.

**Which alternative solutions exist?**
The only similar service that I know of is Cosign but it has a different purpose just for pods.

**Additional context**
I was recently speaking with a colleague about the importance of supply chain security for our project and I later saw how Tekton is signing their release binaries with a REKOR_UUID. As I have been testing devpods this week I thought this would be a fantastic addition to solving this issue earlier in our development process and it may be particularly useful in the context of adding the uuid to the [devcontainer.json](https://containers.dev/) file.

**Comment by FabianKramm** [comment]
@d3287t328 thanks for creating this issue! Yes sounds like a cool idea, not sure when we will have time to implement this, but if you want to give it a shot yourself, I would warmly welcome a PR, if not we will put it on the roadmap
