### ISSUE TITLE
Could not create directory '/root/.ssh' (read-only file system) - GCP Provider

### ISSUE THREAD

**Issue by jontstaz** [loft-sh/devpod#494]
**What happened?**
When I try to create a workspace for my private git repository, I get the following error output. I am using Google Cloud as my provider:

```
[11:24:28] info Could not create directory '/root/.ssh' (Read-only file system).
[11:24:28] info Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).
[11:24:29] info git@github.com: Permission denied (publickey).
[11:24:29] info fatal: Could not read from remote repository.
[11:24:29] debug error creating ssh directory: mkdir /root/.ssh: read-only file system
```

**What did you expect to happen instead?**
I expect it to successfully copy over my SSH key and clone my repo into the workspace.

**How can we reproduce the bug?** (as minimally and precisely as possible)

Windows 11 running DevPod with GCP Provider

**Local Environment:**

* DevPod Version: 0.2.1
* Windows
* 64bit AMD CPU

**DevPod Provider:**

* Cloud Provider: google

**Anything else we need to know?**

**Comment by FabianKramm** [comment]
@jontstaz thanks a lot for creating this issue! I just tried to reproduce and it was working for me. Does it work through https clone?

**Comment by jontstaz** [comment]
No unfortunately it won't even let me attempt to create the workspace via https git link.

**Comment by FabianKramm** [comment]
@jontstaz can you post the log when you try this? Something like:
```
devpod up https://github.com/my-org/my-private-repo --provider gcloud
```
has worked for me.

**Comment by jume-dev** [comment]
Sadly, I have the same issue with the ssh git url, and I also get the same error "Read-only file system". Is this something I need to tackle in the provider configuration or rather in the devcontainer config?
