### ISSUE TITLE
Notify in-app when an update is available

### ISSUE THREAD

**Issue by mrsimonemms** [loft-sh/devpod#510]
**Is your feature request related to a problem?**
I don't know when updates are available until I go to GitHub

**Which solution do you suggest?**
A small notification in the app that says "an update is available" with a link to the relevant release page in GitHub.

I'd also suggest to have an option to disable these notifications in the settings.

Finally, if it's possible to tell how it was installed (eg, `.deb`, `.exe` etc) then there should be an option to go to the download link of the relevant file.

**Which alternative solutions exist?**

**Additional context**

**Comment by mrsimonemms** [comment]
Update: this does exist if you've installed with the AppImage. I'm using the `.deb` package for which it's not available.

**Comment by pascalbreuninger** [comment]
Ah sure, we don't have an updater for `.deb` builds right now because tauri doesn't support it. If you're fine with the plain download link on debian that shouldn't be a problem but full auto updates would require upstream changes

**Comment by pascalbreuninger** [comment]
We've decided to only support auto updates for the platforms [tauri](https://tauri.app/v1/guides/distribution/updater) supports it as it's overhead that doesn't need to be in this project. Closing as not planned for now. If there's community interest in picking this up let us know!
