### ISSUE TITLE
Lifecycle hooks not able to find dependencies installed in `features`

### ISSUE THREAD

**Issue by mrsimonemms** [loft-sh/devpod#522]
**What happened?**

When building an image with a lifecycle hook (`postStartCommand`) that uses something that's installed from the `features` (in this case, Golang), the lifecycle hook cannot find the `go` binary. What's curious is that the `feature` has been installed according to the logs.

---

```
21:57:27 debug Done setting up container
21:57:27 info exit status 1
21:57:27 info setup container
21:57:27 info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).runSingleContainer
21:57:27 info 	/home/runner/work/devpod/devpod/pkg/devcontainer/single.go:97
21:57:27 info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).Up
21:57:27 info 	/home/runner/work/devpod/devpod/pkg/devcontainer/run.go:130
21:57:27 info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).devPodUp
21:57:27 info 	/home/runner/work/devpod/devpod/cmd/agent/workspace/up.go:373
21:57:27 info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).up
21:57:27 info 	/home/runner/work/devpod/devpod/cmd/agent/workspace/up.go:167
21:57:27 info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).Run
21:57:27 info 	/home/runner/work/devpod/devpod/cmd/agent/workspace/up.go:101
21:57:27 info github.com/loft-sh/devpod/cmd/agent/workspace.NewUpCmd.func1
21:57:27 info 	/home/runner/work/devpod/devpod/cmd/agent/workspace/up.go:61
21:57:27 info github.com/spf13/cobra.(*Command).execute
21:57:27 info 	/home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:916
21:57:27 info github.com/spf13/cobra.(*Command).ExecuteC
21:57:27 info 	/home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:1044
21:57:27 info github.com/spf13/cobra.(*Command).Execute
21:57:27 info 	/home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:968
21:57:27 info github.com/loft-sh/devpod/cmd.Execute
21:57:27 info 	/home/runner/work/devpod/devpod/cmd/root.go:89
21:57:27 info main.main
21:57:27 info 	/home/runner/work/devpod/devpod/main.go:8
21:57:27 info runtime.main
21:57:27 info 	/opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250
21:57:27 info runtime.goexit
21:57:27 info 	/opt/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_amd64.s:1594
21:57:27 info devcontainer up
21:57:27 info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).Run
21:57:27 info 	/home/runner/work/devpod/devpod/cmd/agent/workspace/up.go:103
21:57:27 info github.com/loft-sh/devpod/cmd/agent/workspace.NewUpCmd.func1
21:57:27 info 	/home/runner/work/devpod/devpod/cmd/agent/workspace/up.go:61
21:57:27 info github.com/spf13/cobra.(*Command).execute
21:57:27 info 	/home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:916
21:57:27 info github.com/spf13/cobra.(*Command).ExecuteC
21:57:27 info 	/home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:1044
21:57:27 info github.com/spf13/cobra.(*Command).Execute
21:57:27 info 	/home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:968
21:57:27 info github.com/loft-sh/devpod/cmd.Execute
21:57:27 info 	/home/runner/work/devpod/devpod/cmd/root.go:89
21:57:27 info main.main
21:57:27 info 	/home/runner/work/devpod/devpod/main.go:8
21:57:27 info runtime.main
21:57:27 info 	/opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250
21:57:27 info runtime.goexit
21:57:27 info 	/opt/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_amd64.s:1594
```

**What did you expect to happen instead?**

It should be able to install the lifecycle hook successfully. This is what happens if you run the official `devcontainer` package.

**How can we reproduce the bug?** (as minimally and precisely as possible)

My `devcontainer.json`:

```
{
  "name": "Test",
  "image": "mcr.microsoft.com/vscode/devcontainers/base:ubuntu",
  "features": {
    "ghcr.io/devcontainers/features/go:1": {}
  },
  "postStartCommand": "go install github.com/spf13/cobra-cli@latest"
}
```

**Local Environment:**

* DevPod Version: `0.2.1`
* Operating System: linux
* ARCH of the OS: AMD64

**DevPod Provider:**

* Cloud Provider: hetzner
* Kubernetes Provider: Not installed
* Local/remote provider: docker
* Custom provider: provide imported `provider.yaml` config file

**Anything else we need to know?**

**Comment by 89luca89** [comment]
Hi @mrsimonemms can you verify a thing?

Is this trying to perform `go` with arguments `install`, `github.com/spf13/cobra-cli@latest` or like a single command called `go install github.com/spf13/cobra-cli@latest`? This maybe can tell us why it doesn't find the program

If that's the case It should be an easy enough bug to resolve

Thanks!

**Comment by mrsimonemms** [comment]
@89luca89 I think it's the former. I've tried it as both `"go install github.com/spf13/cobra-cli@latest"` and `["go", "install", "github.com/spf13/cobra-cli@latest"]` and I get the same problem. I have also tried `which go` and it comes back with the valid location for `go`, which is strange.

I also get the same with pre-commit - I used the Go example as it's easier to set up as no additional files are required. However, this is an example I've used to demo it:

## `.devcontainer/devcontainer.json`

```json
{
  "name": "Pre-commit",
  "image": "mcr.microsoft.com/vscode/devcontainers/base:ubuntu",
  "features": {
    "ghcr.io/devcontainers-contrib/features/pre-commit:2": {},
    "ghcr.io/devcontainers/features/python:1": {}
  },
  "postStartCommand": "pre-commit install --install-hooks"
}
```

## `.pre-commit-config.yaml`

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
```

**Comment by mrsimonemms** [comment]
This actually seems to be a bigger issue and more related to how the `features` are built. If I remove the `postStartCommand` and SSH into the VM, it doesn't have `go` installed  - eg, if I run `go version` I get `bash: go: command not found`.

However, if I change the `remoteUser` to `root`, then it all works fine. So I'm guessing it's that the builder isn't given the correct permissions.

Happy to help on this issue if necessary.

**Comment by neogopher** [comment]
> If I remove the `postStartCommand` and SSH into the VM,

After you do this, can you see the go binary at '/usr/local/go/bin/go', but the environment variable $PATH does not include '/usr/local/go/bin:/go/bin'. If so, its just that go is installed and available but the $PATH variable is not set correctly.
If you update your postStartCommand as `"postStartCommand": "/usr/local/go/bin/go install github.com/spf13/cobra-cli@latest"`, you will see that it works. 

We will need to check why the $PATH variable doesn't contain go paths already for devpod.

**Comment by mrsimonemms** [comment]
Aaaaah, you're on to something there. I can confirm that `go` is installed to `/usr/local/go/bin`. So, that looks as though the `feature` is correctly installed but not updating the `PATH` envvar.

Hopefully, that'll be easier to solve

**Comment by mrsimonemms** [comment]
So, from looking at it, I've got a sneaking suspicion that the `containerEnv` in the [devcontainer-feature.json](https://github.com/devcontainers/features/blob/7fcec6e7c9dd587b24096597367ef42e4a37465b/src/go/devcontainer-feature.json#L33,L37) isn't being picked up.

Does anyone know whereabouts this is (or should be) applied in the codebase?

**Comment by neogopher** [comment]
Hi @mrsimonemms , I will be pushing a PR shortly to fix this. Will keep you posted.

**Comment by mrsimonemms** [comment]
Great stuff. If you want me to test it out, let me know

**Comment by mrsimonemms** [comment]
It works perfectly in the `go` example, but [the pre-commit example](https://github.com/loft-sh/devpod/issues/522#issuecomment-1637627410) is still failing - I think there might be two separate issues at play, so I'll create a new issue
