### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by awfuel** [loft-sh/devpod#535]
**Is your feature request related to a problem?**
all white apps saturate my retinas and hurt my eyes.

**Which solution do you suggest?**
dark mode toggle for users.

**Comment by pascalbreuninger** [comment]
@awfuel closing this as v0.3 should have a dark mode that syncs with your os mode

**Comment by hex-developer** [comment]
@pascalbreuninger I have dark mode enabled on my system, but DevPod shows in light mode. Is there a way to enable it?

**Comment by pascalbreuninger** [comment]
@hex-developer we disabled it until we have the time to put a bit more effort into it 😅

**Comment by hex-developer** [comment]
Oh ok 😂. What part of the code should I change to get it working properly? I don't mind building it myself!

**Comment by pascalbreuninger** [comment]
Set [this](https://github.com/loft-sh/devpod/blob/4117ebb49301abaf9e518a8f7d41820c698ca8a1/desktop/src/Theme/theme.ts#L89C31-L89C31) to `true` :D

**Comment by hex-developer** [comment]
Got it, thanks!
