### ISSUE TITLE
xdg-open / open from Browser does not work

### ISSUE THREAD

**Issue by Pro** [loft-sh/devpod#536]
**What happened?**

I installed DevPod via .deb on Ubuntu 22.04 and tried to open this URL:
[https://devpod.sh/open#https://github.com/microsoft/vscode-remote-try-cpp](https://devpod.sh/open#https://github.com/microsoft/vscode-remote-try-cpp)

Then, tadaaa, nothing happens.

**What did you expect to happen instead?**

DevPod UI should open and automatically launch VSCode

**How can we reproduce the bug?** (as minimally and precisely as possible)

Install DevPod with .deb on Ubuntu 22.04 and open previously mentioned URL

**Local Environment:**

* DevPod Version: 0.3.0
* Operating System: linux
* ARCH of the OS: AMD64

**Anything else we need to know?**

Syslog shows this line:

> gio: devpod://open?source=https://github.com/microsoft/vscode-remote-try-cpp: The specified location is not supported

Looks like the corresponding mime type is not properly registered.

**Comment by pascalbreuninger** [comment]
Hi @Pro, first up: congratulations on the github username, wow.
Thanks for opening the issue, we'll look into it
