### ISSUE TITLE
Fleet IDE makes workspace publicly available

### ISSUE THREAD

**Issue by marklarr-gfm** [loft-sh/devpod#539]
**What happened?**  
Fleet IDE will publish the workspace to a publicly available jetbrains relay URL

**What did you expect to happen instead?**  
Until Fleet supports the `noPublish` option (see [here](https://www.jetbrains.com/help/fleet/install-on-a-remote-machine.html)), there should probably be some sort of warning or confirmation that lets the user know that using Fleet is insecure and will publish their workspace to a publicly available URL with no authentication.

**Comment by FabianKramm** [comment]
@marklarr-gfm thanks for creating this issue, yes we can add a warning to that
