### ISSUE TITLE
rebuild existing workspace from remote git to pull new changes

### ISSUE THREAD

**Issue by danielehq** [loft-sh/devpod#540]
**Is your feature request related to a problem?**
I would like to rebuild my workspace with a click on an existing workspace that will pull new changes i pushed to my git repository.

**Which solution do you suggest?**
A option to rebuild my worksapce from remote git.

**Which alternative solutions exist?**

**Additional context**

**Comment by pascalbreuninger** [comment]
it's currently not possible but an interesting idea.  
One drawback that I'd be wary of is that you'd possibly interrupt your developers workflows if you rebuild whenever you push to the git repo
