### ISSUE TITLE
Poor File System Performance

### ISSUE THREAD

**Issue by bobpaige** [loft-sh/devpod#549]
**What happened?**
Simple terminal operations like "git status" take over a minute to complete.
Building the Java project takes 15-20 minutes.

**What did you expect to happen instead?**
"git status" should complete in 2-3s.
Building (just compiling, not tests) should take 1-3 minutes.

**How can we reproduce the bug?** (as minimally and precisely as possible)

Create a project with > source 2,000 files in it and do any git operations. The sample Java project has only 54 source files so runs very quickly.

devcontainer.json was copied directly from the vscode-remote-try-java project without modification:

```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/java
{
	"name": "Java",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/java:0-17",

	"features": {
		"ghcr.io/devcontainers/features/java:1": {
			"version": "none",
			"installMaven": "true",
			"mavenVersion": "3.8.6",
			"installGradle": "false"
		}
	},

	// Configure tool-specific properties.
	"customizations": {
		// Configure properties specific to VS Code.
		"vscode": {
			"settings": {},
			"extensions": [
				"streetsidesoftware.code-spell-checker"
			]
		}
	}

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "java -version",

	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}
```

**Local Environment:**

* DevPod Version: 0.3.0
* Operating System: windows
* ARCH of the OS: AMD64

**DevPod Provider:**

* Local/remote provider: docker

**Anything else we need to know?**
The problem seems to be that the project directory is mounted from the host file system. If I clone the project directory into `~/workspaces/myproject` then git operations are near instant and clean build operations are a reasonable 1m.
OTOH, if the project is in `/workspaces/myproject` (which is mounted from the host) then the same build takes 18m.

In both cases, the build command was `gradlew clean bootjar`.
The timings above were for the second build. The first one took longer because it had to download Java dependencies (this is a Gradle project).

I tried the CLI tests from within VS Code and IntelliJ (same devpod on both cases, just launched separately with different IDEs).

Thus, my conclusion is the difference in performance is the file system.

**Comment by pascalbreuninger** [comment]
Hi @bobpaige, thanks for opening the issue, that looks like a frustrating problem indeed. Are you using docker with the WSL backend? If so, the conversion of the windows fs to the unix fs seems to be causing the slowdown. 
One mitigation you could try is to have your source code in WSL as well, eliminating the need for conversion.

**Comment by bobpaige** [comment]
Excellent point. Yes, I'm using WSL2, and the code seems to be mounted from
the windows FS.

Is there a way with DevPod to have it load the code into the image instead
of mounting it from windows?

**Comment by pascalbreuninger** [comment]
yeah we could add such an option but it would remove the syncing behaviour you get from the mount, so you'd have to manage the code as if it were remote

**Comment by bobpaige** [comment]
Is the performance hit specific to Docker on Windows? If I hosted this
somewhere else, would the problem persist?

**Comment by pascalbreuninger** [comment]
Yes, it's specific to docker on windows with the WSL backend and a mount from the windows host system as far as I know. If you'd use a different provider that doesn't sync back to your windows folder it should be fine 👍

**Comment by bobpaige** [comment]
An option to locate the sources within the docker image would be great. I understand we lose the syncing behavior, but if we do this right, users can just recreate the devpod from the repo again, right?
We can manually clone the repo within the IntelliJ terminal within the `/home/vscode/` subdirectory. Is there some way to automate that step in the devcontainer.json?

**Comment by pascalbreuninger** [comment]
Oh yeah, interesting idea. You could use the `postCreateCommand` lifecycle for the initial setup or 'postStartCommand' if you want to re-sync every time you start the workspace. 
Not sure if JetBrains has a cli that automatically lets you switch the workspace to the new cloned destination, so that might still require manual effort

**Comment by bobpaige** [comment]
I'm still learning JetBrains, but apparently when the client is started, the `workspace` context is set and can't be changed. I can manually add another "module" with code located elsewhere (like in the home directory) which I've done to show I can get good performance out of this setup.
Then there's the issue of setting up my `~/.ssh/` keys so I can clone and push to repos, etc.
Still a work in progress, but showing promise 👍 

Thanks for your help.
