### ISSUE TITLE
Minimal alpine container with VSCode fails with missing bash

### ISSUE THREAD

**Issue by luislavena** [loft-sh/devpod#557]
**What happened?**

A simple Alpine Linux container fails to start with DevPod, where the same setup works with VSCode Containers functionality.

**What did you expect to happen instead?**

VSCode should complete loading and provide a working Alpine container

**How can we reproduce the bug?** (as minimally and precisely as possible)

My `devcontainer.json`:

```
{
    "name": "test-alpine-devcontainer",
    "image": "alpine:3.18.2"
}
```

Then `devpod up .` loads and VSCode halts with error about missing bash. Terminal within VSCode shows:

```
debug1: Server host key: ssh-rsa SHA256:fxukPCsxNyesGoGkAUOl0nKNLZMt9M9wXtZXNfXtki4
Warning: Permanently added 'test-devcontainer-alpine.devpod' (RSA) to the list of known hosts.
Authenticated to test-devcontainer-alpine.devpod (via proxy) using "none".
ready: 1afd7c2e8a15
Linux 6.2.6-76060206-generic #202303130630~1689015125~22.04~ab2190e SMP PREEMPT_DYNAMIC Mon J
bash version: 
ash: bash: not found
bash version: 
ash: syntax error: unexpected "(" (expecting "then")
Transferred: sent 17956, received 2064 bytes, in 0.1 seconds
Bytes per second: sent 290066.3, received 33342.4
local-server-1> ssh child died, shutting down

[02:10:28.470] Resolver error: Error: bash not found
	at m.Create (/home/luis/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:584145)
	at /home/luis/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:582093
	at t.handleInstallOutput (/home/luis/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:582627)
	at Object.e [as tryInstallWithLocalServer] (/home/luis/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:623656)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/luis/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:643708
	at async t.withShowDetailsEvent (/home/luis/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:647428)
	at async /home/luis/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:622128
	at async C (/home/luis/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:618634)
	at async t.resolveWithLocalServer (/home/luis/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:621743)
	at async t.resolve (/home/luis/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:645036)
	at async /home/luis/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:720916
[02:10:28.477] ------
```

**Local Environment:**

* DevPod Version: `v0.3.0`
* Operating System: linux (PopOS 22.04, Ubuntu Jammy)
* ARCH of the OS: AMD64

**DevPod Provider:**

* Local/remote provider: docker

**Anything else we need to know?**

Just wanted to thank you for releasing devpod!
❤️ ❤️ ❤️

**Comment by pascalbreuninger** [comment]
Hi @luislavena , thank you for the kind feedback. 
Do you absolutely need this to run on the standalone alpine image? 
If not I'd suggest to use [microsofts base image for alpine based devcontainers](https://github.com/devcontainers/images/tree/main/src/base-alpine), that should work

**Comment by luislavena** [comment]
Hello @pascalbreuninger, thank you for taking time to answer.

The Microsoft base image you linked is pretty much the same as using Alpine directly, at least the one within `.devcontainer` directory in the Dockerfile:

https://github.com/devcontainers/images/blob/main/src/base-alpine/.devcontainer/Dockerfile

And that works with VSCode Dev Container without any modificaton.

If you mean the published image (Eg. `mcr.microsoft.com/devcontainers/base:alpine-3.18`), that one is considerably bigger than what others were using (300MB vs ~7MB uncompressed image) and might be a problem for certain apps that were using above approach with VSCode Dev Container.

I wonder what VSCode Dev Container is doing differently for validating that `bash` is not there 🤔

**Comment by pascalbreuninger** [comment]
I spent some time investigating this issue and for the time being I can't offer a good solution other than using the devcontainer base image unfortunately.
The problem is that we currently need to rely on the `remote-ssh` extension to connect to the container and it errors out on plain alpine as you mentioned above. 
From what I can tell the `Dev Containers` doesn't use ssh to connect to the container. Now, we _might_ be able to use this extension for docker based workspaces but this won't work for remote providers (k8s, aws, gcp etc)

**Comment by luislavena** [comment]
Thank you again for taking the time to investigate it @pascalbreuninger and the detailed response. 

Indeed is hard to replicate or make this portable to multiple scenarios. Naive question, but DevPod is injecting an SSH server inside the container and then connecting that with VSCode using `remote-ssh` extension, correct?

Perhaps is that SSH server not detecting what could be the default shell to be used? 

Anyway, nothing critical, wanted to see if this is a viable alternative to certain applications that are using GitPod or Codespaces and that were working with Alpine or similar but couldn't manage to get to work with DevPod, your explanation could be why.

Once again, thank you for your response, your time and for releasing DevPod open source!
❤️ ❤️ ❤️

**Comment by pascalbreuninger** [comment]
> Indeed is hard to replicate or make this portable to multiple scenarios. Naive question, but DevPod is injecting an SSH server inside the container and then connecting that with VSCode using remote-ssh extension, correct?

Yes pretty much. I'd really like to patch this into the `remote-ssh` extensions, alas, it's not open source afaik.
We'd love to make DevPod your go-to choice, so let's add this fix to the roadmap and see if we can come up with a solution further down the road

**Comment by FabianKramm** [comment]
Hey @luislavena! If you run the following either in the container itself after creating it or in your Dockerfile, vscode can connect to it:
```
apk upgrade
apk add bash build-base gcompat git
```
