### ISSUE TITLE
Please provide the information you collect if any in the security policy

### ISSUE THREAD

**Issue by astrolemonade** [loft-sh/devpod#559]
Please provide the information you collect if any in the security policy

**Comment by FabianKramm** [comment]
Hey @astrolemonade! Thanks for creating this issue, we have a separate docs page for that [here](https://devpod.sh/docs/telemetry#what-are-we-collecting-and-how). You can disable telemetry completely as well via: `devpod context set-options -o TELEMETRY=false`
