### ISSUE TITLE
Can't pull my private github repository

### ISSUE THREAD

**Issue by Xitod** [loft-sh/devpod#564]
**What happened?**
I want to test devpod.

When I try to devpod up with my private github, I've got an error when cloning repository.

**What did you expect to happen instead?**
The repository clones well and the workspace launches in my IDE

**How can we reproduce the bug?** (as minimally and precisely as possible)

Try to devpod up test --source [git:git@github.com](mailto:git:git@github.com):private-repository.git

**Local Environment:**

* DevPod Version: 0.2.1
* Operating System: mac
* ARCH of the OS: silicon

**DevPod Provider:**

* Cloud Provider: aws
* Local/remote provider: ssh

**Anything else we need to know?**
After the error, when I run devpod ssh test, devpod will create a dev container in my instance. I am able to access it in ssh. Then when I do "ssh -T [git@github.com](mailto:git@github.com)", I can authenticate to github. So all my credentials is set and it's working ->
ssh-add -l shows me the good ssh key.

Why can't I clone my repo on the first try ?

**Comment by Xitod** [comment]
Some logs :
```sh
00:20:09 info Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
00:20:09 info git@github.com: Permission denied (publickey).
00:20:10 info exit status 128
00:20:10 info error cloning repository
00:20:10 info github.com/loft-sh/devpod/cmd/agent/workspace.CloneRepository
...
00:20:10 info error parsing workspace info: rerun as root: exit status 1
00:20:10 debug done exec
00:20:10 debug done inject
00:20:10 debug done injecting
00:20:10 debug Done InjectAgentAndExecute
00:20:10 debug Done executing up command
00:20:10 debug Done creating devcontainer
00:20:10 fatal executing agent command: agent error: Rerun as root: /var/lib/toolbox/devpod agent workspace up ...
...
exit status 128
error cloning repository
```

**Comment by 89luca89** [comment]
Hi @Xitod 

I've tried using a private repo (`git@github.com:89luca89/test.git`) with ssh
And it worked:

![image](https://github.com/loft-sh/devpod/assets/598882/5c4aee28-34e8-44f4-8abb-11cd1cf2496a)

The error message might be a bit unclear, as it's not evident that the error was not fatal and it recovered (by cloning locally and uploading the repo)

**Comment by Xitod** [comment]
Could you tell me your provider configuration ? 

I am thinking of a networking issue.

**Comment by 89luca89** [comment]
> Could you tell me your provider configuration ?
> 
> I am thinking of a networking issue.

I'm using the `aws` provider, all stock just specified my login/token credential stuff

**Comment by Xitod** [comment]
Ok I tried again today and now it works. I haven't changed anything... I kept my same AWS provider configuration, with an ssh configuration.

The only difference is that I defined an ssh agent configuration with the command
```sh
ssh-add /path/to/my/private/key
```

Could you add in the documentation the minimum security group configurations please?
