### ISSUE TITLE
Jetbrains IDE Gateway question

### ISSUE THREAD

**Issue by xgalaxy** [loft-sh/devpod#570]
Hello,

Supposedly if you have, for example, GoLand installed it, it comes with the Gateway preinstalled. 
However, when I launched a DevPod workspace it forces me to install the IDE Gateway separately.
Is there a way to avoid having to install the IDE Gateway separately from the GoLand install?

Thanks.

**Comment by pascalbreuninger** [comment]
Hi @xgalaxy, it's an understandable request but we're kind of blocked by jetbrains' custom protocol integrations here. 
From what I can tell they only provide a reliabe cli for gateway, there's a [lengthy discussion](https://youtrack.jetbrains.com/issue/IDEA-65879) about IDE-level custom protocols over at youtrack

**Comment by xgalaxy** [comment]
Thanks.
