### ISSUE TITLE
DevPod UI keeps spinning up new instances on x86 Mac Ventura

### ISSUE THREAD

**Issue by jmlennon** [loft-sh/devpod#578]
**What happened?**

* Installed this DMG on my x86 Mac:
  [https://github.com/loft-sh/devpod/releases/download/v0.3.3/DevPod_macos_x64.dmg](https://github.com/loft-sh/devpod/releases/download/v0.3.3/DevPod_macos_x64.dmg)
* Copied DevPod.app into \~/Applications/
* Ran \~/Applications/DevPod.app/Contents/MacOS/DevPod from my Terminal window
* DevPod UI comes up. Then another instance a few seconds later. After 20 seconds or so, there were 5 UI instances.
* I didn't click any buttons - didn't try to create a workspace, etc.
* Tried to kill these DevPod UIs via command-Q - they all hung and I had to force kill them in Activity monitor.
* Deleted the application & reinstalled - same problem

**What did you expect to happen instead?**
DevPod UI comes up & I try one of the demo apps.

**How can we reproduce the bug?** (as minimally and precisely as possible)

* Follow above steps

My `devcontainer.json`:
None

**Local Environment:**

* DevPod Version: v0.3.3
* Operating System: mac
* ARCH of the OS:  i386

**DevPod Provider:**

* Cloud Provider: none (AFAIK)
* Kubernetes Provider: N/A
* Local/remote provider: N/A
* Custom provider: None

**Anything else we need to know?**
Looks cool. I hope to try it someday :-)

**Comment by pascalbreuninger** [comment]
Hi @jmlennon, sounds like a strange issue. Does it work if you don't copy it to `~/Applications` and start the app by clicking on the icon or using spotlight instead of from the terminal?

**Comment by jmlennon** [comment]
Hi Pascal.

Thanks for those suggestions. I was eventually able to start the
application and run the Python demo app by:

   - Removing the local DevPod copy I had just installed in ~/Applications/
   - Running DevPod directly from the downloaded DMG, i.e., from the disk
   image mounted on /Volumes/DevPod/.

Very odd behaviour. Probably something to do with IT's obsessive need to
lock down our laptops. :-)

I ran "diff -r" on the files in /Volumes/DevPod/ vs ~/Applications/DevPod
just in case there was file corruption due to the copying - no diffs.

So I would tend to say this is a problem with my local environment. Would
you agree?

Thanks!  -Matt

**Comment by pascalbreuninger** [comment]
It's a pretty uncommon problem, that's why I'd be very interested in a way to repro it. Haven't successfully done so on my setup so any detail is welcome. 
It's crazy to me you have to run it from the dmg value directly, sorry

**Comment by pascalbreuninger** [comment]
Closing this for the time being

**Comment by davidpp** [comment]
I have the same issue, tried to look in my console.log app, couldn't find anything that would help though.

**Comment by davidpp** [comment]
![CleanShot 2023-10-20 at 10 57 06](https://github.com/loft-sh/devpod/assets/30426/41ef92f1-322e-41f3-ae66-f1b4fd7e0bb0)
