### ISSUE TITLE
Request: sync gpg signing keys in addition to git & docker credentials

### ISSUE THREAD

**Issue by srudolph-credera** [loft-sh/devpod#580]
For projects that utilize commit signing ([https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work)), it would be really handy to have GPG signing keys already available in the workspace.

**Is your feature request related to a problem?**

No

**Which solution do you suggest?**

Coder appears to have this option ([https://coder.com/docs/v2/latest/cli/ssh#-g---forward-gpg](https://coder.com/docs/v2/latest/cli/ssh#-g---forward-gpg)) and appears to implement it by first uploading GPG keys and then forwarding the GPG Agent: [https://github.com/coder/coder/blob/af036b440bd776f5fe57e0ddea7fc0c0596ffff7/cli/ssh.go#L297C8-L297C8](https://github.com/coder/coder/blob/af036b440bd776f5fe57e0ddea7fc0c0596ffff7/cli/ssh.go#L297C8-L297C8).

**Which alternative solutions exist?**

It looks like it may be possible to forward the GPG Agent via SSH config:
[https://unix.stackexchange.com/questions/656738/how-to-forward-gpg-agent-from-host-to-docker-container-and-reuse-cached-passphra](https://unix.stackexchange.com/questions/656738/how-to-forward-gpg-agent-from-host-to-docker-container-and-reuse-cached-passphra).

**Additional context**

**Comment by FabianKramm** [comment]
@srudolph-credera thanks a lot for the issue! That sounds like a great idea, we'll put that on the roadmap
