### ISSUE TITLE
Failed to save '.devcontainer.json': Unable to write file 'vscode-remote://ssh-remote... (NoPermissions (FileSystemError)

### ISSUE THREAD

**Issue by okbrown** [loft-sh/devpod#583]
**What happened?**
I get file permissions issues when making changes to any of the files in VSCode

**What did you expect to happen instead?**
I expect it to work!

**How can we reproduce the bug?** (as minimally and precisely as possible)
Not sure
My `devcontainer.json`:

```
{"image":"mcr.microsoft.com/devcontainers/javascript-node","build":{}}
```

**Local Environment:**

* DevPod Version: \[use `devpod version`\]
* Operating System: mac
* ARCH of the OS: INTEL64

**DevPod Provider:**

* Local/remote provider: docker

**Anything else we need to know?**
its a basic Nodejs app, but i noticed in order to install dependencies I have to run with sudo e.g. `sudo npm install`
I have missed a step with this process?

**Comment by FabianKramm** [comment]
@okbrown thanks for creating this issue! Mhh strange, that should work, what error message do you get exactly when trying to do a change?

**Comment by neogopher** [comment]
Hi @okbrown ,
Are you still getting this issue. If so, can you share any error logs which you are seeing.
