### ISSUE TITLE
DevPod branch regex doesn't allow for underscores in branch name

### ISSUE THREAD

**Issue by marklarr-gfm** [loft-sh/devpod#600]
**`my_branch` with an underscore fails:**
```
$ devpod up https://github.com/my/repo@my_branch

14:19:28 error Try using the --debug flag to see a more verbose output
14:19:28 fatal https://github.com/my/repo@my_branch is neither a local folder, git repository or docker image
```

**`my-branch` with a hyphen does not fail:**
```$ devpod up https://github.com/my/repo@my-branch```

**solution:**
Need to add underscore as a possible character for branches to the end of this regex here:
https://github.com/loft-sh/devpod/blob/main/pkg/git/git.go#L17

**Comment by neogopher** [comment]
Hi @marklarr-gfm :wave: ,
Thanks for creating this issue. :slightly_smiling_face: I have raised a PR for the fix.
