### ISSUE TITLE
CLI build command should take the prebuildRepository from devcontainer.json file

### ISSUE THREAD

**Issue by Pro** [loft-sh/devpod#605]
**Is your feature request related to a problem?**  

We are using DevPod CLI to pre-build workspace images in CI.
Typically one can configure the `prebuildRepository` in the devcontainer.json file via:

```json
{
    // ...
    "customizations": {
        "devpod": {
            "prebuildRepository": "artifactory.ar.int:5011/workspaces/dev/agile-core/programming"
        }
    }
}
```

Since `--repository` is a mandatory argument to `devpod-cli build`, there is no way to automatically take that value, and we need to first get the value from the json file to pass it as argument.

**Which solution do you suggest?**  

`--repository` should be an optional argument for the `build` command. And only if `prebuildRepository` is not configured, the command should fail.

**Which alternative solutions exist?**  

Currently we are working around this by first parsing the json.

The `sed` command is removing all comments. VSCode ignores them, but jq does not, since json actually does not have comments support.

```shell
prebuild_repo=$(sed '/^[[:blank:]]*#/d;s/\/\/.*//' .devcontainer/devcontainer.json | jq -r ".customizations.devpod.prebuildRepository")
devpod-cli build $PWD --repository $prebuild_repo --provider docker
```

**Comment by pascalbreuninger** [comment]
Hey @Pro, fair point. Created a PR to fix this, will be released in the next version. Thank you for reporting
