### ISSUE TITLE
Devpod cannot launch workspace on first attempt in Kubernetes provider

### ISSUE THREAD

**Issue by cakriwut** [loft-sh/devpod#608]
**What happened?**  
I run devpod using sample repository and Kubernetest providers `devpod up github.com/microsoft/vscode-remote-try-node --ide vscode --debug` . 
It always giving me error and unable to launch, in following step   
```bash
Run command: kubectl --namespace {NAMESPACE} --context {CONTEXT} cp -c devpod {LOCAL WORKSPACE}\vscode-remote-try-node\content/. devpod-vscode-remote-try-node-default-f1d-9398d:/workspaces/vscode-remote-try-node
```
I have to run the same command `devpod up github.com/microsoft/vscode-remote-try-node --ide vscode --debug`  in order to successfully launch devpod.
In short, it seems the failed command was initiated before the pod ready to receive instruction. 

**What did you expect to happen instead?**  
`devpod up` should be able to launch the workspace in Kubernetes remote on the first attempt.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. Enable Kubernetes provider. (use remote Kubernetes)
2. Run `devpod up github.com/microsoft/vscode-remote-try-node --ide vscode --debug`

**Local Environment:**  
- DevPod Version:  v0.3.4
- Operating System: windows 
- ARCH of the OS:  i386 

**DevPod Provider:**  
- Cloud Provider: google | aws | azure | digitalOcean
- Kubernetes Provider: [use `kubectl version`]
```json
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:16:51Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"94c50547e633f1db5d4c56b2b305670e14987d59", GitTreeState:"clean", BuildDate:"2023-06-12T18:46:30Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**

**Comment by pascalbreuninger** [comment]
Hi @cakriwut , thanks for opening the issue. What exactly is the error your receiving on the first try?

**Comment by alexandradragodan** [comment]
Hey, @cakriwut 
Do you still happen to encounter this issue? If so, could you please provide us with the error message you're getting?

**Comment by FabianKramm** [comment]
We close this for know, feel free to reopen if still an issue
