### ISSUE TITLE
Cannot set default shell for ssh access

### ISSUE THREAD

**Issue by kevindurb** [loft-sh/devpod#614]
**What happened?**  
I am trying to setup a devpod that will drop into zsh by default rather than bash. Ive tried setting the login shell for my user via my dockerfile, setting the entrypoint, setting the SHELL env var and various random .devcontainer.json snippets ive found online to get zsh by default but nothing seems to work.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My dockerfile: https://github.com/kevindurb/.dotfiles/blob/main/ci/Containerfile
My *`devcontainer.json`*:
```
{
  "image": "ghcr.io/kevindurb/dev:latest",
  "build": {},
  "settings": {
    "terminal.integrated.defaultProfile.linux": "zsh",
    "terminal.integrated.profiles.linux": {
      "zsh": {
        "path": "zsh"
      }
    },
    "terminal.integrated.defaultProfile.osx": "zsh",
    "terminal.integrated.profiles.osx": {
      "zsh": {
        "path": "zsh"
      }
    }
  }
}
```

**Local Environment:**  
- DevPod Version: v0.3.3
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Kubernetes Provider:
```
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.4+k3s1
```

**Comment by kevindurb** [comment]
I guess i should also specify that im using ssh, not vscode or any other editor

**Comment by aacebedo** [comment]
@kevindurb did you find a solution? I have the same issue.

**Comment by 89luca89** [comment]
Hi @kevindurb did you try using `chsh` to change the default shell for the user?

As you can see here: https://github.com/loft-sh/devpod/blob/5aff1cf6d6e9e1a61961a4cfbe2c3a2c72f5afbf/pkg/ssh/server/ssh.go#L106

Devpod just gets that info from the /etc/passwd

**Comment by frangio** [comment]
@89luca89 The following line in `devcontainer.json` did not change the shell that starts on `devpod ssh`:

```
  "onCreateCommand": "sudo chsh -s /usr/bin/fish $USER"
```

**Comment by 89luca89** [comment]
@frangio after you enter the container with `devpod ssh` what do you get from ` getent passwd $USER | cut -d':' -f7`?

**Comment by frangio** [comment]
```
$ getent passwd $USER | cut -d':' -f7
/usr/bin/fish
```
