### ISSUE TITLE
Provide option to hide available providers and available default IDEs

### ISSUE THREAD

**Issue by haiwu** [loft-sh/devpod#615]
**Is your feature request related to a problem?**  
In a controlled environment, only want to provide one or 2 providers for users to pick, same for available default IDEs. Hard to support too many available providers/default IDE options. And don't want to confuse users with too many UI options. 

**Which solution do you suggest?**  
Provide UI option/configuration option to hide available providers and available default IDEs for Devpod UI application. 

**Which alternative solutions exist?**  
N/A

**Additional context**

**Comment by pascalbreuninger** [comment]
Hi @haiwu, sounds like a reasonable request to me, although I'm wondering if this is best suited in the open source project as every user would need to disable the defaults on their machine individually. This might be more fitting in DevPod Pro where admins can take control over what their users see / can access

**Comment by pascalbreuninger** [comment]
@haiwu We don't have a makefile or anything like that right now, just the documentation on [setting up your enviroment](https://github.com/loft-sh/devpod/blob/main/desktop/README.md#development)
Alternativly you could use devpod to develop devpod :) `devpod up https://github.com/loft-sh/devpod`.
After that, run `cd desktop && yarn && yarn desktop:build:dev` and you'll find the output it `desktop/src-tauri/target/release/bundle`.
I'll also update the desktop readme for future reference
