### ISSUE TITLE
Couldn't load workspace <name>: Invalid character '\x00' looking for beginning of value

### ISSUE THREAD

**Issue by pakdev** [loft-sh/devpod#617]
My workspace disappeared. When I type `devpod list`, I get the following message:

```
devpod list
15:52:04 warn Couldn't load workspace test: invalid character '\x00' looking for beginning of value

              NAME           |                          SOURCE                           | MACHINE | PROVIDER |  IDE   | LAST USED |     AGE
  ---------------------------+-----------------------------------------------------------+---------+----------+--------+-----------+--------------
    vscode-remote-try-python | git:https://github.com/microsoft/vscode-remote-try-python |         | docker   | vscode | 195h7m53s | 2166h10m51s
```

I expect my workspace to be listed.

I'm not sure how to reproduce this bug.

My *`devcontainer.json`*:
```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/python
{
	"name": "Python 3",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/python:0-3.11",

	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},

	// Configure tool-specific properties.
	"customizations": {
		// Configure properties specific to VS Code.
		"vscode": {
			"settings": {},
			"extensions": [
				"streetsidesoftware.code-spell-checker"
			]
		}
	},
	
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [9000],

	// Use 'portsAttributes' to set default properties for specific forwarded ports. 
	// More info: https://containers.dev/implementors/json_reference/#port-attributes
	"portsAttributes": {
		"9000": {
			"label": "Hello Remote World",
			"onAutoForward": "notify"
		}
	},

	// Use 'postCreateCommand' to run commands after the container is created.
	"postCreateCommand": "pip3 install -r requirements.txt"

	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}
```

**Local Environment:**  
- DevPod Version: v0.3.4
- Operating System: windows
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: docker

**Comment by pascalbreuninger** [comment]
Hi @pakdev, thanks for opening the issue. The warning mentions a workspace called `test`, is the `devcontainer.json` you provided the one from `vscode-remote-try-python` or the one from `test`?

Aside from that, other people also experienced this problem on docker, i.e. https://github.com/docker/for-win/issues/12561. 
Are you able to list the image and container when using the docker cli directly?

**Comment by pakdev** [comment]
Hey @pascalbreuninger, the devcontainer.json is from the test workspace, although they are exactly the same (my project happens to be a Python flask project).

I'm able to list the image/container via the Docker CLI, and I can open it as a devcontainer in VSCode to continue working:

![image](https://github.com/loft-sh/devpod/assets/1248927/e50cec79-10e7-4028-a04c-24b2051856a0)

I checked out the issue you linked, but I'm not experiencing that problem:

```
> docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT
      KUBERNETES ENDPOINT   ORCHESTRATOR
default *           moby                Current DOCKER_HOST based configuration   npipe:////./pipe/docker_engine

desktop-linux       moby                Docker Desktop                            npipe:////./pipe/dockerDesktopLinuxEngine
```

My meta.json file in ~/.docker/contexts/** contains:

```
> cat .\meta.json
{"Name":"desktop-linux","Metadata":{"Description":"Docker Desktop"},"Endpoints":{"docker":{"Host":"npipe:////./pipe/dockerDesktopLinuxEngine","SkipTLSVerify":false}}}
```

Everything else is seemingly working fine. I can only reproduce this error by issuing `devpod list`. Note: I was able to use devpod successfully for awhile with this workspace; it's only been recently that devpod failed to discover it. I may have updated Docker for Windows in the interim.

**Comment by pascalbreuninger** [comment]
@pakdev Hm alright, thank you. Could you provide the contents of `%userprofile%\.devpod\contexts\default\workspaces\test\workspace.json` please? 
If we can't find something obvious in there, `grep -Ubo '\x00'  %userprofile%\.devpod\contexts\default\workspaces\test\workspace.json` might yield more insight

**Comment by alexandradragodan** [comment]
Hey, @pakdev 
Thanks for raising this issue! 

Will close it for now due to inactivity. 
Please feel free to reopen it if you can provide more info that would help us reproduce it. 

Thanks a lot!
