### ISSUE TITLE
Stop and Delete don't work if docker-compose.yml is not in current directory

### ISSUE THREAD

**Issue by Oscar3170** [loft-sh/devpod#623]
**What happened?**  
In my projects and in some of the [templates provided by devcontainer](https://github.com/devcontainers/templates/tree/main/src/java-postgres) the docker-compose.yml file is kept inside the .devcontainer directory, and while (with the CLI) `devpod up .` does work to start the workspace, the `stop` and `delete` commands always error because of docker compose.

I can work around it with the CLI by running the commands inside the .devcontainer directory, or moving the docker-compose.yml to the root of the project, but when stopping with the GUI it always errors.

Example:
```
/tmp/templates/src/java-postgres$ devpod stop java-postgres --debug
17:07:43 debug Acquire workspace lock...
17:07:43 debug Acquired workspace lock...
17:07:43 info Stopping container...
17:07:43 debug Run command provider command: "${DEVPOD}" helper sh -c "${COMMAND}"
17:07:43 info Stopping DevPod container...
17:07:43 info Using docker command 'docker'
17:07:43 info Use docker environment variables: [DOCKER_HOST=unix:///run/user/1000/podman/podman.sock]
17:07:44 info stop container: 
17:07:44 info         Can't find a suitable configuration file in this directory or any
17:07:44 info         parent. Are you in the right directory?
17:07:44 info 
17:07:44 info         Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml
17:07:44 info         
17:07:44 info : exit status 1
/tmp/templates/src/java-postgres$ cd .devcontainer/
/tmp/templates/src/java-postgres/.devcontainer$ devpod stop java-postgres --debug
17:07:54 debug Acquire workspace lock...
17:07:54 debug Acquired workspace lock...
17:07:54 info Stopping container...
17:07:54 debug Run command provider command: "${DEVPOD}" helper sh -c "${COMMAND}"
17:07:54 info Stopping DevPod container...
17:07:54 info Using docker command 'docker'
17:07:54 info Use docker environment variables: [DOCKER_HOST=unix:///run/user/1000/podman/podman.sock]
17:08:08 info Successfully stopped DevPod container
17:08:08 info Successfully stopped container...
```

**What did you expect to happen instead?**  
For stop and delete commands to work on projects with docker compose, independent of the current working directory or if the docker-compose.yml is on the root of the project or in the .devcontainer directory.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. Clone the [devcontainers templates repository](https://github.com/devcontainers/templates/)
2. Go to the `src/java-postgres/` directory
3. Change the app service to use the image `mcr.microsoft.com/devcontainers/java:1-11` instead of the Dockerfile inside the `.devcontainer/docker-compose.yml` file
4. Run `devpod up . --ide none` from the java-postgres directory
5. Run `devpod stop java-postgres` from the same directory

**Local Environment:**  
- DevPod Version: v0.3.4
- Operating System: linux
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: docker

**Comment by Oscar3170** [comment]
Looking at the code, I see that when calling docker-compose from the up command, a -f argument is added for all the compose files mentioned in devcontainer.json.
https://github.com/loft-sh/devpod/blob/5c42b572bd973d8352d0727c0d4c81cb5e3cb4ef/pkg/devcontainer/compose.go#L71-L79

But on the stop and delete commands, these options are missing, and it ends up looking for the compose file in the current directory.
https://github.com/loft-sh/devpod/blob/5c42b572bd973d8352d0727c0d4c81cb5e3cb4ef/pkg/compose/helper.go#L117-L133

**Comment by neogopher** [comment]
Hi @Oscar3170 :wave: ,
Thanks for creating the issue. Will have a look and update you shortly.

**Comment by neogopher** [comment]
Hi @Oscar3170 , Thanks for the initial debugging. I have created a PR to fix the same. :slightly_smiling_face:
