### ISSUE TITLE
Windows SSH Agent Forwarding Not Working

### ISSUE THREAD

**Issue by mudged** [loft-sh/devpod#632]
**What happened?**  
Attempting `devpod up` using a ssh url to a private git repository. Cloning fails and falls back to "cloning from host" functionality and continues.

````
11:33:35 info git@xxxxxxxxxxxxx: Permission denied (publickey).
11:33:35 info fatal: Could not read from remote repository.
11:33:35 error Cloning failed: error cloning repository: exit status 128. Trying cloning on local machine and uploading folder
11:33:35 info
11:33:35 info Cloning from host and upload folder to server
11:33:35 info Please make sure you have the correct access rights
11:33:36 info and the repository exists.
````

For some repositories I then see the error (might be unrelated to this issue)
````
11:34:00 info cloning local folder: EOF
11:34:00 info error parsing workspace info: rerun as root: exit status 1
11:34:00 error Try using the --debug flag to see a more verbose output
11:34:00 fatal executing agent command: agent error: cloning local folder: EOF
error parsing workspace info: rerun as root: exit status 1
: exit status 1
````

For other repositories it is able to continue. 
````
11:06:51 info Uploaded 1.60 MB
11:06:54 info Uploaded 2.63 MB
````

I am able to successfully use the https git urls for either of the repositories.

If I also use the `--dotfiles` to point to another private git repo and also use the ssh url. I see the following:
````
11:07:33 info Dotfiles git repository ssh://git@xxxxxxxxxxxx/~daniel.mudge/devpod-dotfiles.git specified
11:07:33 debug Cloning dotfiles into the devcontainer...
11:07:33 debug Running command: [C:\Program Files\DevPod\devpod-cli.exe ssh --agent-forwarding=true --start-services=false --context default yyyyyyyyy --log-output=raw --command /usr/local/bin/devpod agent workspace install-dotfiles --repository ssh://git@xxxxxxxxxx/~daniel.mudge/devpod-dotfiles.git --debug --debug]
11:07:34 info Adding ssh keys to agent, disable via 'devpod context set-options -o SSH_ADD_PRIVATE_KEYS=false'
11:07:34 info Error adding private keys to ssh-agent: ssh-agent is not started
````

I've traced that last error back to https://github.com/loft-sh/devpod/blob/main/pkg/ssh/ssh_add.go#L19 which is looking for the `SSH_AUTH_SOCK` environment variable to be set as an indication that the ssh agent is running. But this isn't set on Windows.

````
C:\Users\DanMudge>echo %SSH_AUTH_SOCK%
%SSH_AUTH_SOCK%
````

even if the agent is running
````
PS C:\WINDOWS\system32> Get-Service ssh-agent

Status   Name               DisplayName
------   ----               -----------
Running  ssh-agent          OpenSSH Authentication Agent


PS C:\WINDOWS\system32> echo %SSH_AUTH_SOCK%
%SSH_AUTH_SOCK%
````

I'm not sure if the ssh agent would have worked if it had got past this guard statement.

**What did you expect to happen instead?**  
Successfully start a workspace using a ssh git repository and ssh forwarding to be used.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Using windows 11 with DevPod installed. Try to start a workspace that uses a ssh url to a private git repository.

**Local Environment:**  
- DevPod Version: 0.3.4
- Operating System: windows (11)
- ARCH of the OS: i386 

**DevPod Provider:**  
- Cloud Provider: aws
- Kubernetes Provider: n/a
- Local/remote provider: n/a
- Custom provider: n/a

**Anything else we need to know?**  
May be related to #463 ?
Related to #620 and attempted to use the workaround mentioned in https://github.com/loft-sh/devpod/issues/620#issuecomment-1683350487 i.e. use ssh url for the dotfile repo instead of a https one.
I'm able to clone all private git repositories on the host machine using the shh url i.e. the ssh key is installed correctly.

**Comment by FabianKramm** [comment]
@mudged thanks a lot for creating this issue! Mhh, I'll need to investigate this, might be that we need to handle this differently on windows.

**Comment by mudged** [comment]
Thanks @FabianKramm.
As a little extra info that might be relevant - I'm not using Docker Desktop on the host (no company licence) and am also not using WSL. I suspect the use of Docker Desktop and WSL2 would give you the more typical ssh setup.

**Comment by 89luca89** [comment]
Hi @mudged can you give some more info about your setup?
I cannot reproduce using DockerDesktop + WSL (as you were predicting)

**Comment by mudged** [comment]
I've upgraded to devpod 0.4.2 and am am no longer seeing this error when using the "docker" provider (Rancher Desktop 1.10.0).

**Comment by 89luca89** [comment]
Cool @mudged thanks for the update!

**Comment by ianepreston** [comment]
Not sure if I should open a new one or tag onto this. I'm having basically the same issue.

I'm using an ssh URL for both my repository and my dotfiles. Both repositories are in GitHub. 
ssh-agent is running and I'm able to clone the repositories from PowerShell no problem.
Cloning the project repository works fine but then when it tries to clone my dotfiles from within the container that fails.

Running devpod `v0.5.3`

Logs below:

```bash
[18:09:14] info Creating devcontainer...
[18:09:15] info Cloning into 'C:\Users\ipreston\.devpod\agent\contexts\default\workspaces\homelab-github\content'...
[18:09:17] info 33984fad91e6e90a1b0d34afd5c316f4003cc0c77aef99db15ccaf457386b195
[18:09:20] info Setup container...
[18:09:21] info Run 'ssh homelab-github.devpod' to ssh into the devcontainer
[18:09:21] info Dotfiles git repository git@github.com:ianepreston/dotfiles.git specified
[18:09:23] info Cloning dotfiles git@github.com:ianepreston/dotfiles.git
[18:09:24] info error cloning repository: exit status 128
[18:09:24] info Error tunneling to container: wait: remote command exited without exit status or exit signal
[18:09:24] info Try enabling Debug mode under Settings to see a more verbose output
[18:09:24] info tunnel to container: run in container: Process exited with status 1
```

**Comment by ianepreston** [comment]
For added context I have docker desktop and that's what I'm using as my provider. I do have WSL installed but I'm doing this right from Windows. I have devpod CLI installed on a WSL VM and I'm able to start up the same workspace with the same dotfiles repo without issue.

**Comment by 89luca89** [comment]
@ianepreston it's a different issue, your involves dotfiles, this one involves the project repo

I'm ok if you open a new issue, as this is a different thing :+1:
