### ISSUE TITLE
Using mac as a provider through ssh

### ISSUE THREAD

**Issue by mistercorea** [loft-sh/devpod#639]
**What happened?**  
![Screen Shot 2023-08-24 at 7 22 30 PM](https://github.com/loft-sh/devpod/assets/2279899/532cc55b-1212-40a2-a2c0-a8da14b3776b)

```
[19:22:41] info Workspace vscode-remote-try-php already exists
[19:22:41] info Creating devcontainer...
[19:22:49] info Waiting for devpod agent to come up...
[19:22:59] info Waiting for devpod agent to come up...
[19:23:08] info Waiting for devpod agent to come up...
[19:23:14] info Waiting for devpod agent to come up...
[19:23:19] info Waiting for devpod agent to come up...
[19:23:24] info Waiting for devpod agent to come up...
[19:23:30] info Waiting for devpod agent to come up...
```
I think I was able to get the ssh connection working but it fails to find the devpod agent.

It may require more params?

Here is a debug console 
```
{"time":"2023-08-24T19:24:14.226265-05:00","message":"execute inject script","level":"debug"}
{"time":"2023-08-24T19:24:14.226271-05:00","message":"download agent from https://github.com/loft-sh/devpod/releases/download/v0.3.4","level":"debug"}
{"time":"2023-08-24T19:24:14.226371-05:00","message":"Run command provider command: ${SSH_PROVIDER} command","level":"debug"}
{"time":"2023-08-24T19:24:15.835108-05:00","message":"done exec","level":"debug"}
{"time":"2023-08-24T19:24:15.835203-05:00","message":"done inject","level":"debug"}
{"time":"2023-08-24T19:24:15.835226-05:00","message":"done injecting","level":"debug"}
{"time":"2023-08-24T19:24:15.835241-05:00","message":"Inject Error: Error: failed to install devpod\n\nEOF","level":"debug"}
{"time":"2023-08-24T19:24:18.835745-05:00","message":"execute inject script","level":"debug"}
{"time":"2023-08-24T19:24:18.835818-05:00","message":"download agent from https://github.com/loft-sh/devpod/releases/download/v0.3.4","level":"debug"}
{"time":"2023-08-24T19:24:18.836342-05:00","message":"Run command provider command: ${SSH_PROVIDER} command","level":"debug"}
```

**What did you expect to happen instead?**  
It would work like local env with docker. 

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```
{
    "name": "...",
    ...
}
```

**Local Environment:**  
- DevPod Version: [use `devpod version`]
- ❯ devpod version
v0.3.4%
- Operating System: windows | linux | mac
- mac
- ARCH of the OS: AMD64 | ARM64 | i386 
- amd64

**DevPod Provider:**  
- Cloud Provider: google | aws | azure | digitalOcean
- Kubernetes Provider: [use `kubectl version`]
- Local/remote provider: docker | ssh
- Custom provider: provide imported `provider.yaml` config file

**Anything else we need to know?**

**Comment by mistercorea** [comment]
This worked on the ubuntu. I think it might be related to environmental differences.

**Comment by 89luca89** [comment]
Hi @mistercorea thanks for the issue, will take a look at this :+1:
