### ISSUE TITLE
offline deployment

### ISSUE THREAD

**Issue by zzhzero** [loft-sh/devpod#649]
Can it be used in a completely offline environment

Like: https://www.jetbrains.com/help/idea/fully-offline-mode.html

**Comment by alexandradragodan** [comment]
Hey, @zzhzero 👋 
Thanks for this idea! 

Have you managed to try it out yet? 🚀

**Comment by alexandradragodan** [comment]
Hey, @zzhzero 

Closing this issue for now due to inactivity. 
Please feel free to reopen if you didn't manage to get the offline deployment to work.

Thanks!
