### ISSUE TITLE
Dotfile script is executed as root if external SSH config is used

### ISSUE THREAD

**Issue by flokoe** [loft-sh/devpod#655]
Hi,

I'm not entirely sure what happened here, I just noticed weird behavior when playing with dotfiles and external SSH configs. I'll try to give as much information as possible.

**What happened?**  

Dotfile script was executed as `root` user if external SSH config is used (via `--ssh-config` option and `Include` in `~/.ssh/config`).

**What did you expect to happen instead?**

Dotfile script should be executed as `remoteUser`. As it normally does when not using `--ssh-config`. In this case, I expected the user to be `vscode`.

**How can we reproduce the bug?** (as minimally and precisely as possible)

SSH Config `~/.ssh/config`:

```plain
Include devpod.conf
```

No custom `devcontainer.json` just DevPod command using prebuild container image:

```bash
devpod up mcr.microsoft.com/devcontainers/base:bookworm \
--dotfiles https://github.com/flokoe/dotfiles-devcontainer \
--dotfiles-script debug.sh \
--ide none \
--recreate \
--ssh-config ~/.ssh/devpod.conf
```

The output of my debug script just dumps information about the current environment. The user will be `root`

If the same command is executed without `--ssh-config ~/.ssh/devpod.conf` The user will be `vscode` as expected.

**Local Environment:**  
- DevPod Version: `v0.3.6`
- Operating System: Debian 12 (Bookworm)
- ARCH of the OS: `AMD64`

**DevPod Provider:**  
- Local/remote provider: `docker`
- Local Docker Version: `24.0.5`

**Anything else we need to know?**  

I'm unsure if this behavior is due to the usage of `--ssh-config` or the include itself in the main SSH config. It's probably the include. As soon as a DevPod SSH config exists in `~/.ssh/config` it works again.

**Comment by 89luca89** [comment]
Thanks for the report! I'll investigate this and try to reproduce :+1:
