### ISSUE TITLE
Create workspace from Docker Hub

### ISSUE THREAD

**Issue by mkessler76** [loft-sh/devpod#657]
When creating workspace, have option to create directly from Docker Hub....   Not just from a Github link or local file

**Comment by FabianKramm** [comment]
Hey @mkessler76! That should work already, just put in any image name, e.g. `devpod up alpine`. Can you give us more information where you encounter this issue?

**Comment by pascalbreuninger** [comment]
@mkessler76 closing due to inactivty, feel free to reopen if you have more questions
