### ISSUE TITLE
"kubectl": executable file not found in $PATH

### ISSUE THREAD

**Issue by solesensei** [loft-sh/devpod#665]
**What happened?**  
Updated to 0.3.6, now I can't manage devpod workspaces with Desktop App. `devpod` executable still working.
All the workspaces have Error status, when you click on status, you get message. Debug mode enabled.
```bash
[20:56:05] error Try enabling Debug mode under Settings to see a more verbose output
[20:56:05] fatal error retrieving container status: find dev container: exec: "kubectl": executable file not found in $PATH
exit status 1
```

**What did you expect to happen instead?**  
Desktop App will work.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```
{
    "name": "...",
    ...
}
```

**Local Environment:**  
- DevPod Version: v0.3.6
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Cloud Provider: azure 
- Kubernetes Provider: v1.27.4
- Local/remote provider: docker

**Anything else we need to know?**  
```bash
which kubectl
>> /opt/homebrew/bin/kubectl
which devpod
>> /usr/local/bin/devpod
```
Also I have this warning even after enter `Add CLI th Path`
![image](https://github.com/loft-sh/devpod/assets/24857057/0ebbfd83-88d9-4455-9d55-ea5afd78e492)

**Comment by pbialon** [comment]
Hi @solesensei thanks for raising this issue! I managed to reproduce a problem with PATH resolving on Mac M2 in the Devpod Desktop version 0.3.6. It works for 0.3.4, so I'd recommend you to downgrade it until we fix the issue with 0.3.6.  (you can download 0.3.4 release for your machine [here](https://github.com/loft-sh/devpod/releases/tag/v0.3.4)).

We'll do our best to fix it for 0.3.6 as soon as possible

**Comment by pbialon** [comment]
Ok, we found the problem and have a fix, which will go with the next release!

**Comment by Jolter** [comment]
Hi, I'm seeing this error message too, on 0.3.7. I installed it to run one of the examples, vscode-remote-try-java.

```
[08:59:39] info Workspace vscode-remote-try-java already exists
[08:59:39] info Creating devcontainer...
[08:59:39] info devcontainer up: find dev container: exec: "kubectl": executable file not found in $PATH
[08:59:39] error Try enabling Debug mode under Settings to see a more verbose output
[08:59:39] fatal executing agent command: exit status 1
```

**Comment by pbialon** [comment]
@Jolter I'll take a look. What OS are you using?

**Comment by Jolter** [comment]
Hi, sorry, I forgot that part. Mac OS!

**Comment by pbialon** [comment]
Did you try to run it with your local docker provider? 

I cannot reproduce the problem now - please make sure you're running on the newest devpod-cli version as well (you can check it by running in the console a command `devpod version`).

**Comment by Jolter** [comment]
Hi, 
No, I didn’t try Docker. Let’s say I don’t like Docker’s license and would prefer to use Minikube. But I can certainly try it for the sake of troubleshooting!

I’ll try, and get back to you.

As for the Cli, I’m a complete Mac newb as well as running Devpod for the first time. I’m trying to simply follow the setup instructions on the web page, hence I’m attempting a GUI based install.

Perhaps there is some prerequisite setup of the env, that is missing from the instructions.

**Comment by Jolter** [comment]
Yeah it works fine on Docker. I guess it's related to the minikube/qemu provider only.

**Comment by solesensei** [comment]
It works fine since 0.3.6. I close the issue.
