### ISSUE TITLE
SSH agent not being forwarded during `postCreateCommand`

### ISSUE THREAD

**Issue by sevetseh28** [loft-sh/devpod#673]
**What happened?**  
I've realized that the SSH agent is not being forwarded during `postCreateCommand` because the SSH connection is not being established yet.

**What did you expect to happen instead?**  
I expect `postCreateCommand` to have access to the forwarded agent (same as when running locally), because it can be needed to pull from private repositories during that (npm, pip install, etc.).

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. Setup any private Git repo to which you have access with your local SSH keys.
2. Have a devcontainer.json that tries to checkout the same private Git repo over SSH in `postCreateCommand`.
2. Notice how it cannot clone it.

**Local Environment:**  
- DevPod Version: 0.3.3
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Cloud Provider: AWS
- Local/remote provider: docker

**Anything else we need to know?**

**Comment by FabianKramm** [comment]
Hey @sevetseh28 thanks for creating this issue! Mhh yeah maybe we can start the ssh agent there already to make sure this works correctly.

**Comment by sevetseh28** [comment]
> Hey @sevetseh28 thanks for creating this issue! Mhh yeah maybe we can start the ssh agent there already to make sure this works correctly. This is more or less the same problem during the initial git clone on the VM where the agent is also not there, I guess we should solve both problems.

Thanks! That would be great. 

The second point you mentioned would be also especially helpful for monolithic repos that are large in size. 
I've noticed that when opening a locally checked out large Git repo it can take a lot of time to upload it to the remote workspace.

Not sure if this is already happening but, one solution I see would be to compress it before, and upload a single compressed file and then decompress it in the remote machine, or more easily, just be able clone the repo in the remote VM which would need to have access to the SSH keys (what you mentioned).

**Comment by FabianKramm** [comment]
@sevetseh28 yeah cloning the repo remotely would be the best way (it works right now already for https where we use a git credentials helper), but ssh has the issue that the ssh agent is not there initially, which is why we fallback to the local system for cloning the repository, but obviously this is not a perfect solution.
