### ISSUE TITLE
No refrence URL for workspace source

### ISSUE THREAD

**Issue by hrittikhere** [loft-sh/devpod#676]
I believe it would be beneficial to provide users with a reference URI or a sample repository to test the product without the need to create something from scratch. The included image showcases an example of this with `github.com/microsoft/vscode-remote-try-go`, so I suggest adding a similar reference for users to easily try out the product.

https://github.com/loft-sh/devpod/blob/b202886f64b082b180512d5e61cbe26c0a51df61/docs/pages/getting-started/quickstart-vscode.mdx#L30

**Comment by FabianKramm** [comment]
Yes good idea, @89luca89 can you take a look?
