### ISSUE TITLE
VScode IDE doesn't start from CLI

### ISSUE THREAD

**Issue by iprystay-incomm** [loft-sh/devpod#681]
**What happened?**  
Command bellow doesn't bring VScode up
`code --folder-uri vscode-remote://ssh-remote+vscode-remote-try-python.devpod//workspaces/vscode-remote-try-python --disable-extension ms-vscode-remote.remote-containers --new-window
`
**What did you expect to happen instead?**  
The command from DevPod to bring VScode up should have container path as the last parameter:
`code --disable-extension ms-vscode-remote.remote-containers --new-window --folder-uri vscode-remote://ssh-remote+vscode-remote-try-python.devpod//workspaces/vscode-remote-try-python
`

**Local Environment:**  
- DevPod Version: 0.3.7
- Operating System: windows
- ARCH of the OS: AMD64
- VSCode Version: 1.81.1
**DevPod Provider:**  
- Local/remote provider: docker

**Anything else we need to know?**  
Proposed fix is to rectify pkg/ide/vscode/open.go openViaCLI function to initialize args in line 77 to empty string `args := []string{}` and add "--folder-uri" parameter at the end before execution (line 89):
`args = append(args, "--folder-uri", "vscode-remote://ssh-remote+" + workspace + ".devpod/" + folder")`

**Comment by FabianKramm** [comment]
@iprystay-incomm thanks for creating this issue! Strange, it works for me, is this a new change in vscode or why does that cause an issue?

**Comment by iprystay-incomm** [comment]
Not sure - if I'm trying to execute it from Windows CLI, even without DevPod open, and path is a 1st parameter as called from DevPod - vscode doesn't start. But if you move path as the last parameter - it VSCode window is opening. May be specific to VSCode version (1.81.1)
