### ISSUE TITLE
New minikube doc seems to be incomplete

### ISSUE THREAD

**Issue by leunamnauj** [loft-sh/devpod#683]
After following the instructions when you try to build an image claims that you dont have a registry to push the image, this has been happening for quite a while. I'm waiting for the resolution of this [PR](https://github.com/loft-sh/devpod/issues/384) to get simple setup easy for testing.

Am I missing something or doing something wrong?

Thanks

**Comment by FabianKramm** [comment]
@leunamnauj in latest alpha version we removed the need to have a registry within Kubernetes / minikube, so you might want to try [v0.4.0-alpha.2](https://github.com/loft-sh/devpod/releases/tag/v0.4.0-alpha.2) which potentially fixes your issue (make sure to readd the Kubernetes provider as its in a different repository now)

**Comment by leunamnauj** [comment]
Hello @FabianKramm 
Thanks a lot!

**Comment by alexandradragodan** [comment]
Hey @leunamnauj 
Thanks for reporting this. 

I'll close this issue for now, to keep our roadmap clear. 
Please feel free to open another one in case you encounter issues when trying out 0.4.0-alpha.2
