### ISSUE TITLE
Pull request devpod.sh/open query parameter

### ISSUE THREAD

**Issue by p5** [loft-sh/devpod#687]
**Is your feature request related to a problem?**  
Other tools (CodeSpaces etc) allow reviewers of code to easily checkout PRs in a devcontainer (or remote environment) to review the changes in a few clicks.  This is not yet possible in DevPod.

**Which solution do you suggest?**  
By having a query parameter available in the https://devpod.sh/open, such as https://devpod.sh/open#https://github.com/loft-sh/devpod&pr=123, you open yourself up to a lot more automation.  

One of which that comes to mind is automatically adding an "Open in DevPod" button to the PR which allows reviewers to open the PR branch in a single click.  You don't necessarily need to create or support the action yourselves - it's easy enough for people to automate appending two strings and updating a PR in GHA.

**Which alternative solutions exist?**  
Running `gh pr checkout` after cloning the repo.

**Additional context**  
This may be easier due to https://github.com/loft-sh/devpod/commit/b202886f64b082b180512d5e61cbe26c0a51df61 being committed.  I guess the UI would need to be updated to support this option.

**Comment by neogopher** [comment]
Hi @p5 :wave: ,

As you correctly identified, we already have this implemented and it will be available for use in the UI once v0.4.0 is released. 

Meanwhile, we have used the format `pull/<PR-Number>/head` to identify the PR reference itself. So once the release is in, creating a workspace from the PR will be possible using the below :slightly_smiling_face: 
`https://devpod.sh/open#https://github.com/loft-sh/devpod@pull/123/head`

**Comment by p5** [comment]
Ah, great!  I thought it was going to be more work getting it to integrate with the devpod.sh link, but sounds like it was already the plan :)

**Comment by alexandradragodan** [comment]
Hey, @p5 
Thanks a bunch for suggesting this! 

Given that we are already working on it, I'll close this issue now to keep our roadmap focused. 
Feel free to open some more when trying it out with the next 0.4.0 release.
