### ISSUE TITLE
Multiple environments per DevPod workspace

### ISSUE THREAD

**Issue by p5** [loft-sh/devpod#688]
This is just an idea - feel free to close if it's not something you wish to support.

**Is your feature request related to a problem?**  
I find it difficult keeping my workspaces clean when working on multiple feature branches at once.  There's always changes I need to stash to change branches, and it's not a smooth experience (although that's nothing related to DevPod - that's Git).

**Which solution do you suggest?**  
It would be awesome if DevPod can manage multiple "environments" or "branches" per workspace - either in isolated containers or simply separate directories in the same container.

If you are working on a feature branch and some urgent change is needed somewhere else, you can open the DevPod app, click the `...` icon on the workspace -> "Create Environment" and have a completely clean, isolated place to make your changes without touching your old feature branch.
You can then switch between each "environment" seamlessly without needing to stash your changes, or discard your changes by deleting the container or directory (using DevPod).

**Which alternative solutions exist?**  
You typically use Git Worktrees to have a single branch per directory, which works well but is not (yet?) supported in DevPod - see my other issue https://github.com/loft-sh/devpod/issues/512

**Additional context**  
Feel free to close this and I'll learn how to actually use git like everyone else :smile:

**Comment by 89luca89** [comment]
Hi @p5 thanks for the issue!

Yea I concur that probably adding worktree support (issue 512) would be the best thing, and would solve this use case

I think this issue can be marked a duplicate of #512

**Comment by p5** [comment]
Closing as duplicate of https://github.com/loft-sh/devpod/issues/512
