### ISSUE TITLE
SSH provider should fail early on noexec filesystem

### ISSUE THREAD

**Issue by arrowmaster** [loft-sh/devpod#692]
**Is your feature request related to a problem?**  
The default agent path of /tmp/devpod/agent could be mounted as noexec on some systems. When trying to start a workspace the agent will be downloaded and then fail to run. This repeats multiple times until failure with no way to cancel. No indication of the problem is given unless debug is enabled.

**Which solution do you suggest?**  
Detect if attempting to start the agent on a noexec mounted filesystem and fail early with an error message. Do not attempt to try again.

**Which alternative solutions exist?**  

**Additional context**

**Comment by pbialon** [comment]
Hi @arrowmaster! Thanks for bringing up that issue - that's a very good idea!

We'll discuss internally on when to implement this, but you're more than welcome to contribute if you want!

**Comment by pbialon** [comment]
Ok it was already merged -> https://github.com/loft-sh/devpod/pull/704 

It will be present in the next release!
