### ISSUE TITLE
Can't recreate workspace with updated resources [kubernetes]

### ISSUE THREAD

**Issue by solesensei** [loft-sh/devpod#693]
**What happened?**  
1. Created a workspace with provider (1 CPU, 8Gb RAM)
2. Updated provider (2 CPU, 16Gb RAM)
3. Tried to recreate workspace with the same provider
  - `devpod up . --recreate`
  - `devpod stop ubuntu-latest && devpod start ubuntu-latest`
 4. Resources are the same (1 CPU, 8Gb RAM)

**What did you expect to happen instead?**  
Resources will be changed

**How can we reproduce the bug?**

My *`devcontainer.json`*:
```
{
    "name": "ubuntu:latest",
}
```

**Local Environment:**  
- DevPod Version: v0.3.7
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Cloud Provider: azure
- Kubernetes Provider: 1.27
- Local/remote provider: ssh
- Custom provider: provide imported `provider.yaml` config file

**Anything else we need to know?** 
I use custom provider.yaml config. But it doesn't matter here

<details><summary>Logs</summary>

```
debug Workspace Folder already exists
10:04:03 debug Use Kubernetes Namespace 'devpod'
10:04:03 debug Run command: kubectl --namespace devpod get pvc devpod-ubuntu-latest-default-de6df1c6e0be-a97b7 --ignore-not-found -o json
10:04:04 debug Run command: kubectl --namespace devpod get pod devpod-ubuntu-latest-default-de6df1c6e0be-a97b7 --ignore-not-found -o json
10:04:06 debug Run command: kubectl --namespace devpod get pvc devpod-ubuntu-latest-default-de6df1c6e0be-a97b7 --ignore-not-found -o json
10:04:06 debug Run command: kubectl --namespace devpod get pod devpod-ubuntu-latest-default-de6df1c6e0be-a97b7 --ignore-not-found -o json
10:04:06 info Deleting devcontainer...
10:04:06 debug Run command: kubectl --namespace devpod delete po devpod-ubuntu-latest-default-de6df1c6e0be-a97b7 --ignore-not-found
10:04:08 info Delete pod 'devpod-ubuntu-latest-default-de6df1c6e0be-a97b7'...
10:04:08 debug Run command: kubectl --namespace devpod delete po devpod-ubuntu-latest-default-de6df1c6e0be-a97b7 --ignore-not-found --grace-period=10
10:04:08 debug Create namespace 'devpod'
10:04:08 debug Run command: kubectl --namespace devpod create ns devpod
10:04:08 debug Error creating namespace: exit status 1
10:04:08 debug Run command: kubectl --namespace devpod get pvc devpod-ubuntu-latest-default-de6df1c6e0be-a97b7 --ignore-not-found -o json
this line ---> 10:04:09 debug Create pod with: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"devpod-ubuntu-latest-default-de6df1c6e0be-a97b7","creationTimestamp":null,"labels":{"app.kubernetes.io/name":"devpod","devpod.sh/created":"true","user":"dim-gonch"}},"spec":{"volumes":[{"name":"devpod","persistentVolumeClaim":{"claimName":"devpod-ubuntu-latest-default-de6df1c6e0be-a97b7"}}],"containers":[{"name":"devpod","image":"ubuntu:latest","command":["/bin/sh"],"args":["-c","echo Container started\ntrap \"exit 0\" 15\n\nexec \"$@\"\nwhile sleep 1 \u0026 wait $!; do :; done","-"],"resources":{"limits":{"cpu":"1","memory":"8Gi","nvidia.com/gpu":"0"},"requests":{"cpu":"1","memory":"8Gi","nvidia.com/gpu":"0"}},"volumeMounts":[{"name":"devpod","mountPath":"/workspaces/ubuntu-latest","subPath":"devpod/0"}],"securityContext":{"runAsUser":0,"runAsGroup":0,"runAsNonRoot":false}}],"restartPolicy":"Never"},"status":{}}
10:04:09 info Create Pod 'devpod-ubuntu-latest-default-de6df1c6e0be-a97b7'

here you can see that request manifes still use old provider
```

</details>

If I use
```
devpod delete
devpod up . --provider
```
everything will be fine, but is it possible to resize/recreate the **same workspace** with **new resources** without deleting it?

**Comment by solesensei** [comment]
Hi @FabianKramm 
I got 
```
kubernetes is not an in-built provider in this DevPod version anymore, please run `devpod provider update kubernetes kubernetes` to use the latest kubernetes provider
```

**Comment by pascalbreuninger** [comment]
Hi @solesensei, you can use kubernetes providers the way you've used to. We split them into a [separate repo](https://github.com/loft-sh/devpod-provider-kubernetes) to decouple them.

**Comment by solesensei** [comment]
Hi @pascalbreuninger 
The way I've used to kubernetes provider is

```bash
devpod provider add /path/to/providers/provider.yaml --name my-custom-name
```

On the version [v0.4.0](https://github.com/loft-sh/devpod/releases/tag/v0.4.0-alpha.4) it is not possible.

I need multiple kuberentes providers, don't see a way to do it now.

```bash
devpod provider add kubernetes
```
It is working, but I need a custom provider.yaml

What I need to change in my provider config (see previous comment)?

**Comment by solesensei** [comment]
If switching to `custom` provider with binaries, I don't see a way to specify `BUILD_REPOSITORY` variable.
Also I splitted `RESOURCES` on separate variables, because it's much easier to specify them in separate GUI fields and then I used them in `kubernetes`

```yaml
    resources: |- 
requests.cpu=${RESOURCES_CPU},requests.memory=${RESOURCES_MEMORY},requests.${RESOURCES_GPU_VENDOR}=${RESOURCES_GPU},limits.cpu=${RESOURCES_CPU},limits.memory=${RESOURCES_MEMORY},limits.${RESOURCES_GPU_VENDOR}=${RESOURCES_GPU}
```

In the new version I don't see a way to use them inside kubernetes.

**Comment by pascalbreuninger** [comment]
> It is working, but I need a custom provider.yaml

What's the use case for this exactly? Is there something the options for the kubernetes provider don't cover?

Other than that, the way to create multiple kubernetes providers didn't change 
`devpod provider add kubernetes --name my-k8s`

We removed `BUILD_REPOSITORY` from the kubernetes driver but you can still push builds to a repository with `devpod build $WORKSPACE_SOURCE --repository=your/repo`

**Comment by solesensei** [comment]
> What's the use case for this exactly? Is there something the options for the kubernetes provider don't cover?

The main use case is GUI. I need a convenient way to create devpods with and without GPUs and different resources.
![image](https://github.com/loft-sh/devpod/assets/24857057/e33c805c-fafc-443c-a0e9-be205cf0f58f)

And I don't like to specify `RESOURCES` manually in the following field.
![image](https://github.com/loft-sh/devpod/assets/24857057/d8865ff1-b358-4e88-b84b-da00a8984195)

> We removed BUILD_REPOSITORY from the kubernetes

Understood. I used it for building `Dockerfile` from `.devcontainer`. With single command.

```bash
devpod up git@github../repo.git --provider my-kuber-with-1-gpu
>>> clone, get .devcontainer.json
>>> build Dockerfile with build kit
>>> push image to BUILD_REPOSITORY
>>> start pod with this image
```
I guess I can do the same with
```
devpod build git@github../repo.git --repository=BUILD_REPOSITORY
>>> image:hash
devpod up image:hash --provider my-kuber-with-1-gpu
```
but with one more action, and copy-pasting `image:hash`.

---
The main reason is that I made a small wrapper around devpod to simplify the creating process for Azure kubernetes (I need it often), I can do something like that.

```bash
devpod-conf workspace start ubuntu:latest --gpu 2 --cpu 32 --memory 16Gb --volume my-pvc-volume
>>> devpod provider add provider.yaml --name my-provider --option=RESOURCES_GPU=2 ...
>>> devpod up ubuntu:latest --provider my-provider
>>> starting workspace
```
