### ISSUE TITLE
`Starting VS Code` Nothing happen.

### ISSUE THREAD

**Issue by kmarilleau** [loft-sh/devpod#706]
When I start a workspace on devpod using VS Code (not VS Code Browser), I get this:
![image](https://github.com/loft-sh/devpod/assets/11370450/326abbd1-6a2d-47da-862c-4bbedcab73e0)

But VS Code disn't start automatically. I need to open it manually.

**Environment:**
- **OS Edition:** Windows 11 Pro
- **Version:** 22H2
- **OS build:** 22621.2283
- **ARCH of the OS:** AMD64
- **DevPod Version:** 0.3.7
- **Local provider:** docker
- `(Get-Command code).Source`: `C:\Users\myuser\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd`

**Comment by pascalbreuninger** [comment]
Hi @kmarilleau, can you rerun the command with the `--debug` flag set (settings > general > debug mode in the UI), there might be more information

**Comment by davull** [comment]
Same here, i can confirm the missing `=` (on windows systems)

**Comment by pascalbreuninger** [comment]
not sure if I want to cry or laugh. Will try repro this and fix
