### ISSUE TITLE
Difficulties using devpod on closed-network

### ISSUE THREAD

**Issue by itamadev** [loft-sh/devpod#707]
**Is your feature request related to a problem?**  
As of now when trying to use `devpod` on-prem or more specifically on some closed-network situations it's not compatible (for IDEs like `vscodebrowser` or `jetbrains`) 
the main reason is that the providers use a `const` from where to download the ide base. 

Are there any plans to give the options to configure it like the default `DEVPOD_AGENT_URL` 

**Which solution do you suggest?**  
The solution I see as of now is creating a forked repo enabling this capability, if this change can be added to the stable release of `devpod` I'd be more than happy to try and tackle it.

**Comment by pascalbreuninger** [comment]
Hi @itamadev , sounds like a useful addition to me. Let us know if you need help getting your PR ready

**Comment by itamadev** [comment]
Hey @pascalbreuninger I saw something weird while implementing this,
The code seems to have some functionality to override the download URLs of the IDEs but not using environment variables, I think it would be good to add an env var implementation still - mainly to keep it simple and have a similar solution to `DEVPOD_AGENT_URL`. 
However, we can add it in the UI too as the devpod agents have an implementation for that too.

Wanted to get your thoughts on this before I move forward with my PR 😄

**Comment by pascalbreuninger** [comment]
@itamadev, the current dynamic url fetching is to pick the correct jetbrains IDE binary for the target architecture. An environment variable makes sense though, I agree. 
If you're curious about the UI, feel free to add it. If not, I can also do that once your PR is merged

**Comment by alexandradragodan** [comment]
Hey, @itamadev 
Thanks for opening this issue! 

Are you still planning to open a PR for this contribution? 😄

**Comment by benjie91** [comment]
I am currently facing the same issue. The workaround I have is to up the container without specifying the IDE and then use jetbrain gateway to ssh into the container which will install the necessary binary

**Comment by vrabbi** [comment]
This would be extremely beneficial for us as well

**Comment by pascalbreuninger** [comment]
@vrabbi you can manually specify the Download URL per IDE:
`devpod ide set-options intellij -o DOWNLOAD_URLAMD64=$YOUR_URL`, just make sure you're pinning your version `devpod ide set-options -o VERSION=$VERSION` as well :)
