### ISSUE TITLE
Git cloning failure

### ISSUE THREAD

**Issue by vanarok** [loft-sh/devpod#709]
**What happened?**  
```git@git.sr.ht: Permission denied (publickey,keyboard-interactive)```

**What did you expect to happen instead?**  
Git cloning success

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Cloning private repository from git.sr.ht

**Local Environment:**  
- DevPod Version: master branch 19 september
- Operating System: Android OS with termux
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Cloud Provider: digitalOcean
- Local/remote provider: ssh 
- Custom provider: 
[devpod-provider.txt](https://github.com/loft-sh/devpod/files/12726276/devpod-provider.txt)

[devpod.log](https://github.com/loft-sh/devpod/files/12726291/devpod.log)

**Comment by pascalbreuninger** [comment]
Hi @vanarok, thanks for opening the issue. We use the git credential manager to authenticate against the server from within the vm. Did you set this up on your local machine?
There's more info in [the docs](https://devpod.sh/docs/developing-in-workspaces/credentials) that might help you

**Comment by vanarok** [comment]
Привет. Я ознакомился с документацией еше ранее. 
Могу дополнить, что у меня нет проблем с клонированием и работой с git репозиториями по https.

**Comment by pascalbreuninger** [comment]
Ahh I see now. This is actually a version mismatch between the latest release and the master branch. 
The agent pulls the latest stable release from github (v0.3.7) but your local client is the latest master branch. Because of a grpc handler rename the agent can't call the fallback for failed git clones anymore. 

Can you check if it works with using v0.3.7 locall?

**Comment by vanarok** [comment]
Я воспользовался вашим советом и репозиторий склонировался в девконтейнере, но git команды в веб vscode не работают и требуют ключи.
```
> git pull --tags origin master
git@git.sr.ht: Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by vanarok** [comment]
[devpod-debug-output.txt](https://github.com/loft-sh/devpod/files/12740357/devpod-debug-output.txt)

**Comment by FabianKramm** [comment]
@vanarok seems like it has worked now, is this issue solved then?

**Comment by vanarok** [comment]
Yes, the original problem is solved, but I still have a question about how I can use this solution on the master branch instead of the release tag.

**Comment by pascalbreuninger** [comment]
@vanarok You'd have to compile and host the cli based on the master branch yourself and then set the agent url to point to your hosted version. You will need to ensure it's accessible from your remote host! 
You can set it either on the context level, or per command
context: `devpod context set-options -o AGENT_URL=$path-to-your-version` or in the UI `Settings > General > Agent URL` 
command: `DEVPOD_AGENT_URL=$path-to-your-version up ...`
