### ISSUE TITLE
Inject Error: check if filesystem is noexec

### ISSUE THREAD

**Issue by vanarok** [loft-sh/devpod#713]
**What happened?**  
[devpod-output.txt](https://github.com/loft-sh/devpod/files/12762602/devpod-output.txt)

**What did you expect to happen instead?**  
connection to workspace

**How can we reproduce the bug?** (as minimally and precisely as possible)  

clone master branch, build, add provider and up workspace

**Local Environment:**  
- DevPod Version: master branch 37bc7ce
- Operating System: Android OS with termux
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Cloud Provider: digitalOcean
- Local/remote provider: ssh
- Custom provider: https://github.com/vanarok/devpod-provider-digitalocean/releases/download/v0.1.3/provider.yaml

**Comment by pascalbreuninger** [comment]
Hi @vanarok , thanks for opening the issue - we'll take a look

**Comment by pascalbreuninger** [comment]
should be fixed by #868 as well
