### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by vanarok** [loft-sh/devpod#714]
**Is your feature request related to a problem?**  
Yes

**Which solution do you suggest?**  
Create build for OS android with CGO_ENABLED=1

**Which alternative solutions exist?**  
Manual build

**Additional context**
Build working without CGO, but have errors when devpod getting providers.
https://github.com/golang/go/issues/8877

I created fork with draft building for android.
https://github.com/vanarok/devpod/blob/main/.github/workflows/release.yaml

**Comment by pascalbreuninger** [comment]
Hi @vanarok, great to see you got it running on android. Targeting mobile platforms isn't a priority for the project as of now, though. If you want to, we can link to your fork in the readme

**Comment by vanarok** [comment]
@pascalbreuninger 
Thanks for the comprehensive answer.  I hope someday there will be official support for mobile platforms, because remote work in the cloud is gradually becoming popular thanks to, for example: samsung dex, miui pc mode.

Thanks for the comprehensive answer.  I hope someday there will be official support for mobile platforms, because remote work in the cloud is gradually becoming popular thanks to, for example: samsung dex, miui pc mode.

 I won't mind if you point this out in the readme.

**Comment by pascalbreuninger** [comment]
Absolutely, we've also thought about it quite a bit, and people have been asking it ever since the launch. There's a lot of work to add two non-desktop OSs though and we simply don't have the capacity to work on that atm.

Added your release.yaml to [this](https://github.com/loft-sh/devpod/pull/716) page on the docs btw

**Comment by bbigras** [comment]
Btw, with nix-on-droid (a termux fork that use nixpkgs), you can use `nix-shell -p devpod` to get a prebuilt binary.

It would still be nice, for termux users, to package devpod for them too eventually.
