### ISSUE TITLE
Support for Digital Ocean and Linode.

### ISSUE THREAD

**Issue by AkshayAwate** [loft-sh/devpod#717]
**Is your feature request related to a problem?**  
Not now, Better to have choice for various cloud providers.

**Which solution do you suggest?**  
Its better to add Digital Ocean and Linode provider, might be useful in future.

**Which alternative solutions exist?**  

**Additional context**  
Let me know, i can pick this task.

**Comment by pascalbreuninger** [comment]
Hey @AkshayAwate, we have an official provider for [Digital Ocean](https://github.com/loft-sh/devpod-provider-digitalocean). If you want to add a community provider for linode, [this guide](https://devpod.sh/docs/developing-providers/quickstart) is a good place to get started
