### ISSUE TITLE
Is Docker Desktop for Windows (WSL2) supported?

### ISSUE THREAD

**Issue by ktzsolt** [loft-sh/devpod#726]
**What happened?**  
On Windows 10 with Docker Desktop for Windows (WSL2) I tried to use the docker provider with docker host address host.docker.internal and also with localhost and neither did work. I also set the Docker Desktop setting to true `Expose daemon on tcp://localhost:2375 without TLS` 

What needs to be done to make it work if it is even possible?

Got this in log:
```
[11:36:56] debug Using docker command 'docker'
[11:36:56] debug Use docker environment variables: [DOCKER_HOST=host.docker.internal]
[11:37:13] info find dev container: docker ps: error during connect: Get "http://host.docker.internal:2375/v1.24/containers/json?all=1": dial tcp 192.168.1.110:2375: connectex: No connection could be made because the target machine actively refused it.
[11:37:13] info exit status 1
```

**What did you expect to happen instead?**  
To launch a devpod.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. Install DD4W 
2. Launch DevPod and configure a Docker provider with `Docker host` as host.docker.internal or localhost
3. Create a workspace with the docker provider

**Local Environment:**  
- DevPod Version: v0.3.7
- Operating System: windows 10 Pro
- ARCH of the OS: AMD64 

**DevPod Provider:**  
- Local/remote provider: docker 

**Anything else we need to know?**  
The Docker Desktop for Windows WSL2 integrated solution is different than running a pure docker engine installation inside a WSL2 distro, I guess that would work just fine, but I would like to use the DD4W docker.

**Comment by shanehughes1990** [comment]
@ktzsolt I have WSL2 docker desktop windows 11, works fine for me without needing any changes to either softwares.

![image](https://github.com/loft-sh/devpod/assets/31993465/9ec84c09-99f9-4356-a303-48857e4ab2e0)
![image](https://github.com/loft-sh/devpod/assets/31993465/c062b670-150f-4eeb-8b6a-01e2943ff28d)

**Comment by ktzsolt** [comment]
> Hi @ktzsolt, thanks for opening the issue. Does it work if you omit the `DOCKER_HOST` config altogether?

Yes it works now! Looks like it is a documentation issue then :) I didn't know that I should not write anything in the Docker Host field if I want to use my local Docker Desktop. Thanks!

**Comment by pascalbreuninger** [comment]
Perfect, glad we could sort this out. Thanks @shanehughes1990 for chiming in!

**Comment by shanehughes1990** [comment]
Yw, truth be told I was comming here anyway to file an issue for something else and saw this figured I'd help out.
