### ISSUE TITLE
VSCode Windows 11 doesn't open

### ISSUE THREAD

**Issue by shanehughes1990** [loft-sh/devpod#727]
**What happened?**  

Setup DevPod with docker provider and VSCode as the open button,

Everything boots up just fine when pressing the open button to the workspace it starts to load gets to the point of the code command and stalls.

![image](https://github.com/loft-sh/devpod/assets/31993465/00583649-38f2-42be-b2aa-ca2eb8133d70)

If I take that command and run it in PowerShell nothing happens the cursor just returns to new line, typing in `code .` for example still works fine and opens vscode in my current directory as expected so it's not a path issue.

**What did you expect to happen instead?**  

I would expect that VSCode opens to the directory of the dev container workspace like it does when you open with vscode browser.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

All I did was install devpod, setup docker provider (localhost), added the golang workspace template and tried to open with vscode.

My *`devcontainer.json`*:
Golang quickstart template

**Local Environment:**  
- DevPod Version: 0.3.7
- Operating System: windows 11
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: docker
- Default provider settings I just pressed docker and save

**Anything else we need to know?**  
Nope.

**Comment by shanehughes1990** [comment]
I was playing around with this and the only param that is causing the issue is the --folder-uri command. Take that away and it opens code (obv not in the workspace but opens)

**Comment by neogopher** [comment]
Hi @shanehughes1990 :wave: ,
This is a known issue on Windows and specifically with a recent version of vscode. We already have a [fix](https://github.com/loft-sh/devpod/pull/710) for this which will be available in the next release.

**Comment by shanehughes1990** [comment]
Oh perfect I will lookout for the update then, thanks 👍

**Comment by muraleee** [comment]
When would be a release with this fix be available? Thanks
