### ISSUE TITLE
SSH starting directory should be workspace directory

### ISSUE THREAD

**Issue by frangio** [loft-sh/devpod#730]
**What happened?**  

SSH into a workspace starts at user home directory (perhaps Docker image workdir).

**What did you expect to happen instead?**  

Current directory should automatically be the workspace directory.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

1. Create a workspace for Node.js
2. SSH into the workspace with `devpod ssh`
3. `pwd` will show `/home/node` as opposed to `/workspaces/<name>`

**Local Environment:**  
- DevPod Version: v0.3.7
- Operating System: linux & mac
- ARCH of the OS: AMD64 & ARM64 

**DevPod Provider:**  
- Localprovider: docker

**Anything else we need to know?**

**Comment by 89luca89** [comment]
Thanks @frangio 

That seems a reasonable thing to do :smile:

**Comment by vikashkumar2020** [comment]
Please assign me this issue, I want to contribute and resolve this

**Comment by frangio** [comment]
@89luca89 Do you have any ideas for how this should be fixed?

**Comment by frangio** [comment]
I was looking into this and I think this is the line that needs to be changed:

https://github.com/loft-sh/devpod/blob/d3899a54249e15ddf2ad0de7fd5a72f2a562c153/pkg/ssh/server/ssh.go#L334

But the workspace name or directory is not available in this scope as far as I can tell. What would you recommend? CC @FabianKramm since you have worked on this file recently.

Thanks.

**Comment by 89luca89** [comment]
> I was looking into this and I think this is the line that needs to be changed:
> 
> https://github.com/loft-sh/devpod/blob/d3899a54249e15ddf2ad0de7fd5a72f2a562c153/pkg/ssh/server/ssh.go#L334
> 
> But the workspace name or directory is not available in this scope as far as I can tell. What would you recommend? CC @FabianKramm since you have worked on this file recently.
> 
> Thanks.

Hi @frangio 
Yes there isn't the information at that point
Probably it's better to add a flag `--workdir` to the `cmd/ssh.go`, in order to give the directory ad specific command level
And default it to the workspace, so that if it's not specified we get the behaviour that we're searching for

**Comment by timnolte** [comment]
@frangio so after working on trying to get my Dev Container setup, that uses a `docker-compose.yml` file, working in GitHub Codespaces it seemed that I needed to use `/workspace` not `/workspaces`. Of course now [this line](https://github.com/loft-sh/devpod/blob/main/cmd/ssh.go#L377) doesn't work anymore. I can test out my recent changes again and try to go back to `/workspaces` to confirm but I wanted to flag whether we are certain that `/workspaces` is actually the standard. According to the Dev Container json specs they indicate `/workspace` in their example for `workspaceMount`. https://containers.dev/implementors/json_reference/

**Comment by timnolte** [comment]
I did some testing and it does appear that `/workspaces` is working properly in Codespaces. I'm going to confirm if this is also the case with VS Code with a local-only dev container.

**Comment by timnolte** [comment]
So VS Code does appear to still work, I think there is a bit of concern though as that directory can apparently be changed to anything through the configuration it would seem.

**Comment by pascalbreuninger** [comment]
@timnolte Did that change break your use case? [We should fall back to the home directory](https://github.com/loft-sh/devpod/blob/4cee98370d0c310679ccf1e6622e369b54c6082d/pkg/ssh/server/ssh.go#L362) in case we're not able to find the `/workspaces/$NAME` directory, essentially behaving as if the flag wasn't set at all.
