### ISSUE TITLE
Machine Provider | Azure | Support Premium SSD

### ISSUE THREAD

**Issue by solesensei** [loft-sh/devpod#732]
**Is your feature request related to a problem?**  

Right now you can't control VM disk type with devpod. For e.g. you can't select PremiumSSD, by default devpod creates VM with HDD.

**Which solution do you suggest?**  

Add possibility to choose disk type.

**Which alternative solutions exist?**  

**Additional context**  

related #731

**Comment by pascalbreuninger** [comment]
Hi @solesensei , sounds like a reasonable addition to the Azure Provider. Would you mind opening an issue [over at its repo](https://github.com/loft-sh/devpod-provider-azure)? I'll close this one in the main repo
