### ISSUE TITLE
Machine Provider | Azure | Support working with already created VMs

### ISSUE THREAD

**Issue by solesensei** [loft-sh/devpod#733]
**Is your feature request related to a problem?**  

I need to run a **workspace** on my Azure VM (called `devpod-my-vm`), which was created by me outside devpod provider.
I have devpod machine provider with the same name `my-vm`). Devpod sees the VM and even connects to it, but it can't create a workspace.

```bash
23:16:15 debug Run command provider command: ${AZURE_PROVIDER} command
23:16:35 debug done inject
23:16:35 debug done injecting
23:16:35 info Waiting for devpod agent to come up...
23:16:35 debug Inject Error: context deadline exceeded
23:16:35 debug done exec
23:16:38 debug execute inject script
23:16:38 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.4.0-alpha.4
23:20:26 fatal executing agent command: timeout waiting for instance connection: context deadline exceeded
```
Public ssh keys are valid. Used `~/.devpod/contexts/defaut/machines/my-vm/id_devpod_rsa.pub`

**Which solution do you suggest?**  

Make possible to work with your own VMs with devpod.

**Which alternative solutions exist?**  

**Additional context**  

Related #732 #731

**Comment by pascalbreuninger** [comment]
There are couple of steps involved in setting up a machine on azure for DevPod usage, see [the Azure Provider](https://github.com/loft-sh/devpod-provider-azure/blob/main/pkg/azure/create.go) for reference. 
Afaik connecting to a pre-existing VM via this provider isn't supported, that's something that the `ssh` provider excels at, though

**Comment by solesensei** [comment]
Thanks. SSH provider works just fine.
