### ISSUE TITLE
Create devcontainer.json manually by selecting a language

### ISSUE THREAD

**Issue by shanehughes1990** [loft-sh/devpod#736]
**Is your feature request related to a problem?**  
Yes

**Which solution do you suggest?**  
We have many many repos at this point, all of which don't have devcontainer.json file in it. it would be nice once you pick your local repo as the workspace dir, if you were also able to pick from the templates to create the devcontainer.json file in the existing repo if one is not present. Currently nothing happens you have to look through logs to find out that the workspace is erroring due to missing json file.

**Which alternative solutions exist?**  

**Additional context**

**Comment by pascalbreuninger** [comment]
Hi @shanehughes1990, thanks for opening an issue. Not sure I completely understand what you're trying to do. DevPod usually falls back to a generic image if it can't detect a `devcontainer.json`

**Comment by shanehughes1990** [comment]
What I hope to accomplish is to be able to open the repo without any devcontainer config in it. and update the spec in the workspace itself right now I have to open my repo it outside of devpod do the json config then add the workspace.

**Comment by pascalbreuninger** [comment]
Oh, I just saw you're using version `0.4.0-14` but that's incompatible with `0.3.7` because of internal DevPod <-> Agent communication changes. Could you try to use `0.3.7` and see if that solves your issue?

**Comment by shanehughes1990** [comment]
I was on latest pre-release because I wanted the open in vscode button to work 😆, the results 
of 3.0.7, same thing you can see no devcontainer json gets created and devpod just spins.
![image](https://github.com/loft-sh/devpod/assets/31993465/e62e6bd7-20cf-4e42-9a23-d9bd10b700b1)

**Comment by pascalbreuninger** [comment]
@shanehughes1990 should be fixed by #813 , will be included in next release
