### ISSUE TITLE
SSH Provider | Can't pull image from internal registry | UNAUTHORIZED

### ISSUE THREAD

**Issue by solesensei** [loft-sh/devpod#743]
**What happened?**  

```
devpod provider add ssh
>>> host: devpod@<vm-public-ip>
>>> done

devpod up internal.azurecr.io/image:tag --provider ssh

16:02:29 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.3.7
16:02:29 debug Run command provider command: ${SSH_PROVIDER} command
16:02:30 debug Received line after pong: done
16:02:32 debug done exec
16:02:32 debug done inject
16:02:32 debug done injecting
16:02:32 debug Done InjectAgentAndExecute
16:02:32 fatal executing agent command: agent error: No root required, because neither docker nor agent daemon needs to be installed
Use /home/devpod/.devpod/agent/contexts/default/workspaces/image-tag as workspace dir
GET https://internal.azurecr.io/oauth2/token?scope=repository%3Aimage%3Apull&service=internal.azurecr.io: UNAUTHORIZED: authentication required, visit https://aka.ms/acr/authorization for more information.
```

**What did you expect to happen instead?**  

As I singed to registry in on laptop and also signed in on VM, I expected image to be pulled.

**Local Environment:**  
- DevPod Version: 0.3.7
- Operating System: mac laptop / linux vm 

**DevPod Provider:**  
- Cloud Provider: azure
- Local/remote provider: ssh

**Comment by solesensei** [comment]
@89luca89 I used `devpod` user

**Comment by solesensei** [comment]
Hi @89luca89, any updates on this?

**Comment by solesensei** [comment]
I can connect to the VM
```
ssh devpod@<ip>
docker pull internal.azurecr.io/image:tag
```
Then `docker up` will work with this image. But it's not working otherwise.

**Comment by 89luca89** [comment]
Hi @solesensei 
I'm setting up an azure environment for this, because simply trying to reproduce with a private docker registry did not reproduce the issue
At this point I'm suspecting a problem in forwarding specifically the azure registry auth

**Comment by solesensei** [comment]
@89luca89 ok, please share the update after you try this.
