### ISSUE TITLE
SSH Provider and GPUs ?

### ISSUE THREAD

**Issue by solesensei** [loft-sh/devpod#744]
Is it possible to pass `--gpus=all` argument in devpod workspace with SSH provider?
I need to run a container with GPUs.

**Comment by solesensei** [comment]
I know I can do this with `.devcontainer.json`

```json
"runArgs": [
    "--gpus",
    "all"
]
```

But can I add arguments via terminal for custom image, like `devpod up custom-image --provider ssh [--gpus=all]`?

**Comment by pascalbreuninger** [comment]
@solesensei setting a devcontainer option from the `up` command is not possible right now, I'm afraid

**Comment by solesensei** [comment]
@pascalbreuninger for kubernetes provider it's possible to set GPU in `Resources` option and then devpod will create pod with all the right resources and will append argument `--gpus=all` if at least one GPU specified.

Can you make something similar to ssh provider?

**Comment by pascalbreuninger** [comment]
@solesensei That's not really a primary use case for the ssh provider in my opinion, so it's pretty low on the priority list. Feel free to contribute to the `[devpod-provider-ssh](https://github.com/loft-sh/devpod-provider-ssh), though
