### ISSUE TITLE
Link to linux targz broken

### ISSUE THREAD

**Issue by frkam** [loft-sh/devpod#745]
**What happened?**  
I've clicked to "Linux targz" at https://devpod.sh/docs/getting-started/install and got not found response https://github.com/loft-sh/devpod/releases/download/v0.3.7/DevPod_linux_amd64.tar.gz

**Comment by pascalbreuninger** [comment]
Hi @frkam , that's because we haven't had a stable official release with the tar.gz, we just introduced it today and it's part of the [`v0.4.0-alpha.5` prerelease](https://github.com/loft-sh/devpod/releases/tag/v0.4.0-alpha.5). Thanks for raising awareness though!
