### ISSUE TITLE
Terminating building a workspace

### ISSUE THREAD

**Issue by fehtemam** [loft-sh/devpod#747]
**Is your feature request related to a problem?**  
There is no way to terminate the process of building a workspace after it gets started. I get an error that tries to download agent from github.com/loft-sh/devpod and gives an Inject error but it keeps retrying and I have no way of terminating the workspace build process.

**Which solution do you suggest?**  
Have a button to cancel the build process when something is going wrong. An equivalent of ^+C

**Which alternative solutions exist?**  
Not sure. I had to quit the whole devpod app.

**Additional context**

**Comment by pascalbreuninger** [comment]
Hi @fehtemam, you're right, that's a long standing issue on the roadmap that we haven't had the time to tackle yet. Would you be interestd in contributing this?

Btw, what version are you on?

**Comment by fehtemam** [comment]
@pascalbreuninger Unfortunately I don't think I am in a position to contribute right now. I was testing it to see if I could use it as an alternative to gitpod and if I could then maybe I could also convince others to use it. I tested on version 0.4.0-14

**Comment by pascalbreuninger** [comment]
aside from the cancelling feature this sounds like a separate issue. What operating system/provider/workspace did you use?

**Comment by pascalbreuninger** [comment]
This has been added to DevPod with [v0.5.0](https://github.com/loft-sh/devpod/releases/tag/v0.5.0)
