### ISSUE TITLE
VS Code not Launching

### ISSUE THREAD

**Issue by robinhalabicki** [loft-sh/devpod#749]
**What happened?**  
Using the C Sharp Template with VS Code and both Azure and Docker providers, the devpod gets to this spot and stops

`[16:06:30] info Setup container...
[16:06:30] info Install extensions 'dbaeumer.vscode-eslint,ms-dotnettools.csharp,streetsidesoftware.code-spell-checker' in the background
[16:06:34] info Run 'ssh vscode-remote-try-dotnet.devpod' to ssh into the devcontainer
[16:06:34] info Starting VSCode...`

I can see the container running.   

I can Launch VS Code and Attach to Running Container and Open Folder from the /workspaces/vscode-remote-try-dotnet directory

**What did you expect to happen instead?**  
Launch VS Code

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Use the template and Create workspace

**Local Environment:**  
- DevPod Version: 0.3.7
- Operating System: windows 
- ARCH of the OS: AMD64 | ARM64 | i386 

**DevPod Provider:**  
- Cloud Provider:  azure 
- Local/remote provider: docker

**Comment by pascalbreuninger** [comment]
hey @robinhalabicki, is the `code` CLI installed on your machine?
If yes, can you try using the [latest prerelease version](https://github.com/loft-sh/devpod/releases/tag/v0.4.0-alpha.5) please? We've added a fix for vscode on windows a couple of weeks ago, might fix your problem as well

**Comment by robinhalabicki** [comment]
Thank you, prerelease worked!
