### ISSUE TITLE
ssh-provider: inject error permission denied

### ISSUE THREAD

**Issue by milton0825** [loft-sh/devpod#751]
**What happened?**  
```
$ devpod up envoy --debug
---
21:02:39 debug execute inject script
21:02:39 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.3.7
21:02:39 debug Run command provider command: ${SSH_PROVIDER} command
21:02:40 debug done exec
21:02:40 debug done inject
21:02:40 debug done injecting
21:02:40 debug Inject Error: xxx@aaa.bbb.ccc: Permission denied (publickey).

EOF
```

**What did you expect to happen instead?**  

No injection error

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
https://github.com/envoyproxy/envoy/tree/main/.devcontainer

**Local Environment:**  
- DevPod Version: v0.3.7
- Operating System: mac
- ARCH of the OS: intel

**DevPod Provider:**  
- Local/remote provider:  ssh

**Anything else we need to know?**  
- 
- Found the following folder on remote machine so there should be no ssh connection issue:
```
ls /tmp | grep devpod
devpod
```

**Comment by 89luca89** [comment]
Hi @milton0825 can you provide us the configuration of the ssh provider?
Thanks
