### ISSUE TITLE
Unable to run latest AppImage on Debian 11

### ISSUE THREAD

**Issue by mwild1** [loft-sh/devpod#752]
**What happened?**  

I downloaded the DevPod AppImage from the download page on the website today.

When I executed the downloaded AppImage, I encountered the following error (and many more similar):

```output
$ ./DevPod_linux_amd64.AppImage 
dev-pod: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by dev-pod)
```

**What did you expect to happen instead?**  

I expected it to run devpod.

I'm on Debian 11, which the website says is tested and supported. I was previously using the deb package.

I have libc 2.31.

**Local Environment:**  

- DevPod Version: Whatever is current on the website today (it doesn't say a version number on the website or in the filename, and it won't run so I can't check the version)
- Operating System: linux
- ARCH of the OS: AMD64

**Comment by 89luca89** [comment]
Hi @mwild1 can you try the 0.40alpha5 release?

I fear that the docs have been updated before the stable release
