### ISSUE TITLE
IntelliJ Version Bump

### ISSUE THREAD

**Issue by juliuslipp** [loft-sh/devpod#753]
IntelliJ 2023.2.3 is available, but devpod always uses 2023.1.1. Is there a config that could be changed or does this have to be updated in the repo? Couldn't find anything in the docs

**Comment by pascalbreuninger** [comment]
hey @juliuslipp, it needs to be updated for all jetbrains IDEs in a similar way to [intellij](https://github.com/loft-sh/devpod/blob/b4d4723d7dddfe9d25d308cc3e3a0cfbaafc12f1/pkg/ide/jetbrains/intellij.go#L12C7-L12C7)

**Comment by juliuslipp** [comment]
Great thanks @pascalbreuninger
