### ISSUE TITLE
ssh provider fails starting workspace

### ISSUE THREAD

**Issue by behrica** [loft-sh/devpod#754]
Starting a certain github workspace with ssh provider gives error:
```
executing agent command: agent error: No root required, because neither docker nor agent daemon needs to be installed
```

**What did you expect to happen instead?**  
Workspace should start successfully.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
```
devpod up --provider ssh  --ide none  --recreate https://github.com/behrica/try-langchain-opencity.git --debug

```

**Local Environment:**  
- DevPod Version: v0.4.0-alpha.5
- Operating System: Linux
- ARCH of the OS: i386 

**DevPod Provider:**  
- Local/remote provider: ssh

**Anything else we need to know?**  
With a docker provider it works.

**Comment by behrica** [comment]
Higher up ni teh logs it seems to me that the "docker build" failed , but I jave no error message:

```
15:02:55 info #14 38.25 Setting up libpython3-dev:amd64 (3.11.2-1+b1) ...
15:02:55 info #14 38.28 Setting up python3-setuptools (66.1.1-1) ...
15:02:55 info #14 38.99 Setting up python3.11-dev (3.11.2-6) ...
15:02:55 info #14 39.02 Setting up python3-wheel (0.38.4-2) ...
15:02:55 info #14 39.23 Setting up python3.11-venv (3.11.2-6) ...
15:02:55 info #14 39.31 Setting up python3.11-doc (3.11.2-6) ...
15:02:55 info #14 39.34 Setting up python3-pip (23.0.1+dfsg-1) ...
15:02:55 info #14 40.91 Setting up libjs-sphinxdoc (5.3.0-4) ...
15:02:55 info #14 40.94 Setting up python3-doc (3.11.2-1) ...
15:02:55 info #14 40.96 Setting up python3-venv (3.11.2-1+b1) ...
15:02:55 info #14 41.00 Setting up python3-dev (3.11.2-1+b1) ...
15:02:55 info #14 41.03 Processing triggers for man-db (2.11.2-2) ...
15:02:55 info #14 41.60 Processing triggers for libc-bin (2.36-9+deb12u1) ...
15:02:55 info exit status 1
15:02:55 info build image
15:02:55 info github.com/loft-sh/devpod/pkg/driver/docker.(*dockerDriver).buildxBuild
15:02:55 info 	/home/runner/work/devpod/devpod/pkg/driver/docker/build.go:294
15:02:55 info github.com/loft-sh/devpod/pkg/driver/docker.(*dockerDriver).BuildDevContainer
15:02:55 info 	/home/runner/work/devpod/devpod/pkg/driver/docker/build.go:74
15:02:55 info github.com/loft-sh/devpod/pkg/devcontainer.(*runner).buildImage
15:02:55 info 	/home/runner/work/devpod/devpod/pkg/devcontainer/build.go:306
```

(exit staus = 1)

And it works with provider docker, so the devcontainer spec does work, in general.

**Comment by behrica** [comment]
It my setup the workspace "https://github.com/pbialon/vscode-remote-try-node" does work, for information.

**Comment by pascalbreuninger** [comment]
Hey @behrica, could you try to run the ssh provider with the stable [`v0.3.7`](https://github.com/loft-sh/devpod/releases/tag/v0.3.7) release again please? There might be a version mismatch between the agent and the devpod version on your machine

**Comment by behrica** [comment]
I have the same issue on 0.3.7.

I seems to me that I might get an error message from a 'postCreateCommand' which is hidden by devpod. Could this be ?

**Comment by behrica** [comment]
I got it finally working. The root cause for the error was a failing "postCreateCommand".
Strangely it did work with provider docker...

**Comment by pascalbreuninger** [comment]
Mh I see. We don't actively hide it, no. How did you find out eventually?

**Comment by behrica** [comment]
Just poking arround.
But errors in postCreateCommand are indeed not logged, even in debug.

The repo has an invalid command here:
https://github.com/behrica/try-langchain-opencity-invalid/blob/76559acab97050985ced7766a799784a62fa73a0/.devcontainer/devcontainer.json#L39

but there is no error in here, except the "21:55:34 fatal executing agent command: agent error: No root required, because neither docker nor agent daemon needs to be installed"

```
devpod up --provider ssh  --ide none  --recreate https://github.com/behrica/try-langchain-opencity-invalid.git --debug
```

**Comment by behrica** [comment]
Closing this in favor of a more foussed:
https://github.com/loft-sh/devpod/issues/775
