### ISSUE TITLE
Complete Doc Review: Fix/Enhance doc issues for complete documentation files

### ISSUE THREAD

**Issue by syedzubeen** [loft-sh/devpod#755]
**What happened?**  
This reviews typos/grammatical enhancements for the entire docs for the Devpod

**What did you expect to happen instead?**  

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```
{
    "name": "...",
    ...
}
```

**Local Environment:**  
- DevPod Version: [use `devpod version`]
- Operating System: windows | linux | mac
- ARCH of the OS: AMD64 | ARM64 | i386 

**DevPod Provider:**  
- Cloud Provider: google | aws | azure | digitalOcean
- Kubernetes Provider: [use `kubectl version`]
- Local/remote provider: docker | ssh
- Custom provider: provide imported `provider.yaml` config file

**Anything else we need to know?**

**Comment by 89luca89** [comment]
Hi @syedzubeen 

Thanks for your work 
Could you please do everything in one single PR and close the others?

Thanks

**Comment by syedzubeen** [comment]
@89luca89  
Sure. Should I add the PR to this ticket or create a new issue and link it to that one, since this issue has now been marked closed?

**Comment by 89luca89** [comment]
@syedzubeen just link to this one, I'll reopen it

**Comment by syedzubeen** [comment]
Updated all changes to a single PR.
