### ISSUE TITLE
Does inactivity timeout with ssh provider work?

### ISSUE THREAD

**Issue by jablonski** [loft-sh/devpod#776]
**What happened?**  

I've set inactivity timeout for my ssh provider to 10m, but no container gets stopped after this time.

**What did you expect to happen instead?**  

I'm expecting that a container is shutdown after the specified time.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

- Using VSCode as IDE
- ssh-connection to a Ubuntu-VM

**Local Environment:**  
- DevPod Version: 0.3.7
- Operating System: mac
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: ssh

**Comment by pascalbreuninger** [comment]
Hi @jablonski , thanks for opening the issue. Did you close VSCode completely?

**Comment by jablonski** [comment]
Yes, I've closed VSCode, even put my laptop to sleep, but the containers are still running.

**Comment by jablonski** [comment]
Maybe it is relevant: I'm using the devpod-GUI.

**Comment by pascalbreuninger** [comment]
hm alright, thank you. The Desktop App shouldn't have an impact there. We'll look into it

**Comment by pascalbreuninger** [comment]
@jablonski are you still able to reproduce this? We weren't able to reproduce this

**Comment by jablonski** [comment]
Doesn't work for me, just checked again. No idea what might be causing the issue in combination with our setup using remotes based on Ubuntu 22.04.
