### ISSUE TITLE
Setup dev container in an existing running container

### ISSUE THREAD

**Issue by amitds1997** [loft-sh/devpod#782]
**Is your feature request related to a problem?**
I sometimes have a running container with lots of resources and I want to use that as up my devcontainer in that.

**Which solution do you suggest?**
Add a command `set-up` or a sub-command to `up` to start a workspace in an existing container. My guess is that this just needs to be exposed and most, if not all features are already present in the code base.

**Which alternative solutions exist?**
`devcontainer` CLI provides `devcontainer set-up` where you can pass a container ID to set it up as a devcontainer.

![Setup existing container as devcontainer using devcontainer CLI](https://github.com/loft-sh/devpod/assets/29333147/372d06ed-cb59-4472-9464-3749f4e94633)

**Additional context**
I looked at `devpod agent container setup` and it's description kind of says the same thing, but I'm not sure if it is supposed to be used directly or not. Also, I am unsure about what to pass in the `--setup-info` and `--workspace-info` options to make it work.

![devcontainer agent container setup command help output](https://github.com/loft-sh/devpod/assets/29333147/51e6837c-b678-465a-a0c8-7ace3c506ef8)

**Comment by pascalbreuninger** [comment]
Hi @amitds1997, sounds like an interesting addition. Would you be interested in contributing it?

**Comment by amitds1997** [comment]
Sure. Do we want to add this as a new top-level command or expose it as a sub-command?

**Comment by pascalbreuninger** [comment]
maybe something along the lines of `devpod up $CONTAINER_ID`? Not 100% sure if it's feasible but it's certainly the easiest to use

**Comment by amitds1997** [comment]
Just wanted to go over the approach that I am taking to get this done. Also raised draft PR while I am still ironing out the details. It should be usable in its current state though.

# Approach
Containers can be referred to by either their container ID or their name when setting them up.

## To setup a running container as dev container
Run `devpod up container:<container-id-or-name> <other-devpod-options>`. This should be enough to setup any running container as a dev container.

## How it works internally
Created a new workspace source called `Container`. On receiving container as a CLI argument, we set up an environment variable in the driver (currently only in the Docker driver) called `DEVPOD_RUNNING_CONTAINER_ID`. When searching for the container in the driver code, we check if this environment variable is set, and if yes, we search by the ID as well. Rest all of the flow remains the same.

## Setting workspace
The default workspace is set to `/` ([WORKDIR default](https://docs.docker.com/engine/reference/run/#workdir)). If a custom workdir is found, it is set (detected by `Config.WorkingDir`).

## Other changes
1. For `devpod delete`: We do not delete the container, since it was not created by DevPod.
2. For `devpod stop`: We do stop the container since it is now set up as a devcontainer, so it should be okay to stop the container since it can easily be restarted too. Can change this behaviour if the other alternate of not stopping seems better.
3. For `devpod up`: When run with `--recreate`, we error out since we are working with a container that was not built and started by us, so we do not have enough information to rebuild it.

## Sample workflow

`devpod up`:

https://github.com/loft-sh/devpod/assets/29333147/bcd7dfa3-907b-41e0-a50e-9355d062a553




`devpod delete` and `devpod list`:

https://github.com/loft-sh/devpod/assets/29333147/04ed96fe-9130-4019-a8f0-61b7b353af63

**Comment by pascalbreuninger** [comment]
@amitds1997 thanks for lining out the approach here, that's super useful 👍 

I see a bit of a problem with the `container:` prefix as the first argument to `devpod up`. There might be a problem where an `image:tag` string named `container:0.0.1` (for whatever reason) comes into play. Even if we keep the order in a way that it'll always resolve the image first, it adds extra confusion. 
I'd suggest to have this as a `--source` flag option only, so you'd do `devpod up $SOME_NAME --source container:ubuntu`

Having a environment variable to find the devcontainer is a bit too much magic imo, could you try to solve this via the `dev.containers.id` label on the container? We might need to patch the id properly when attaching to the running container.

**Comment by amitds1997** [comment]
Thanks for the review! Some follow up questions:

> I see a bit of a problem with the `container:` prefix as the first argument to `devpod up`. There might be a problem where an `image:tag` string named `container:0.0.1` (for whatever reason) comes into play. Even if we keep the order in a way that it'll always resolve the image first, it adds extra confusion. I'd suggest to have this as a `--source` flag option only, so you'd do `devpod up $SOME_NAME --source container:ubuntu`

Great point! I understand the confusion that could arise from `container:` syntax. And the `--source` flag is already supported 👍 

1a. Is there any other possible syntax that you would recommend just for ease of use. I cannot think of any standard syntax, so I doubt not.
1b. As far as I could understand from the codebase, `$SOME_NAME` usually provides the source from which the devcontainer would be built in a `devpod up` command. What would we pass in case we use `--source container:ubuntu` to build it. What do you think it should represent in the statement: `devpod up $SOME_NAME --source container:ubuntu`

> Having a environment variable to find the devcontainer is a bit too much magic imo, could you try to solve this via the `dev.containers.id` label on the container? We might need to patch the id properly when attaching to the running container.

If we want to attach to a running container, my assumption was that it may not always have the `dev.containers.id` label preset since this is something that we add when bringing up a container. One possibility was that we could search by the container ID or name but it would not be possible to do it without introducing changes in the Driver interface (I could not find a way to pass it down except the environment variable).

**Comment by pascalbreuninger** [comment]
If the `--source` flag is specified, `$SOME_NAME` will act like the `--name` flag does 👍 

> If we want to attach to a running container, my assumption was that it may not always have the dev.containers.id label preset since this is something that we add when bringing up a container.

If you `docker inspect` the container after attaching it to devpod, you'll see the `config.labels` includes `dev.containers.id`. Unfortunately it's currently wrong, so we'd have to fix that for alread running containers to match the workspace ID. But then we can find the container from the driver later on again

**Comment by amitds1997** [comment]
> If you `docker inspect` the container after attaching it to devpod, you'll see the `config.labels` includes `dev.containers.id`. Unfortunately it's currently wrong, so we'd have to fix that for alread running containers to match the workspace ID. But then we can find the container from the driver later on again

Are we suggesting that if a running container is found, we add this label to the returned configuration for such containers?

**Comment by pascalbreuninger** [comment]
yep

**Comment by pascalbreuninger** [comment]
yep

**Comment by amitds1997** [comment]
One last question around finding the container, our [driver interface](https://github.com/loft-sh/devpod/blob/96e5d0083911b4289fc2113cbf51eba0793861c3/pkg/driver/types.go#L11-L32) provides us `FindDevContainer` which only takes `workspaceID` as an argument. What would you suggest is the best way to pass it down to the underlying Driver.

1. One way was to use the environment variables but since that was too much magic so we are not going down that path.
2. I can pass down the <container-id>/<container-name> using the `workspaceID` field but there is no way down in the driver to identify if it is a container ID or fetch the workspace configuration inside the driver.
3. Change the driver interface to allow passing down that information since this container could also be say a k8s pod, similar to a docker container.

**Comment by pascalbreuninger** [comment]
The driver interfaces will use the workspace ID to find the actual container based on a label. So if we label the original, already running, container with the workspace ID, we should be able to detect it afterwards the same way we do with every other workspace.
That's how it might work in my mind at least :D

**Comment by amitds1997** [comment]
Yeah, I would love that workflow too, but the problem is that it is not possible to add a label to a running docker container :/ [Docker issue](https://github.com/moby/moby/issues/15496)

**Comment by pascalbreuninger** [comment]
Ah right, that's on me. I tested the feature with a devcontainer base image and it already had that label 🙃 
Regardless, an environment variable is a lot of magic here, this is much better suited to be part of the configuration the host sends to the agent like `devcontainer.UpOptions` imo.

**Comment by zhuoqun-chen** [comment]
Hi @pascalbreuninger, is there any example showing how I can use `devpod up` to attach to a running container inside a k8s pod and turn it into a DevPod Workspace?
