### ISSUE TITLE
Missing RPM release v0.4.0

### ISSUE THREAD

**Issue by p5** [loft-sh/devpod#783]
**What happened?**  

The most recent v0.4.0 is missing the RPM bundle that was included in previous releases.

**What did you expect to happen instead?**  

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Compare release artefacts from [v0.3.7](https://github.com/loft-sh/devpod/releases/tag/v0.3.7) and [v0.4.0](https://github.com/loft-sh/devpod/releases/tag/v0.4.0) and see missing RPM file.

**Anything else we need to know?**  

If this is expected, do you have any guidance for how we should install the UI on a Fedora/RHEL system?

**Comment by pascalbreuninger** [comment]
Hi @p5, we've made the decision to remove `deb` and `rpm` support for upcoming versions with #737 and instead provide a `.tar.gz` for all non-appimage use-cases.
The reason for this is that we've hit quite a few problems with linux package formats and don't have the bandwidth to support all of them. AppImage is supported by the desktop framework we use, the rest were custom builds we needed to maintain individually. 
With the tar you should have the option to build these yourself or in a fork if you really need them.
