### ISSUE TITLE
Azure Provider 

### ISSUE THREAD

**Issue by samhodgkinson** [loft-sh/devpod#786]
**What happened?**  

When selecting Azure as the provider I get 

Parse Provider: parse provider config: error converting YAML to JSON: yaml : line 141 could not find expected ':'

**What did you expect to happen instead?**  

To be able to select the Azure provider 

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Just try to add the Azure Provider 

**Local Environment:**  
- DevPod Version: v0.4.4
- Operating System: windows 
- ARCH of the OS: x64

**DevPod Provider:**  
- Cloud Provider: azure

**Anything else we need to know?**

**Comment by pascalbreuninger** [comment]
@samhodgkinson thanks for reporting, the issue should be fixed now
