### ISSUE TITLE
failure in port forwarding should fail `devpod ssh`

### ISSUE THREAD

**Issue by behrica** [loft-sh/devpod#793]
Failure in port forwarding should be more prominent, maybe even fail the `devpod ssh` command

I see this in `--debug` , which is for me too hidden.
```
16:40:13 debug Error port forwarding 7777: listen tcp 127.0.0.1:7777: bind: address already in use
16:40:13 debug Error port forwarding 12345: listen tcp 127.0.0.1:12345: bind: address already in use
```

**Comment by FabianKramm** [comment]
@behrica thanks for the issue, yes we should print this error to the regular console even in non-debug mode
