### ISSUE TITLE
Inactivity timeout stopping workspace although actively working in workspace

### ISSUE THREAD

**Issue by maplat1** [loft-sh/devpod#795]
**What happened?**  
I’ve the inactivity timeout set to e.g. 6 hrs. While I was actively working in the workspace it got stopped. Tried with different values and behavior is consistent

**What did you expect to happen instead?**  

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```
{
    "name": "...",
    ...
}
```

**Local Environment:**  
- DevPod Version: 0.4.0
- Operating System: Mac
- ARCH of the OS:  ARM64 

**DevPod Provider:**  
- Cloud Provider: none
- Kubernetes Provider: none
- Local/remote provider: local docker desktop
- Custom provider: 

**Anything else we need to know?**  using fleet 1.25 as ide

**Comment by FabianKramm** [comment]
@maplat1 sorry for the delay? Which provider are you using? Local docker desktop?
