### ISSUE TITLE
failed to solve: failed to compute cache key: `<file>` not found: not found

### ISSUE THREAD

**Issue by amitds1997** [loft-sh/devpod#796]
**What happened?**
Doing `devpod up .` on a previously working project no longer works. It errors out with the following error: `failed to solve: failed to compute cache key: "/requirements.txt" not found: not found`

**What did you expect to happen instead?**  
Devcontainer is set up.

**How can we reproduce the bug?** (as minimally and precisely as possible)
1. Verify that you have `0.4.0` using `devpod version`
2. Do `devpod up https://github.com/amitds1997/devpod-cache-issue`.

**Local Environment:**  
- DevPod Version: v0.4.0
- Operating System: mac
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Cloud Provider: Not applicable
- Kubernetes Provider: Not applicable
- Local/remote provider: docker
- Custom provider: Not applicable

**Anything else we need to know?**
Downgrading to devpod `v0.3.7` makes this work again.

**Comment by pascalbreuninger** [comment]
Hi @amitds1997 , thanks for opening the issue.
I'm not sure why this worked before because the docker context isn't set to the parent directory. [According to the spec](https://containers.dev/implementors/json_reference/#image-specific) it is in the `.devcontainer` directory by default.
If you adapt your `devcontainer.json` like [here](https://github.com/pascalbreuninger/devpod-cache-issue/blob/main/.devcontainer/devcontainer.json) it should work again

**Comment by amitds1997** [comment]
Thanks for the quick reply! That solves the problem indeed.

Just a quick follow up question, the spec you mentioned describes how to define build context for image/Dockerfile. For docker-compose, specifying build context in `docker-compose.yml` should work or is that something that is missing from the spec doc and we need to pass it in the `build.context` option?

I tried the same configuration (one without `build.context`) with VSCode and it worked. So, is this a quirk on their end too?

**Comment by pascalbreuninger** [comment]
It should also work when you set the context in the docker-compose file, although I think you'll need to set it to `..` as well, because the `.devcontainer` directory will always be the working directory

**Comment by amitds1997** [comment]
> It should also work when you set the context in the docker-compose file, although I think you'll need to set it to .. as well, because the .devcontainer directory will always be the working directory

This works but it would break the normal `docker compose up` workflow :/ I opened an issue in the spec repo to provide clarity on this: https://github.com/devcontainers/spec/issues/331.

Since we have a solution for this, I would close this issue, for now. Thanks again!

**Comment by pascalbreuninger** [comment]
thanks!
