### ISSUE TITLE
postCreateCommand with Windows local environment and Ubuntu machine line ending mismatch

### ISSUE THREAD

**Issue by cgravill** [loft-sh/devpod#801]
**What happened?**  

Created a new workspace using Docker (podman) provider against private GitHub repository.

```shell
...
[14:28:01] info Run command : bash .devcontainer/setup.sh...
[14:28:01] error .devcontainer/setup.sh: line 2: $'\r': command not found
...
```

(mismatched line endings)

**What did you expect to happen instead?**  

Create a new machine.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```
{
    "name": "...",
    "postCreateCommand": "bash .devcontainer/setup.sh",
    ...
}
```

**Local Environment:**  
- DevPod Version: v0.4.1
- Operating System: windows
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: podman

**Anything else we need to know?**  

I guess this is because my Git install on Windows (which I guess you use) is set to `autocrlf`, then that git repo is being directly shared into the machine?

I am able to use the setup with, for example, https://github.com/microsoft/vscode-remote-try-python which doesn't have a `postCreateCommand` to at least create the machine. That creates the machine and I can connect with VSCode.

**Comment by pascalbreuninger** [comment]
Hi @cgravill, thanks for opening the issue. To be honest, I see this more on the users responsibility than on DevPods, as we can't possibly know how you'll be using the `postCreateCommand`. Maybe a tool like [dos2unix](https://linux.die.net/man/1/dos2unix) could solve your problem:
`"postCreateCommand": "dos2unix .devcontainer/setup.sh; bash .devcontainer/setup.sh`

Of course you'd have to bake `dos2unix` into your image first

**Comment by pascalbreuninger** [comment]
We're not using the host config for `autocrlf`, only for the email and the credential helper. Setting `core.autocrlf=false`, `core.eol=lf` and gitattributes `text=auto` pre-clone would definitely be an option. I'd have to test these combinations a bit though, do you have an open source git repo with CRLF line endings with a devcontainer.json by chance?

**Comment by sansmoraxz** [comment]
Alternatively you may try dumping your latest changes in a git stash, open the folder in devcontainer, discard all changes in the container and then pop the stash.

IMO this seems a lot cleaner than messing with gitattributes or autocrlf config.

**Comment by cgravill** [comment]
> We're not using the host config for `autocrlf`, only for the email and the credential helper. Setting `core.autocrlf=false`, `core.eol=lf` and gitattributes `text=auto` pre-clone would definitely be an option. I'd have to test these combinations a bit though, do you have an open source git repo with CRLF line endings with a devcontainer.json by chance?

Sorry for the delay. I checked and our repository is stored as LF

```sh
git show HEAD:README.md | file -
/dev/stdin: ASCII text
```
It's specifically `core.autocrlf=false` that I guess would help. Is it something we can inject ourselves in the devpod delivery process?

**Comment by cgravill** [comment]
> Alternatively you may try dumping your latest changes in a git stash, open the folder in devcontainer, discard all changes in the container and then pop the stash.
> 
> IMO this seems a lot cleaner than messing with gitattributes or autocrlf config.

Thanks for the suggestion, I'm not quite following though. We're doing a fresh checkout without changes. We don't actually have any plans to change the files directly on the Windows host it's just a side effect of getting the code there.

**Comment by sansmoraxz** [comment]
AFIK if you are loading a local folder it just streams the contents as is. It doesn't really manipulate the contents with git. Hell it will even copy the `.git` folder.

If you had any uncommitted changes that were made in your windows, you can have those stashed manually earlier.

Once you do a `git reset` in the container it will reset the changes to `HEAD` commit. Interesting thing is it will follow the `crlf` conventions within the container. Same while popping the stash.


Although reading the issue again, I think this has to be handled by devpod itself as postCreateCommand runs before any user interaction.

As a best practive I would suggest is having a `.gitattributes` for posix shell script. Those should always end with LF. Same with powershell which should end with CRLF.

Otherwise manually change your the line endings for .sh files before creating the container.

**Comment by cgravill** [comment]
> AFIK if you are loading a local folder it just streams the contents as is. It doesn't really manipulate the contents with git. Hell it will even copy the `.git` folder.
> 
> For windows the default behaviour of crlf is auto, ie clones always use crlf unless specified or configured separately.
> 
> If you had any uncommitted changes that were made in your windows, you can have those stashed manually earlier.
> 
> Once you do a `git reset` in the container it will reset the changes to `HEAD` commit. Interesting thing is it will follow the `crlf` conventions within the container. Same while popping the stash.
> 
> Although reading the issue again, I think this has to be handled by devpod itself as postCreateCommand runs before any user interaction.
> 
> As a best practice I would suggest is having a `.gitattributes` for posix shell script. Those should always end with LF. Same with powershell which should end with CRLF.
> 
> Otherwise manually change the line endings for .sh files before creating the container.

Thanks! Putting a `.gitattributes` is a very sensible workaround. I'll try that with the repository.

That's also an interesting note about `git reset` respecting `crlf` configuration.

**Comment by cgravill** [comment]
Just to note using `.gitattributes` to force LF worked around the issue. To be explicit for others:

```
*.sh eol=lf

```
So we're unblocked on this, though it'd be great to work without adjustments.

Thanks again for the suggestion @sansmoraxz
