### ISSUE TITLE
Image override

### ISSUE THREAD

**Issue by kfox1111** [loft-sh/devpod#810]
**Is your feature request related to a problem?**  
Yes. When on an isolated network, you may need to specify an alternative source of:
ghcr.io/loft-sh/dockerless:0.1.4

**Which solution do you suggest?**  
add a field to the configuration of docker/k8s drivers to allow specifying an alternate source for the image.

**Comment by pascalbreuninger** [comment]
Hi @kfox1111 , thanks for opening this issue. We do understand the need for this in special conditions, but you can't plug in any arbitrary image, it'd have to be either based on `loft-sh/dockerless` or built from the same [Dockerfile](https://github.com/loft-sh/devpod-provider-dockerless/blob/main/image/Dockerfile). As long as you're aware of that we could add a flag to use your custom image

**Comment by kfox1111** [comment]
We regularly use skopeo with gitlab to mirror images to self hosted registries (https://github.com/pnnl-miscscripts/gitlab-lib/blob/v1/gitlab-lib.yaml#L1) so mirroring in dockerless shouldn't be a problem.

**Comment by FabianKramm** [comment]
@kfox1111 this is now possible with the latest kubernetes provider release, there is a new option `DOCKERLESS_IMAGE` that lets you override the dockerless image that is pulled
