### ISSUE TITLE
Question: Why not using the official devcontainer CLI?

### ISSUE THREAD

**Issue by aledbf** [loft-sh/devpod#816]
👋 Hi,

I am just curious about why build a new implementation and not use the official one? Is the language?
Are there any missing features? (I only see a mention of userEnvProbe)
Thanks!

**Comment by FabianKramm** [comment]
Hey @aledbf! There are multiple reasons for that:
* Official devcontainer cli requires nodejs to be installed which is a requirement we don't want to enforce on the target we want to run the devcontainer on
* We can extend the standard through the customizations devcontainer.json property
* We can support more drivers than just docker (dockerless, kubernetes, ECS etc.)
Hope that helps!

**Comment by aledbf** [comment]
@FabianKramm thank you!
