### ISSUE TITLE
gpg forwarding bug - git user.signingkey configuration not transferred

### ISSUE THREAD

**Issue by srudolph-credera** [loft-sh/devpod#824]
**What happened?**  
I tried out the new GPG agent forwarding feature and when I tried to commit a change, I got the following error:

```
error: gpg failed to sign the data:
gpg: skipped <redacted>: No secret key
[GNUPG:] INV_SGNR 9 <redacted>
[GNUPG:] FAILURE sign 17
gpg: signing failed: No secret key
```

**What did you expect to happen instead?**

I expected my git commit to be signed successfully. Instead I had to first run `git config --global user.signingkey <redacted>` within the devcontainer environment to mirror my local setup.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

A full reproduction requires setting the host up to use commit signing and then trying to do so from within the devcontainer. However, a much quicker reproduction is simply adding a dummy value for the host's global Git user.signingkey config and observing that it is not copied over automatically to the devcontainer's global git config alongside the user.name and user.email values.

I believe user.signingkey needs to be copied over in pkg/gitcredentials/gitcredentials.go.

**Local Environment:**  
- DevPod Version: v0.4.2
- Operating System: mac
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: ssh

**Anything else we need to know?**  

That's it!

**Comment by pascalbreuninger** [comment]
Hey @srudolph-credera, thanks for opening the issue. You're right, we should set the config as well
