### ISSUE TITLE
Add support for devcontainer up --secrets-file

### ISSUE THREAD

**Issue by alexef** [loft-sh/devpod#827]
**Is your feature request related to a problem?**  

yes

**Which solution do you suggest?**  

The workspace configuration should allow configuring a secrets file. This should be passed to the `devcontainer up` invocation, regardless of provider.

**Which alternative solutions exist?**  

None.

**Additional context** 

This would enable us to more easily control secrets (as opposed to https://devpod.sh/docs/developing-in-workspaces/environment-variables-in-devcontainer-json). We need secrets at runtime and during prebuilds, for accessing external systems like Codeartifact.

**Comment by pascalbreuninger** [comment]
Hey @alexef, thanks for your suggestion. Would be a nice QoL improvement, would you be interested in contributing it?

**Comment by alexef** [comment]
of course, I would need some pointers as I haven't yet contributed to devpod.

**Comment by pascalbreuninger** [comment]
Not sure if it'll work for your prebuild use-case. But for the runtime variables you could parse the secrets file during `devpod up` and convert it into a series of [`--workspace-env` flags](https://github.com/loft-sh/devpod/blob/1a3341f8f06e839077ef65b30e6a0c7ad0ccdf33/cmd/up.go#L130C43-L130C43)
