### ISSUE TITLE
Ability to change machine type / spec

### ISSUE THREAD

**Issue by sansmoraxz** [loft-sh/devpod#831]
**Is your feature request related to a problem?**  
No

**Which solution do you suggest?**  
We should be able to resize the instances created by the provider.

Through CLI something like (assuming an AWS Instance):
```sh
devpod machine set-options "$machinename" --option AWS_INSTANCE_TYPE="inf1.xlarge"
```

which would internally invoke the AWS API like this:-

```sh
aws ec2 modify-instance-attribute \
                   --instance-id "$machineid" \
                   --instance-type "{\"Value\":\"inf1.xlarge\"}"
```

Similar things can be pulled off iwth docker and kubernetes.

**Which alternative solutions exist?**  
In Codespace, we can adjust instance type pretty easily.
![image](https://github.com/loft-sh/devpod/assets/31374920/13bbb9f7-1056-464a-a912-212839f96e1f)

**Additional context**  

Edge case:

- Some providers such as AWS do require instances to be stopped before the instance size can be changed.
- Haven't gone into dept for all providers, but not all providers may support this functionality.

**Comment by pascalbreuninger** [comment]
Hi @sansmoraxz, thanks for opening the issue. 
This would definitely make for a way better user experience. Right now you'd either have to edit the provider to use another instance type or clone the existing provider using `devpod provider add --from-existing=aws ...`, then set the instance type and create a new workspace with the new provider. 
Out of curiosity: How often did you have to resize the machine so far?

**Comment by sansmoraxz** [comment]
Implementing an API for exposing machine metadata might be a pre-requisite here.

**Comment by minhio** [comment]
The way i've implemented this in my multipass machine provider is to put the logic to update the instance specs within the Start command. The logic is of course different depending on the provider. For example, in the case of AWS, you can do something like this prior to starting the instance

```
if instance state == stopped && instance specs need updating {
    update specs
}
```
