### ISSUE TITLE
Remote Linux Docker from Windows DevPod : mount path must be absolute.

### ISSUE THREAD

**Issue by mikecarr** [loft-sh/devpod#834]
**What happened?**  
Launching a devcontainer from Windows UI to remote Desktop server returns error: info docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: 'C:/Users/MCarr1/.devpod/agent/contexts/default/workspaces/vscode-remote-try-go/content' mount path must be absolute.
(see attached debug log)
[devpod-windows-absolute-path.log](https://github.com/loft-sh/devpod/files/13590416/devpod-windows-absolute-path.log)

**What did you expect to happen instead?**  
I expected the workspace to be deployed to the remote Docker host

**How can we reproduce the bug?** (as minimally and precisely as possible)  
* Setup Docker Provider with remote host (or port that is port forwarded to Docker host) i.e. localhost:2375
*  port forward localhost 2375 to remote Docker host
   `ssh -L2375:localhost:2375 remote-dockerhost.com`
* Create any workspace with Docker provider

**Local Environment:**  
- DevPod Version: 0.4.2
- Operating System: Windows
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: docker | ssh

**Anything else we need to know?**  
The host that Devpod is running is Windows, the host where Docker is running is linux

**Comment by mikecarr** [comment]
Attaching command line from Linux debug log which results in same error

[devpod-linux-absolute-path.log](https://github.com/loft-sh/devpod/files/13590923/devpod-linux-absolute-path.log)

**Comment by mikecarr** [comment]
The SSH provider does what I want

**Comment by 89luca89** [comment]
Hi @mikecarr this probably could be linked to the #808 issue, probably same path conversion problem

**Comment by samhodgkinson** [comment]
I know this is an old issue, but I'm seeing it from Windows 11 to Ubuntu 24.10.  Was there a resolution to this or suggestion on how this is resolved ?

Version 0.5.18

while sleep 1 & wait $!; do :; done -
[23:47:57] info docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: 'C:/Git/SSH/Datadog/Datadog' mount path must be absolute.
[23:47:57] info See 'docker run --help'.
[23:47:57] info exit status 125
[23:47:57] info start dev container
