### ISSUE TITLE
Can't find VSCode because I use code-insider from a tarball

### ISSUE THREAD

**Issue by rajinder-yadav** [loft-sh/devpod#842]
**Is your feature request related to a problem?**  
Yes

**Which solution do you suggest?**  
Allow me to point to the path where I have VSCode Insider installed from a tarball.

**Which alternative solutions exist?**  
VSCode installed to system or VSCode in browser both which I don't want to use.

**Additional context**  
Checking out DevPod for first time

**Comment by pascalbreuninger** [comment]
Hi @rajinder-yadav, thanks for opening the issue. I haven't tried it but it might be enough for you to alias the `vscode` command to your vscode insider installation

**Comment by rajinder-yadav** [comment]
I suggesst a solution of looking first to see if a "EDITOR" environment varaible is set and to use this, or to define it in some configuration file or settings.

**Comment by pascalbreuninger** [comment]
I'm not sure this is related to the issue you opened, but it's a great idea for auto suggesting an IDE or fall back to it if not specified in the CLI commands

**Comment by pascalbreuninger** [comment]
@rajinder-yadav DevPod now supports VSCode insider natively
