### ISSUE TITLE
Configure GCP provider with IAP tunnel instead of external IP

### ISSUE THREAD

**Issue by Myrz** [loft-sh/devpod#847]
**Is your feature request related to a problem?**  
This feature is related to a security problem.
For security reasons, it's not recommended to provided a GCP Compute Engine with an external IP.

**Which solution do you suggest?**  
A better pratice is to use Identity-Aware-Proxy tunnel, but unfortunatly there's no option to configure that in devpod.

**Which alternative solutions exist?**  
An alternative is to configure a ssh provider, and set the right options to use the IAP tunnnel. But there is also a problem.
Actually here's the right ssh command:

`ssh -t -i C:/Users/xxx/.ssh/google_compute_engine_rsa_key.pri -oProxyCommand="\"C:/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/platform/bundledpython/python.exe\" -S \"C:/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/lib/gcloud.py\" compute start-iap-tunnel devpod-env 22 --listen-on-stdin --project=xxx-yyy-dev --zone=europe-west1-b --verbosity=warning" xxx_yyy_com@compute.zzz`

This ssh command allows me to connect to an Compute Engine instance with a Windows Terminal. 
But when I set the ssh provider I get this error.

**error: ssh output mismatch**

![image](https://github.com/loft-sh/devpod/assets/32385346/81f9c7e8-5ecc-45fe-9767-0d126f862fdc)

So my first request is to directly configure IAP through the GCP provider, and maybe if it takes too long, have a quick workaround to connect with ssh at my Compute Engine's instance. 

**Additional context**  

Windows 10
GCP Compute Engine

**Comment by pascalbreuninger** [comment]
Thanks for opening the issue @Myrz. I'd defer this to an [open issue in the gcloud provider repo](https://github.com/loft-sh/devpod-provider-gcloud/issues/3#issue-1863853368)
