### ISSUE TITLE
.devpod/contexts/default/providers/.DS_Store/provider.json: not a directory

### ISSUE THREAD

**Issue by minhio** [loft-sh/devpod#852]
**What happened?**  
Adding a provider produce a strange error. But only after navigating to and exploring the `~/.devpod` directory from Finder.

<img width="1005" alt="Screenshot 2023-12-23 at 3 48 00 PM" src="https://github.com/loft-sh/devpod/assets/983465/c4b3fef5-e609-4118-9164-716d155c09f4">

**What did you expect to happen instead?**  
Being able to add provider.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
- given that the `~/.devpod` directory does not exist, and no providers have been added
- add a docker provider using the GUI (expect no errors, and `~/.devpod` dir created)
- use Finder, navigate to the `~/.devpod/contexts/default/providers/docker` dir
- add an AWS provider using the GUI (expect error to happen here)
- only way to fix is to delete the `~/.devpod/contexts/default/providers` directory

**Local Environment:**  
- DevPod Version: v0.4.2
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Cloud Provider: issue is not specific to a provider
- Kubernetes Provider: N/A
- Local/remote provider: docker
- Custom provider: N/A

**Comment by jmdacruz** [comment]
Run into this very same issue :)

**Comment by pascalbreuninger** [comment]
Thanks for opening the issue, should be fixed by #854. Until it is released you can also remove the `.DS_Store` folder manually via the CLI `rm -r ~/.devpod/contexts/default/providers/.DS_Store`
