### ISSUE TITLE
VSCode not starting in Ubuntu 22.04

### ISSUE THREAD

**Issue by pedro93** [loft-sh/devpod#860]
**What happened?**  
VSCode is not started by DevPod in Ubuntu 22.04

**What did you expect to happen instead?**  
Expected VS Code to start with a remote ssh connection to the devcontainer started by DevPod.

**How can we reproduce the bug?** (as minimally and precisely as possible)
In a fresh Ubuntu 22.04.3 with docker installed:
- Install VSCode via snap `sudo snap install --classic code` (version installed is 1.85.1)
- Install DevPod via AppImage (must grant the executable permission to the binary file)
- Create a basic `alpine` devcontainer in a given folder under `.devcontainer/devcontainer.json`.
- Create a DevPod workspace for the aforementioned folder with the docker provider.
- VScode is not started.

My *`devcontainer.json`*:
```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/alpine
{
	"name": "Alpine",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/base:alpine-3.18"

	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "uname -a",

	// Configure tool-specific properties.
	// "customizations": {},

	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}
```

**Local Environment:**  
- DevPod Version: 0.4.2 (x86_64)
- Operating System: Linux - Ubuntu 22.04.3
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: docker

** Logs From DevPod **
![Screenshot from 2024-01-04 12-23-36](https://github.com/loft-sh/devpod/assets/3718654/67ee5c07-8f5f-4d3a-9f0d-c1a415fab931)

**Comment by pascalbreuninger** [comment]
hey @pedro93, can you use the `code` command from the CLI? It's a requirement for opening VSCode from DevPod.
If not, could you enable debug logs and paste the output here please?

**Comment by pedro93** [comment]
> hey @pedro93, can you use the `code` command from the CLI? It's a requirement for opening VSCode from DevPod. If not, could you enable debug logs and paste the output here please?

From the terminal you mean? Yes I can.

How can I enable debug logs?

**Comment by pascalbreuninger** [comment]
in `settings > general > debug`

**Comment by pascalbreuninger** [comment]
@pedro93 we just discussed this problem internally and it's related to the way `snap` installs packages. We don't think taking on the maintenance burden for these kinds of package manager is feasible right now.

However, as a workaround you could install VSCode via [flatpak](https://flathub.org/apps/com.visualstudio.code)

**Comment by pedro93** [comment]
Sounds good,
Thank you for the support!

**Comment by thediveo** [comment]
Considering the many warnings included in the unofficial flatpack package, I find your recommendation very worrisome.
