### ISSUE TITLE
If two developers want to enter the same workspace, is there any simple and fast way?

### ISSUE THREAD

**Issue by LiuuuSY** [loft-sh/devpod#861]
If providers use ssh, is there any way for two developers to enter the same workspace and operate the project?

**Comment by pascalbreuninger** [comment]
Hi @LiuuuSY, not really, at least not a straight-forward one. Technically you should be able to have one person start the workspace, connect the other manually to the remote machine using SSH and then `docker exec` into the container. 
Alternatively you could expose the `DOCKER_HOST` of the remote to a docker provider and then let the second person connect to an already existing workspace by attaching to the running container `devpod up $WORKSPACE_NAME --source=container:$CONTAINER_ID` (courtesy of @amitds1997)

Sidenote: Shared cloud workspaces is a feature of our commercial offering DevPod.Pro
