### ISSUE TITLE
Some questions about providers and ssh

### ISSUE THREAD

**Issue by LiuuuSY** [loft-sh/devpod#862]
When the provider is ssh, does it also support username and password login in addition to public key and private key authentication?

**Comment by LiuuuSY** [comment]
> @LiuuuSY if you specify the `HOST` option as `user@host` and no key can be used it should fall back to prompt for a password afaik

Sorry, I may not have expressed my meaning clearly. What I want to ask is if the provider of devpod is ssh, can I use a password instead of a private key to connect?

**Comment by 89luca89** [comment]
Hi @LiuuuSY 
We only support ssh keys authentication

Password prompt is not supported nor we're planning it
