### ISSUE TITLE
【BUG】DEVPOD can't connect server via ssh with a ssh key file which need  passphrase.

### ISSUE THREAD

**Issue by DaiQiangReal** [loft-sh/devpod#870]
**What happened?**  

DEVPOD can't connect server via ssh with a ssh key file which need passphrase, by the way, it is ok with the cli. But after connected, the cli still can't work because it require 'sudo' with no password prompt to input if the account of the remote mechine is not root.

**What did you expect to happen instead?**  

**How can we reproduce the bug?** (as minimally and precisely as possible)  

**Local Environment:**  
- DevPod Version: [use `devpod version`]
- Operating System: windows 
- ARCH of the OS:  i386 

**DevPod Provider:**  
- Cloud Provider: google | aws | azure | digitalOcean
- Kubernetes Provider: [use `kubectl version`]
- Local/remote provider: ssh

**Anything else we need to know?**  
![image](https://github.com/loft-sh/devpod/assets/29626873/538e62d1-5e71-43a3-9fcb-b5bb347cdadb)

**Comment by pascalbreuninger** [comment]
Hi @DaiQiangReal , thanks for reporting the issue. We'll look into it

**Comment by 89luca89** [comment]
Hi @DaiQiangReal 
The ssh-key passphrase  can be stored in a keyring, like it's done on MacOS and Linux

In your case, you should find a Windows solution for this

Like for username and password logins, we've decided to not store internally any authentications for security purposes
