### ISSUE TITLE
OSX App keeps running in background

### ISSUE THREAD

**Issue by msander** [loft-sh/devpod#872]
**What happened?**  
I have used DevPod on OSX. After closing the App, the process keeps running in the background. There is no window open.
When I click the DevPod Icon again, nothing happens. After killing the process, I can open the DevPod App again.

**What did you expect to happen instead?**  
Either the process needs to stop after closing the app, or a new window should open if the process needs to keep running in the background.

**Local Environment:**  
- DevPod Version: 0.4.2
- Operating System: mac
- ARCH of the OS: ARM64 

**DevPod Provider:**  
- Local/remote provider: docker

**Comment by pascalbreuninger** [comment]
Hi @msander, the application lives on in your system tray (or menu bar in macOS terms).
If you want to bring up a new window from that mode, click "Show Dashboard" after clicking on the DevPod system tray icon.
The fact that it doesn't open another window if you click the Icon on your Desktop or Launcher is a quirk of the framework we use for the Desktop Application, let's see if we can improve in the future
