### ISSUE TITLE
Crowdstrike is blocking you as malware

### ISSUE THREAD

**Issue by mikebell90** [loft-sh/devpod#880]
Just fyi - downloaded latest mac aarch64

**Comment by pascalbreuninger** [comment]
@mikebell90 Thanks for the info, good to know! Let's see what we can do about this. Our certificates should all be solid, got to investigate what their criteria for malware is 🤷‍♂️

**Comment by mikebell90** [comment]
Just that they flagged it for suspicious behaior. My sec team made an exemption for me, so this is just a heads up
