### ISSUE TITLE
GPG_AGENT_FORWARDING with docker-in-docker feature breaks ssh

### ISSUE THREAD

**Issue by josmo** [loft-sh/devpod#881]
**What happened?**  
When settings `devpod context set-options default -o GPG_AGENT_FORWARDING=true` and using the feature `"ghcr.io/devcontainers/features/docker-in-docker:2": {}` trying to ssh to the workspace results in the error
```
7:20:50 info gpg: directory '/home/vscode/.gnupg' created
17:20:50 info gpg: keybox '/home/vscode/.gnupg/pubring.kbx' created
17:20:50 info gpg: /home/vscode/.gnupg/trustdb.gpg: trustdb created
17:20:50 info Reverse forwarding local unix//Users/me/.gnupg/S.gpg-agent.extra to remote unix//Users/me/.gnupg/S.gpg-agent.extra
17:20:51 fatal error forwarding /Users/me/.gnupg/S.gpg-agent.extra: EOF
kex_exchange_identification: Connection closed by remote host
```

**What did you expect to happen instead?**  
Should be able ssh into the workspace

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```
{
  "name": "kubevirt",
  "image": "mcr.microsoft.com/devcontainers/go:1.21-bullseye",

  "features": {
    "ghcr.io/devcontainers-contrib/features/sops:1": {},
    "ghcr.io/devcontainers/features/docker-in-docker:2": {}
  },

  "customizations": {
    "settings": {
      "remote.containers.copyGitConfig": true
    },
    "vscode": {
      "extensions": [
        "streetsidesoftware.code-spell-checker"
      ]
    }
  },
  "forwardPorts": [],
  "portsAttributes": {
  },
  "postCreateCommand": ""
}

```

**Local Environment:**  
- DevPod Version: v.0.5.0
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Cloud Provider: aws 
- Kubernetes Provider: 1.28
- Local/remote provider: ssh

**Anything else we need to know?**

**Comment by pascalbreuninger** [comment]
Hi @josmo, thanks for opening the issue! We'll look into it 👀
