### ISSUE TITLE
Inconsistent workspace status when stopped

### ISSUE THREAD

**Issue by akyriako** [loft-sh/devpod#883]
**What happened?**  

I start 3 identical workspaces in 3 different providers:

1. Docker
2. Azure
3. Open Telekom Cloud

I stop the providers, and the status message in the workspace windows is different for all 3 of them. The logs inside indicate that every workspace is stopped successfully, but only Docker has the expected status message: **Stopped**

**What did you expect to happen instead?**  

I would expect that the status of all workspaces is **Stopped**

**How can we reproduce the bug?** (as minimally and precisely as possible)  

1. Create a workspace from python example on a new machine for each provider 
2. As long as it is started, stop each one of them
3. Observe the status message of the workspace in the workspaces window

**Local Environment:**  
- DevPod Version: v0.5.0
- Operating System: windows | linux 
- ARCH of the OS: AMD64   

**DevPod Provider:**  
- Cloud Provider: azure 
- Local/remote provider: docker 
- Custom provider: akyriako/opentelekomcloud

**Anything else we need to know?**  

I attach 2 screenshot for more clarity:

![Screenshot from 2024-02-02 12-51-24](https://github.com/loft-sh/devpod/assets/3920167/93bde93d-f5df-4f33-8136-b7c3666180bd)

![Screenshot from 2024-02-02 12-51-43](https://github.com/loft-sh/devpod/assets/3920167/59915e94-e218-4967-ac09-579b4a5ca2b7)

**Comment by pascalbreuninger** [comment]
Thanks for reporting @akyriako, we'll have a look soon. If you have any pointers on why that might happen we'd highly appreciate it

**Comment by 89luca89** [comment]
@akyriako can you also print the output of the CLI command `devpod list`  and for each of them do a `devpod status` so we see if the CLI is reporting the status correctly?

Thanks!

**Comment by akyriako** [comment]
After upgrading to **v0.5.1**,UI status updates seem to have become more consistent and occur in a timely manner. I have tested it for ~1hr and I cannot conclusively decide if it is fixed or not. Please check at your end as well, but looks promising.

**Comment by 89luca89** [comment]
Hi @akyriako tried to reproduce for a long time but couldn't, I'd say this is fixed, if you can reproduce in a more precise and reproducible manner, let's reopen this issue then :+1:
