### ISSUE TITLE
Recreate option does not run dotfiles again in new container

### ISSUE THREAD

**Issue by flokoe** [loft-sh/devpod#884]
**What happened?**  
Devpod did not run dotfiles script after using `--recreate` option on up command.

Only deleting the existing workspace via `devpod delete` or manually deleting the `dotfiles` directory within the container/context content would run dotfiles again.

As dotfiles script is not run configs are missing in new container.

**What did you expect to happen instead?**  
Devpod runs dotfiles again if I recreate the container via `--recreate` option.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

```bash
devpod up github.com/microsoft/vscode-remote-try-node --ide none --dotfiles https://github.com/flokoe/dotfiles-devcontainer --dotfiles-script debug.sh 

# Run command again with --recreate
devpod up github.com/microsoft/vscode-remote-try-node --ide none --dotfiles https://github.com/flokoe/dotfiles-devcontainer --dotfiles-script debug.sh --recreate

# Output
17:39:53 info Workspace vscode-remote-try-node already exists
17:39:53 info Creating devcontainer...
17:39:53 info Deleting devcontainer...
17:39:53 info fc8af9bc14ff06ba8dd3c52950f5d36da087ab925f0b31a2e4f0777d8fae2573
17:39:54 info Setup container...
17:39:54 info Chown workspace...
17:39:54 info Run command : yarn install...
17:39:54 info yarn install v1.22.19
17:39:54 info [1/4] Resolving packages...
17:39:54 info success Already up-to-date.
17:39:54 info Done in 0.09s.
17:39:54 done Successfully ran command : yarn install
17:39:54 info Run 'ssh vscode-remote-try-node.devpod' to ssh into the devcontainer
17:39:54 info Dotfiles git repository https://github.com/flokoe/dotfiles-devcontainer specified
17:39:54 info Dotfiles script debug.sh specified
17:39:55 info dotfiles already set up, skipping
17:39:55 info Done setting up dotfiles into the devcontainer
```

**Local Environment:**  
- DevPod Version: v0.5.0
- Operating System: Debian Linux 12
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: docker

**Comment by 89luca89** [comment]
Hi @flokoe thanks for reporting!
I'll take a look at this :+1:
