### ISSUE TITLE
Can't to create workspace from private git repo with credential access token in custom url and branch custom

### ISSUE THREAD

**Issue by undercode99** [loft-sh/devpod#885]
**What happened?**  
I'm trying to create a git source workspace with an access token in the git URL and with a custom branch with example
```
devpod up myapp --source=git:https://username:xxxx@gitlab.com/test/aqua-demo.git@patch-v1  --provider ubuntu --ide none
```
And i got Authentication failed when clone repo
```
12:38:35 info Creating devcontainer...
12:38:50 info Cloning into '/home/xxx/.devpod/agent/contexts/default/workspaces/myapp/content'...
12:38:51 info remote: Unauthorized
12:38:51 info fatal: Authentication failed for 'https://gitlab.com/test/aqua-demo.git@patch-v1/'
12:38:51 error Cloning failed: error cloning repository: exit status 128. Trying cloning on local machine and uploading folder
12:38:51 info Cloning from host and upload folder to server
12:38:51 info cloning local folder: EOF
12:38:52 error Try using the --debug flag to see a more verbose output
12:38:52 fatal run agent command: Process exited with status 1
```
but when I don't use access token in url it works perfectly

**What did you expect to happen instead?**  
It should be the same when not using access token in url

**How can we reproduce the bug?** (as minimally and precisely as possible)  
```
devpod up myapp --source=git:https://$USERNAME:$ACCESSTOKEN_OR_PASSWORD@$REPO_URL@$BRANCH  --provider $SSH --ide none
```

**Local Environment:**  
- DevPod Version: v0.4.2
- Operating System: mac
- ARCH of the OS: ARM64 

**DevPod Provider:**  
- Local/remote provider:  ssh

**Anything else we need to know?**  
i use this for programmatically uses, it is not possible to use git credentials because of some reasons, so i need that feature

**Comment by pascalbreuninger** [comment]
Hey @undercode99, we are a bit hesitant to implement this because this is a potential security concern. We do save the resolved repository in the `DEVPOD_HOME` folder for reuse. With credentials included everyone with access to this file also has access to your git repo.
One remedy we were thinking about it to put a **big, fat warning** log message in the CLI and pause the execution for 60 seconds. Would you be fine with that?

**Comment by pascalbreuninger** [comment]
closing due to staleness, feel free to reopen if you can still repro

**Comment by loonfly** [comment]
hi guys, I don't know what's the status for this currently. but "One remedy we were thinking about it to put a big, fat warning log message in the CLI and pause the execution for 60 seconds. Would you be fine with that?" this seem make sense. 

for example, my case, I am a solo developer and no one else would have access to my laptop, therefore I believe it is very safe for my to have git url something like "https://username:xxxx@gitlab.com/test/aqua-demo.git"

**Comment by tobi1220** [comment]
Does DevPod currently not support using a PAT for cloning over HTTPS for the creation of a workspace?
