### ISSUE TITLE
SFTP sync from local to remote machine

### ISSUE THREAD

**Issue by famagusta** [loft-sh/devpod#889]
We are trying to setup devpods for our dev environment. We are using aws provider with docker-compose
We are trying to setup a sync between local folder and the remote machine. From the remote machine we will
sync the folder by mounting the volume to the docker containers. This will help retaining a copy of changes in local
machine in the event of accidental workspace deletions. This also allows us to do dev in local environments and
sync the code to devpod using sftp sync plugin in vscode.

Using the devpod cli (devpod machine list), we are able to get the machine name but unable to figure out the
ssh command being used or where the keys are stored.

Below is our devcontainer.json

`{
	"name": "<SERVICE>",
	"dockerComposeFile": "docker-compose.dev.yaml",
	"service": "hobbit",
	"workspaceFolder": "<SERVICE_FOLDER>",
	"initializeCommand":"docker build -t <SERVICE> .",
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	"forwardPorts": [
		8000, 8080, 80, 8114, 8115, 3306, 3307, 5432, 5433
	],
	"customizations": {
		"vscode": {
		  "extensions": [
			"ms-python.python",
			"mtxr.sqltools",
			"mtxr.sqltools-driver-pg"
		  ]
		}
	  }
}
`

**Comment by 89luca89** [comment]
Hi @famagusta 

The keys are stored in  `~/.devpod/contexts/default/machines/${machine-name}`, and you can use `devpod machine ssh` to access them directly

**Comment by famagusta** [comment]
Thanks. This was super helpful
