### ISSUE TITLE
Environment Variable to Detect Devcontainer

### ISSUE THREAD

**Issue by natescherer** [loft-sh/devpod#891]
Hello! I wanted to make a suggestion that DevPod inject an environment variable that would allow scripts to detect they are running inside a devcontainer. VS Code did this [here](https://github.com/microsoft/vscode-remote-release/issues/3517) via setting REMOTE_CONTAINERS=true, doing the same would be convenient, maybe even adding DEVPOD=true to boot.

Thanks for a great product!

**Is your feature request related to a problem?**  
No

**Which solution do you suggest?**  
Inject the following env vars:
REMOTE_CONTAINERS=true
DEVPOD=true

**Which alternative solutions exist?**  
None I'm aware of.

**Additional context**

**Comment by pascalbreuninger** [comment]
Hi @natescherer, good idea, will add it! In the meantime if you depend on knowing you're in a devcontainer your could add a workspace environment variable via `devpod up ... --workspace-env=DEVPOD=true`
