### ISSUE TITLE
Publish devpod to the AUR

### ISSUE THREAD

**Issue by IgnisDa** [loft-sh/devpod#894]
**Is your feature request related to a problem?**  

It would be great if Devpod was available on the [AUR](https://aur.archlinux.org/), so that the Arch Linux community can use it.

**Which solution do you suggest?**  

The following packages:

- `devpod`: The frontend application
- `devpod-cli`: The CLI

**Which alternative solutions exist?**  

N/A

**Additional context**  

I am willing to be a maintainer for the package.

**Comment by 89luca89** [comment]
Hi @IgnisDa 

you're welcome to maintain a community package using the artifacts that we have in the release pages, but we're not interested in maintaining an official AUR/Arch package

Please make clear that the package you're going to do is unofficial, as the only official ones are the one we release here on github :+1:

**Comment by IgnisDa** [comment]
@89luca89 Understood. Where can I get icons assets for devpod?

**Comment by IgnisDa** [comment]
I published the Devpod to https://aur.archlinux.org/packages/devpod. Thanks @89luca89 for your help!
