### ISSUE TITLE
Cannot connect to containers due to pre-existing settings in ~/.ssh/config

### ISSUE THREAD

**Issue by richard-fairthorne** [loft-sh/devpod#899]
**What happened?**  

SSH prompted for a password, VsCode filed to connect to container, only the browser editor works.

**What did you expect to happen instead?**  

VsCode should work fine.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Put the following in your ~/.ssh/config file before starting a container:

Host *
  User root

**SUGGESTED FIX**

SSH prioritizes settings by order, not specificity. Settings higher in the file take priority.

Put devpod sections at the TOP of the ~/.ssh/config file. It would also be wonderful to use an external config file, so the config file doesn't get cluttered/overwhelmed.

My *`devcontainer.json`*:

Not relevant

**Local Environment:**  

Any unix like OS.. (MacOS on my case). Haven't tested windows, but if it uses openssh and config, same problem.

**DevPod Provider:**  
- Cloud Provider: google | aws | azure | digitalOcean
- Kubernetes Provider: [use `kubectl version`]
- Local/remote provider: docker | ssh
- Custom provider: provide imported `provider.yaml` config file

**Anything else we need to know?**

**Comment by richard-fairthorne** [comment]
User workarounds: 
- change the config order after creating the container
- remove any settings that override devpod settings
- do not use a 'Host *' section for default SSH settings

**Comment by pascalbreuninger** [comment]
Hey @richard-fairthorne, that's a fair point. We append it to the SSH file to minimize the possibility of messing anything up, prepending would be very prone to unexpected side effects if you're not aware DevPod is changing your `~/.ssh/config` file. 

However, you can point DevPod to a separate file that's being used for ssh configuration, either by setting it in the context for all workspaces `devpod context set-options -o SSH_CONFIG_PATH=./your_file` or individually per workspace `devpod up --ssh-config=./your_file`

**Comment by richard-fairthorne** [comment]
I appreciate the response.

As far as I have seen, all devpod settings are specific to exactly one host. I may be missing something, but I don't see how options for individual hosts would mess up global settings, or settings for other hosts.

This is a fantastic product, and as a brand new user with no orientation to the product, this was the thing that nearly made me hit "uninstall". I'm glad I persisted. While I've gotten over this hurdle with simple workarounds, as a new user, I couldn't use the product without debugging this problem first.

My initial impression was that the product simply doesn't work.

I understand being cautious about messing up people's config file, but I hope you reconsider the placement of the host configurations.
