### ISSUE TITLE
Add link to docs on how to specify branch

### ISSUE THREAD

**Issue by csantanapr** [loft-sh/devpod#903]
**Is your feature request related to a problem?**  

I can't remember what's the syntax to specify a branch or pull request when I created a new workspace from the UI

**Which solution do you suggest?**  

I think there might be 2 improvements
1. in the current box show @main `github.com/my-org/my-repo@branch`
2. at the bottom put a link "check the [docs](https://devpod.sh/docs/developing-in-workspaces/create-a-workspace#git-repository) for the syntax to specify branch or pull request" docs point to the specific spot in the docs that talk about the syntax of git repo 

![image](https://github.com/loft-sh/devpod/assets/1094878/bb1d0ae0-6dc5-4627-969f-dba1dd8fa890)

**Which alternative solutions exist?**  
1. web search "devpod documentation"
2. devpod search box "branch"

**Additional context**

**Comment by 89luca89** [comment]
Thanks @csantanapr for the suggestions we'll try to improve this part of the UI :+1:
