### ISSUE TITLE
postCreateCommand output shows as errors

### ISSUE THREAD

**Issue by csantanapr** [loft-sh/devpod#907]
**What happened?**  

running devpod that uses a `postCreateCommand` scripts all the commands show as error on the output instead of info
![image](https://github.com/loft-sh/devpod/assets/1094878/6aa66e1d-631d-4ca3-b776-228f08274441)

**What did you expect to happen instead?**  
I expect the output to be info and not indicate error

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*: https://github.com/csantanapr/idpbuilder/blob/codespaces/.devcontainer/devcontainer.json

```
  "postCreateCommand": ".devcontainer/postCreateCommand.sh",
```
The script can have something simple as declaring a variable
https://github.com/csantanapr/idpbuilder/blob/codespaces/.devcontainer/postCreateCommand.sh
```
#!/usr/bin/env sh
set -eux

TARGETOS=linux
TARGETARCH=amd64
```

**Local Environment:**  
- DevPod Version: v0.5.2
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Cloud Provider: aws

**Anything else we need to know?**

**Comment by 89luca89** [comment]
Hi @csantanapr 

This is likely because `set -x` for the debug, uses STDERR, which is interpreted as an error

Because usually STDERR is used for errors

**Comment by timnolte** [comment]
@89luca89 OK, so I was suspecting as much, though I thought I tried also not using `-x` and was still seeing this. 🤔
