### ISSUE TITLE
Timeout creating workspace on DigitalOcean provider

### ISSUE THREAD

**Issue by austinlparker** [loft-sh/devpod#909]
**What happened?**  
When running `devpod up`, the machine gets created but the devpod agent never comes up.

**What did you expect to happen instead?**  
The command to succeed

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Doesn't seem to be related to the devcontainer -- both my custom one as well as the prebuilt node.js one failed.

**Local Environment:**  
- DevPod Version: 0.5.2
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Cloud Provider: digitalOcean

**Anything else we need to know?**  

The only thing I can think that's weird is that I store my SSH Key for DigitalOcean in 1Password and use SSH-Agent and the 1Password CLI. I don't get prompted to unlock the vault when running `devpod up`.

**Comment by austinlparker** [comment]
A couple of things I tried -- first, here's the debug output where it loops while trying to install the agent.

```
18:57:24 info Creating devcontainer...
18:57:24 debug Inject and run command: '/home/devpod/.devpod/devpod' helper ssh-server --stdio --debug
18:57:24 debug Attempting to create SSH client
18:57:24 debug execute inject script
18:57:24 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.2
18:57:24 debug Run command provider command: ${DO_PROVIDER} command
18:57:44 debug done inject
18:57:44 debug done injecting
18:57:44 info Waiting for devpod agent to come up...
18:57:44 debug Inject Error: context deadline exceeded
18:57:44 debug done exec
18:57:47 debug execute inject script
18:57:47 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.2
18:57:47 debug Run command provider command: ${DO_PROVIDER} command
18:58:07 debug done inject
18:58:07 debug done injecting
```

Second, I did think to try and add a SSH key directly rather than using SSH-Agent, but that actually gives a different error:

```
[19:06:37] info Creating devcontainer...
[19:06:37] debug Inject and run command: '/home/devpod/.devpod/devpod' helper ssh-server --stdio --debug
[19:06:37] debug Attempting to create SSH client
[19:06:37] debug execute inject script
[19:06:37] debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.2
[19:06:37] debug Run command provider command: ${DO_PROVIDER} command
[19:06:38] debug done exec
[19:06:38] debug done inject
[19:06:38] debug done injecting
[19:06:38] debug Inject Error: create ssh client: dial to 146.190.157.184:22 failed: dial tcp 146.190.157.184:22: connect: connection refused

EOF
```

**Comment by 89luca89** [comment]
Hi @austinlparker this seems more like the machine is not reachable from you, are you able to test connectivity to the machine outside of devpod?

**Comment by austinlparker** [comment]
You would appear to be correct, although it's odd. I can reach the node from another machine on the same network. Something must be odd about my ssh config?

**Comment by austinlparker** [comment]
Hm, no, still having problems. I tried installing DevPod on the other machine and I'm seeing the same behavior. Weirdly enough if I create the node from one machine then try to ssh from the other, I'm able to connect via ssh.

**Comment by 89luca89** [comment]
@austinlparker I'm not able to reproduce this

![image](https://github.com/loft-sh/devpod/assets/598882/215fdfd4-6330-4675-bcbf-341a0f1dda34)

SSH works correctly both from the provider and from regular SSH

**Comment by austinlparker** [comment]
Ok, I figured this out -- appears to have been an issue with my local network security roles and wifi vs. something with DevPod. I did notice that the DO provider is still being a bit weird because the instance requires a password change on boot and it refuses SSH connections until that happens, but other providers like AWS are working now so I'm unblocked. Sorry for the trouble!
