### ISSUE TITLE
Display the Devpods by "last used at" instead of creation date

### ISSUE THREAD

**Issue by IgnisDa** [loft-sh/devpod#912]
**Is your feature request related to a problem?**  

N/A

**Which solution do you suggest?**  

It would be better UX to sort Devpods by the date they were last updated at.

**Which alternative solutions exist?**  

N/A

**Additional context** 

I am willing to make a PR if accepted.

**Comment by pascalbreuninger** [comment]
Hey @IgnisDa, you're absolutely right, we need to improve the workspace for longer lists

**Comment by pascalbreuninger** [comment]
@IgnisDa you can now filter the workspaces based on:
<img width="532" alt="image" src="https://github.com/loft-sh/devpod/assets/117151367/504909f0-6fa3-431d-9903-f0adb812eb9b">
