### ISSUE TITLE
No easy way to see logs after clicking back button

### ISSUE THREAD

**Issue by IgnisDa** [loft-sh/devpod#922]
**Is your feature request related to a problem?**  

N/A

**Which solution do you suggest?**  

If I click on the back button while building a devcontainer, there is no easy way to show the logs again. I'd prefer there be a "Logs" button in the three dot menu while a devcontainer is being built.

**Which alternative solutions exist?**  

I have found that clicking on "starting <name>" in the notifications leads back to the logs page.

**Additional context** 

N/A

**Comment by pascalbreuninger** [comment]
HI @IgnisDa, you can click on the status ("unknown" in the screenshot) and it'll take you to the latest log output. I agree it's not really discoverable, will add a logs button 
<img width="521" alt="image" src="https://github.com/loft-sh/devpod/assets/117151367/433b2a17-d5d5-40bc-b31e-86ba2cb0e14e">
