### ISSUE TITLE
Running the DevPod gui causes Microsoft Defender to consume large amounts of CPU!

### ISSUE THREAD

**Issue by Gaff** [loft-sh/devpod#956]
**What happened?**  

Running the DevPod gui causes Microsoft Defender Antivirus Software to consume large amounts of CPU!

Quiting devpod causes the CPU from Microsoft Defender to go back down.

**What did you expect to happen instead?**  

I'd expect it to use little CPU!

**How can we reproduce the bug?** (as minimally and precisely as possible)  

For me it was as simple as starting the GUI. No running devpod pods or other docker containers.

**Local Environment:**  
- DevPod Version: 0.54
- Operating System: windows 
- ARCH of the OS: AMD64 

**DevPod Provider:**  
- Cloud Provider: docker
- Kubernetes Provider:  NA
- Local/remote provider: docker | ssh
- Custom provider: provide imported `provider.yaml` config file

**Anything else we need to know?**  

Seems like minimusing to the system tray causes it to reduce CPU losd

**Comment by 89luca89** [comment]
Hi @Gaff do you have any special setup for defender? On my test machine this does not happen and I can't reproduce

**Comment by Gaff** [comment]
ok - it's definitely weird. I don't think I have anything special going on.

I'm using windows 10 and operating on fairly old hardware (i5-4670). Though I don't see how that's particularly relevant.

I see Defender Antivirus at 20-40% CPU with the GUI open, 2-5% without.

If nobody else can reproduce then I guess I'll chalk it up to software-rot on my machine; it's certainly strange though!

**Comment by 89luca89** [comment]
Got it, my test machine is a plain W11 machine, maybe something to do with W10

Will try to reproduce :+1:

**Comment by Gaff** [comment]
![image](https://github.com/loft-sh/devpod/assets/226665/37216b18-bb00-414b-9717-a72c7c448a1a)

Seems to correspond with the visibility of the GUI. I must say there's a lot of process churn when the GUI widget is visible (pictured) that goes away when it's minimised to the system tray.
