### ISSUE TITLE
port forwarding failing - No forwarded ports

### ISSUE THREAD

**Issue by IntranetFactory** [loft-sh/devpod#957]
I have the following `devcontainer.json` to run Playwright tests and to inspect the web browser with [devcontainer VNC Desktop Lite](https://github.com/devcontainers/features/blob/main/src/desktop-lite/NOTES.md):

```json
{
  "name": "Playwright Testing",
  "image": "mcr.microsoft.com/playwright:jammy",
  "forwardPorts": [
    9323,
    6080
  ],
  "portsAttributes": {
    "6080": {
      "label": "desktop"
    }
  },
  "features": {
    "ghcr.io/devcontainers/features/desktop-lite:1": {}
  },
  "postCreateCommand": "npm install && npx playwright install",
  "customizations": {
    "vscode": {
      "extensions": [
        "ms-playwright.playwright"
      ]
    }
  }
}
```

When I open that repo with GitHub Codespace I see the expected VNC port 6080

![image](https://github.com/loft-sh/devpod/assets/7462342/24efe962-13fb-4e13-a4e9-e143eb0b17b5)

When I open with DevPod in a workspace with VS Code on Windows 11 I see no ports:

![image](https://github.com/loft-sh/devpod/assets/7462342/14df639a-f3b9-4121-a96a-8f8637654682)

Should I see port 6080 also when using DevPod ?

**Comment by IntranetFactory** [comment]
I'm sorry, I didn't check that - you are right http://127.0.0.1:6080/ opens the noVNC viewer. So is it expected that the PORTS tab remains empty?

**Comment by pascalbreuninger** [comment]
At least it works, that's something :) For me it shows up sometimes and sometimes it doesn't, haven't figured out how to advertise the ports consistently to VSCode. Maybe this issue is a nice opportunity to dig into it
