### ISSUE TITLE
Add logs option to check container output

### ISSUE THREAD

**Issue by gjhenrique** [loft-sh/devpod#958]
**Is your feature request related to a problem?**  
No. It's not an issue per se

**Which solution do you suggest?**  
We're wrapping devpod to run the development environment for dozens of projects . It would be nice to show developers the logs of the dev container for better introspectability, maybe as a new option; `devpod logs` for example.

**Which alternative solutions exist?**  
One could use `docker logs` (or `kubectl logs` if using the k8s provider) using the right labels, but it would be better to have this inside `devpod`

**Additional context**  
I can add some code if you feel like it's not in your roadmap, given the right directions. We could even add a new option for [custom drivers](https://github.com/loft-sh/devpod/blob/85557b3e1f0379a3ef2f18f0136306be55326f6d/pkg/provider/provider.go#L149-L173) if you think it's a good idea.

**Comment by pascalbreuninger** [comment]
Hi @gjhenrique, great idea. Added a `devpod logs $WORKSPACE_ID` command. Currently works only with machine (cloud) providers and local providers. Will update the kubernetes provider in the next step

**Comment by gjhenrique** [comment]
Thanks @pascalbreuninger. That was surprisingly fast.

You're doing an awesome job building this product. Keep it up :muscle:
