### ISSUE TITLE
SSH host key algorithms

### ISSUE THREAD

**Issue by neingeist** [loft-sh/devpod#960]
**What happened?**  

I set up DevPod (with mrsimonemms/devpod-provider-hetzner) and this worked beautifully, except I couldn't connect with SSH, which also breaks using VSCode (not the browser version).

It turns out that I needed special SSH configuration: `HostKeyAlgorithms rsa-sha2-256,rsa-sha2-512,ssh-rsa` for DevPod, because I have my `ssh` configured to use `HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-ed25519` (via `Match final all`).

**What did you expect to happen instead?**  

That DevPod's SSH server provides ED25519. **Or** that the generated SSH client configuration sets `HostKeyAlgorithms` properly.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Use this in `.ssh/config`:

```
Match final all
  HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-ed25519
```

**Local Environment:**  
- DevPod Version: 0.5.4
- Operating System: linux
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Cloud Provider: **hetzner**
- Kubernetes Provider: (none)
- Local/remote provider:  ssh

**Anything else we need to know?**  
I am not sure if the custom provider (Hetzner) changes anything.

**Comment by neingeist** [comment]
Other than this DevPod works nicely, even with my exotic provider! 🤩

**Comment by pascalbreuninger** [comment]
@neingeist thanks for opening the issue! We'll take a look at it but glad you've found a workaround - might be useful for others in the future as well

**Comment by neingeist** [comment]
`ssh` (the client) is fixed but VSCode chokes on the above workaround, for now using this instead:

```
Host *.devpod
     HostKeyAlgorithms rsa-sha2-256,rsa-sha2-512,ssh-rsa
```
