### ISSUE TITLE
Support Mutagen for file synchronization

### ISSUE THREAD

**Issue by maxbrunet** [loft-sh/devpod#962]
**Is your feature request related to a problem?**

Currently, only VSCode and JetBrains IDE have 1st class support to connect the remote workspace and the local editor. Vim/Neovim have [Netrw](https://devpod.sh/docs/getting-started/quickstart-vim#netrwscp), but this requires the module to be enabled, which is not always desired (e.g. [neo-tree.nvim](https://github.com/nvim-neo-tree/neo-tree.nvim) disables it). Other editors do not have any documented support.

**Which solution do you suggest?**

[Mutagen](https://mutagen.io/) could be used to synchronize the filesystems of the local and remote workspace allowing any local editor to make changes into the remote workspace.

**Which alternative solutions exist?**

At moment, [SSH](https://devpod.sh/docs/getting-started/quickstart-ssh) and setting up an editor on the remote workspace seem to be the alternative.

**Additional context**

As of DevPod v0.5.4, Mutagen fails to create a synchronization session:

```console
$ mutagen sync create . myworkspace.devpod:/workspaces/myworkspace
Connecting to agent (POSIX)...
Error: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to handshake with agent process: unable to receive server magic number: EOF (error output: Connection timed out during banner exchange)
```

**Comment by pascalbreuninger** [comment]
Hi @maxbrunet, thanks for opening the issue. We're investigating options of having file syncing built-in instead of relying on external tools like mutagen, sshfs or rsync

**Comment by leoncamel** [comment]
If you don't consider the license, mutagen is a good idea.
