### ISSUE TITLE
Issue when workspace inactivity timeout runs out or machine stops.

### ISSUE THREAD

**Issue by lazycoder168** [loft-sh/devpod#964]
I have been seeing some issues that I want to raise here in the case of devpods. 
1. When the worspace shuts down, the inactivity timeout is set to be 100mins but the workspace stops sometimes before that. Since 1 workspace is there, the machine stops as well. I have configured devpod using aws as a provider. 
2. Whenever the worspace shuts down while we are in the terminal, 
`15:23:35 info wait: remote command exited without exit status or exit signal
`the above message comes and it hangs the terminal tab. I then have to open another tab to continue work. It gets tedious at times. Is there something I am missing?

**Comment by pascalbreuninger** [comment]
Hey @lazycoder168, thanks for opening the issue. Can you share a bit more of your devcontainer.json and provider setup, IDE option you're using and DevPod version please?
