### ISSUE TITLE
Setup on rootless kubernetes

### ISSUE THREAD

**Issue by danila-grobov** [loft-sh/devpod#969]
Hi,

I'm trying to setup devpod on our kubernetes cluster (openshift) and I am not allowed to create priveleged pods.

So trying to make devpod works has been quite a challenge. I was able to launch the pod and it seems like the whole "devpod up" sequence completes without issues, however vscode throws an ssh error, something about needing a password for su.

Do you have any ideas, what's wrong? Or maybe you could point me to the code where it's implemented? 

How does it establish that tunnel? Wouldn't you have to expose the 22 port on the pod?

Also I couldn't figure out how does it intercept the "container.devpod" hostname?

Thanks!

**Comment by danila-grobov** [comment]
Nevermind, I've figured it out. Just replaced su with a cheeky patch, instead of actually switching the user it just executes whatever is supplied to -c. Works like a charm now!

**Comment by alexandradragodan** [comment]
Hey @danila-grobov 
Thanks for opening the issue. 

Glad it worked out in the meantime. 
Let us know if there's anything else we can help out with.
