### ISSUE TITLE
No support for (forward) http proxy 

### ISSUE THREAD

**Issue by u72z** [loft-sh/devpod#976]
DevPod cannot connect to the internet in an airgapped environment (behind a corporate proxy)

I would expect a proxy option in the settings where to configure the proxy or have it use the system's default

**Comment by J-PC** [comment]
I have the same problem and and I succeeded setting environment variables in powershell and launching DevPod from there.

It obviously respects the http_proxy and https_proxy environment variables but it shouldn't be necessary. A proxy should be configurable from desktop app and CLI setting it manually or better, detecting the system proxy setting on a Windows system like what you can find in Firefox proxy configuration. It's clearly a requirement in a corporate environement.

**Comment by 89luca89** [comment]
Hi @u72z @J-PC 

Yea it would make sense to have an easy to configure (from GUI and CLI) context option for the proxies

Will discuss internally for the feature, or PR are welcome if someone wants to chime in :smile:

**Comment by u72z** [comment]
> I have the same problem and and I succeeded setting environment variables in powershell and launching DevPod from there.

interesting, were you able to have the GUI to connect via the proxy as well or does this only apply to the cli ?

**Comment by 89luca89** [comment]
> > I have the same problem and and I succeeded setting environment variables in powershell and launching DevPod from there.
> 
> interesting, were you able to have the GUI to connect via the proxy as well or does this only apply to the cli ?

if those are env variables they can be passed by the UI using the new `Additional Flags` experimental feature:

![image](https://github.com/loft-sh/devpod/assets/598882/0c7c0b3d-7e61-462d-bfd8-d08c7f891a1d)

**Comment by u72z** [comment]
> > > I have the same problem and and I succeeded setting environment variables in powershell and launching DevPod from there.
> > 
> > 
> > interesting, were you able to have the GUI to connect via the proxy as well or does this only apply to the cli ?
> 
> if those are env variables they can be passed by the UI using the new `Additional Flags` experimental feature:
> 
> ![image](https://private-user-images.githubusercontent.com/598882/317708123-0c7c0b3d-7e61-462d-bfd8-d08c7f891a1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTk3MzAsIm5iZiI6MTcxMjc1OTQzMCwicGF0aCI6Ii81OTg4ODIvMzE3NzA4MTIzLTBjN2MwYjNkLTdlNjEtNDYyZC1iZmQ4LWQwOGM3Zjg5MWExZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxNDMwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2ExMzZlZTRkNWYzNTQ3OWFjNGY2NjBmNjAzNDM4MzdkYTk1MjQ2Y2EwNjM0MTQwMzQ0ZmZlODQ3YzhlNzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vsKPRXT8TDrfd0kfq4SMkyhE5MKLHXFPLD7me2hj3kM)

Running the latest version for Windows and can't see the section `CLI Additional Flags` in the experimental features, am I missing something ? 

![image](https://github.com/loft-sh/devpod/assets/138193092/6b5e3926-155c-4097-a8fd-a2f8bb67fad1)

**Comment by pascalbreuninger** [comment]
@u72z this will be available with `v0.5.5` tomorrow

**Comment by u72z** [comment]
The cli additional flags is indeed available with the v0.5.5 version, but the proxy variables set with --workspace-env HTTP_PROXY=xxx isn't taken into account (upper and lower case)

**Comment by pascalbreuninger** [comment]
@u72z There is no `HTTP_PROXY` env var in your container even after restarting?

**Comment by u72z** [comment]
yes after restarting. I don't think it goes far enough to even start talking about containers.

Adding a provider or a workspace fails (timeout)

Debug mode is enabled but I don't see any trace of this variable.

The first line while starting a workspace is already pretty explicit:

`[12:16:34] debug error sending telemetry request: Post "https://admin.loft.sh/analytics/v1/devpod/v1/events": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[12:16:51] debug Acquire workspace lock...
[12:16:51] debug Acquired workspace lock...
[12:16:51] info Creating devcontainer...
[12:16:51] debug Inject and run command: 'C:\Program Files\DevPod\devpod-cli.exe' helper ssh-server --stdio --debug

[...]

info error downloading workspace vscode-remote-try-node-docker binaries: downloading binary KUBERNETES_PROVIDER: download binary: download file: Head "https://github.com/loft-sh/devpod-provider-kubernetes/releases/download/v0.1.5/devpod-provider-kubernetes-windows-amd64.exe": dial tcp 140.82.121.4:443: connectex
`

**Comment by pascalbreuninger** [comment]
Ah I see, you'd need to set the proxy on the hostmachine as well... Do you use the GUI?

**Comment by u72z** [comment]
yes mainly the UI, can those variables be set for the host machine with cli flags too on devpod level, instead of messing around with the (proxy's) system config ?

**Comment by pascalbreuninger** [comment]
With #1016 you'll be able to set additional environment variables for all commands on your current machine as well 👍 
We'll probably release that in a week, in the meantime I can cut an alpha release

**Comment by pascalbreuninger** [comment]
It's available now with the v0.5.6 release
