### ISSUE TITLE
Unable to run latest release on windows 11 after installation

### ISSUE THREAD

**Issue by faisal-fida** [loft-sh/devpod#981]
**What happened?**  
Unable to run latest release on windows 11 after installation

**How can we reproduce the bug?**
Just install and run the app, it's not even showing anything.

**Local Environment:**  
- DevPod Version: https://github.com/loft-sh/devpod/releases/latest/download/DevPod_windows_x64_en-US.msi
- Operating System: windows 11

**Comment by faisal-fida** [comment]
@89luca89 Can you please confirm, is it only me?

**Comment by 89luca89** [comment]
Hi @faisal-fida need to check will get back :+1:

**Comment by faisal-fida** [comment]
Sure.

**Comment by faisal-fida** [comment]
Sure, @89luca89 I would be waiting for your response 💯

**Comment by Allsimon** [comment]
FWIW, 0.5.7 works fine for me

**Comment by pascalbreuninger** [comment]
@faisal-fida If you still experience the problem please let us know, until then I'm closing the issue
