### ISSUE TITLE
Add option to run vscode as Administrator

### ISSUE THREAD

**Issue by TemimeHammami** [loft-sh/devpod#983]
**Is your feature request related to a problem?**  

 Can't vscode run as Administrator - launch-failed code 18

**Which solution do you suggest?**  
Launch a second instance with code --no-sandbox --disable-gpu-sandbox

**Which alternative solutions exist?**  

**Additional context**  

case when we are not local admin

**Comment by pascalbreuninger** [comment]
Hi @TemimeHammami, thanks for opening the issue. I'm not sure I understand your problem fully, could you provide a couple more details please?
- Operating system
- DevPod version
- VSCode version
