### ISSUE TITLE
Using podman <4.9  with devcontainer features does not work

### ISSUE THREAD

**Issue by aacebedo** [loft-sh/devpod#984]
**What happened?**  

I tried to use devpod with podman on ubuntu 22.04. 
I have devcontainer.json with some features that fail to build with the following error:

```
19:06:47 info Build with internal buildkit...
19:06:47 info unable to upgrade to h2c, received 404
19:06:47 info failed to dial gRPC
```

I have another machine (nixos) with podman 4.9.3. It seems that podman added the support of the command `podman buildx version` in-between as on my ubuntu machine this command returns an error but not on my nixos machine.
Devpod uses the result of this command to choose between the internal buildkit and the docker buildx builder. 
When the command fails it chooses the internal buildkit which, I think, is not compatible with buildah (podman builder) as all APIs of buildkit have not been implemented yet. 

**What did you expect to happen instead?**  

Devpod is able to run with older version of podman.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```
{
        "name": "test",
        "image": "ubuntu:jammy-20240212",
        "runArgs": [
                "--userns",
                "keep-id"
        ],
        "features": {
"any feature"
        }
}

```

**Local Environment:**  
- DevPod Version: 0.5.4
- Operating System:  linux
- ARCH of the OS: AMD64  

**DevPod Provider:**  
- Local/remote provider: docker (with podman)

**Anything else we need to know?**  

It shall be possible to check the real client passed as DOCKER_PATH. When it is podman, the builder shall be buildx and not the internal buildkit.

**Comment by 89luca89** [comment]
Thanks @aacebedo will take a look!

**Comment by aacebedo** [comment]
It shall be fixed now

**Comment by 89luca89** [comment]
Oh great that PR you opened fixed it :+1:  thanks!
