### ISSUE TITLE
Support using config files from user machine for container init when using remote setups

### ISSUE THREAD

**Issue by QAston** [loft-sh/devpod#996]
**Is your feature request related to a problem?**  

It'd be great to be able to run some code that uploads configuration files from the host to the devpod. This works with local docker devpod runs, `initializeCommand` can copy the files to dockerfile context and the data can then be uploaded via dockerfile. Sadly, this doesn't work for remote environments because initializeCommand and docker build are all run remotely, not on the machine with devpod cli and configuration files.

**Which solution do you suggest?**  

Build and run docker images on the machine with `devpod-cli` or add a separate hook that allows uploading files from the host to the remote for this purpose. Similar to how some user files are already propagated (docker, ssh), but customizable.

Alternatively add some other type of custom hook that runs on the machine with devpod cli, so we can ssh/scp the files ourselves.

**Which alternative solutions exist?**  

* Wrap devpod cli in a script that uploads config files and make sure users don't forget to run it - this is the workaround we're currently using

**Comment by pascalbreuninger** [comment]
Hi @QAston, sounds like a good addition. We've discussed adding an `--additional-files` flag to `devpod up` which would
1. Stream these files to the remote machine
2. Mount them into the devcontainer
3. Expose them to lifecycle commands

This would also solve your problem, right?

**Comment by QAston** [comment]
In case we want to be able to run some logic as well to select/prepare files, so I'd personally prefer a custom hook in the config file, similar to the existing hooks but guaranteed to be run. Just having a flag that has to be manually added doesn't provide much over our current approach of wrapping the cli and scp in the wrapper script.

**Comment by pascalbreuninger** [comment]
fair enough. Be aware that if you rely on the customization to spin up your environment correctly you'd loose the ability to create workspace with other supporting tools _and_ you'd expect everybody to have these files on their machines outside of your git repository. This basically creates a loop where you'd now have to standardize the environment _again_

**Comment by euven** [comment]
> Hi @QAston, sounds like a good addition. We've discussed adding an `--additional-files` flag to `devpod up` which would
> 
>     1. Stream these files to the remote machine
> 
>     2. Mount them into the devcontainer
> 
>     3. Expose them to lifecycle commands
> 
> 
> This would also solve your problem, right?

This would solve our problem! :)

**Comment by euven** [comment]
Hi @89luca89 @pascalbreuninger - has this been implemented?

Thanks!
