### ISSUE TITLE
GCP workspace unable to launch for the first time

### ISSUE THREAD

**Issue by SGudbrandsson** [loft-sh/devpod#999]
**What happened?**  
Trying to boot up a new GCP instance doesn't work - stuck in `Waiting for devpod agent to come up...`

**What did you expect to happen instead?**  
Devpod would come up

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Unknown - I haven't been able to boot yet!
Just create a new server in Google, point to a github repo, then wait.

**Local Environment:**  
- DevPod Version: 0.5.5
- Operating System: linux 
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Cloud Provider: google

**Anything else we need to know?**  
Initial test, fresh build, first container.
![image](https://github.com/loft-sh/devpod/assets/1608474/d9e66dbf-5e1f-4e2c-b03f-633af27a38c0)
![image](https://github.com/loft-sh/devpod/assets/1608474/f2fb1a45-0130-4e0a-b8c9-a897ab7ac84c)
No meaningful logs.
![image](https://github.com/loft-sh/devpod/assets/1608474/e7922fad-7ea4-42b5-8351-81f926e92397)

**Comment by SGudbrandsson** [comment]
Here's the log when I try to launch this locally with docker
![image](https://github.com/loft-sh/devpod/assets/1608474/a130fbd8-0b2c-4ffb-a6fb-bb4a7663d88b)

`fatal: could not read Username for 'https://github.com': terminal prompts disabled`

![image](https://github.com/loft-sh/devpod/assets/1608474/e1806a0c-623e-4800-8c40-8d92bb02fbe7)

**Comment by SGudbrandsson** [comment]
The next person reporting an issue gets the lucky #1000 .. maybe I should create a separate issue for the docker stuff? :grin:

**Comment by pascalbreuninger** [comment]
Hey @SGudbrandsson, thanks for reporting the issue.
couple of questions here:
1. What's the configuration for your `gcloud` provider? I just tried with basically no modification and it worked just fine
2.  Regarding the docker issue `fatal: could not read Username for 'https://github.com': terminal prompts disabled`: Are you able to clone the repository using https on your local machine? And if so, do you have an `insteadOf` in your git config?

**Comment by SGudbrandsson** [comment]
Hey @pascalbreuninger, thanks for responding so quickly.

1. I dunno, just vanilla gcloud login. Are you looking for some specifics? Any command you want me to run?
2. Generally I clone with git@... - should I try that instead? This repo is private.

**Comment by pascalbreuninger** [comment]
1. So you just ran `devpod provider add gcloud` without changing any configuration?
2. That's cloning via SSH - should also work though, let me try to reproduce

**Comment by pascalbreuninger** [comment]
Update on the second issue: did you also enter `git@$YOUR_REPO` in the DevPod UI? If not, it'll fall back to https based cloning and you might not have the git credentials helper configure on your host.
